// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

const (
	DeletePipelineByIDServerCloud        string = "cloud"
	DeletePipelineByIDServerCloudGroup   string = "cloud-group"
	DeletePipelineByIDServerManagedGroup string = "managed-group"
)

var DeletePipelineByIDServerList = map[string]string{
	DeletePipelineByIDServerCloud:        "https://app.cribl.cloud",
	DeletePipelineByIDServerCloudGroup:   "https://{workspaceName}-{organizationId}.{cloudDomain}/api/v1/m/{groupName}",
	DeletePipelineByIDServerManagedGroup: "https://{hostname}:{port}/api/v1/m/{groupName}",
}

type DeletePipelineByIDRequest struct {
	// Unique ID to DELETE
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The consumer group to which this instance belongs. Defaults to 'Cribl'.
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
}

func (o *DeletePipelineByIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeletePipelineByIDRequest) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

// DeletePipelineByIDResponseBody - a list of Pipeline objects
type DeletePipelineByIDResponseBody struct {
	Items []shared.Pipeline `json:"items,omitempty"`
}

func (o *DeletePipelineByIDResponseBody) GetItems() []shared.Pipeline {
	if o == nil {
		return nil
	}
	return o.Items
}

type DeletePipelineByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of Pipeline objects
	Object *DeletePipelineByIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *DeletePipelineByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeletePipelineByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeletePipelineByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeletePipelineByIDResponse) GetObject() *DeletePipelineByIDResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *DeletePipelineByIDResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
