// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type DeleteLocalSearchEngineByIDRequest struct {
	// The <code>id</code> of the Local Search engine to delete.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Target engine <code>id</code> that receives the main dataset when the deleted engine currently owns it.
	MainDatasetDestinationEngine *string `queryParam:"style=form,explode=true,name=mainDatasetDestinationEngine"`
}

func (d *DeleteLocalSearchEngineByIDRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeleteLocalSearchEngineByIDRequest) GetMainDatasetDestinationEngine() *string {
	if d == nil {
		return nil
	}
	return d.MainDatasetDestinationEngine
}

type DeleteLocalSearchEngineByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The engine marked for deletion
	CountedLocalSearchEngine *shared.CountedLocalSearchEngine
	// Unexpected error
	Error *shared.Error
}

func (d *DeleteLocalSearchEngineByIDResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteLocalSearchEngineByIDResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteLocalSearchEngineByIDResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteLocalSearchEngineByIDResponse) GetCountedLocalSearchEngine() *shared.CountedLocalSearchEngine {
	if d == nil {
		return nil
	}
	return d.CountedLocalSearchEngine
}

func (d *DeleteLocalSearchEngineByIDResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
