// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

// GetAdminProductsMappingsByProductAndIDProduct - Name of the Cribl product to get the mappings for
type GetAdminProductsMappingsByProductAndIDProduct string

const (
	GetAdminProductsMappingsByProductAndIDProductStream GetAdminProductsMappingsByProductAndIDProduct = "stream"
	GetAdminProductsMappingsByProductAndIDProductEdge   GetAdminProductsMappingsByProductAndIDProduct = "edge"
)

func (e GetAdminProductsMappingsByProductAndIDProduct) ToPointer() *GetAdminProductsMappingsByProductAndIDProduct {
	return &e
}
func (e *GetAdminProductsMappingsByProductAndIDProduct) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stream":
		fallthrough
	case "edge":
		*e = GetAdminProductsMappingsByProductAndIDProduct(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAdminProductsMappingsByProductAndIDProduct: %v", v)
	}
}

type GetAdminProductsMappingsByProductAndIDRequest struct {
	// Name of the Cribl product to get the mappings for
	Product GetAdminProductsMappingsByProductAndIDProduct `pathParam:"style=simple,explode=false,name=product"`
	// The id of the mapping ruleset to get
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetAdminProductsMappingsByProductAndIDRequest) GetProduct() GetAdminProductsMappingsByProductAndIDProduct {
	if g == nil {
		return GetAdminProductsMappingsByProductAndIDProduct("")
	}
	return g.Product
}

func (g *GetAdminProductsMappingsByProductAndIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetAdminProductsMappingsByProductAndIDResponseBody - a list of MappingRuleset objects
type GetAdminProductsMappingsByProductAndIDResponseBody struct {
	Items []shared.MappingRuleset `json:"items,omitempty"`
}

func (g *GetAdminProductsMappingsByProductAndIDResponseBody) GetItems() []shared.MappingRuleset {
	if g == nil {
		return nil
	}
	return g.Items
}

type GetAdminProductsMappingsByProductAndIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of MappingRuleset objects
	Object *GetAdminProductsMappingsByProductAndIDResponseBody
	// Unexpected error
	Error *shared.Error
}

func (g *GetAdminProductsMappingsByProductAndIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAdminProductsMappingsByProductAndIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAdminProductsMappingsByProductAndIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAdminProductsMappingsByProductAndIDResponse) GetObject() *GetAdminProductsMappingsByProductAndIDResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetAdminProductsMappingsByProductAndIDResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
