// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

const (
	GetAuthMultiFactorServerCloud        string = "cloud"
	GetAuthMultiFactorServerCloudGroup   string = "cloud-group"
	GetAuthMultiFactorServerManagedGroup string = "managed-group"
)

var GetAuthMultiFactorServerList = map[string]string{
	GetAuthMultiFactorServerCloud:        "https://app.cribl.cloud",
	GetAuthMultiFactorServerCloudGroup:   "https://{workspaceName}-{organizationId}.{cloudDomain}/api/v1/m/{groupName}",
	GetAuthMultiFactorServerManagedGroup: "https://{hostname}:{port}/api/v1/m/{groupName}",
}

// GetAuthMultiFactorResponseBody - a list of MultiFactorAuthSchema objects
type GetAuthMultiFactorResponseBody struct {
	Items []shared.MultiFactorAuthSchema `json:"items,omitempty"`
}

func (o *GetAuthMultiFactorResponseBody) GetItems() []shared.MultiFactorAuthSchema {
	if o == nil {
		return nil
	}
	return o.Items
}

type GetAuthMultiFactorResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// a list of MultiFactorAuthSchema objects
	Object *GetAuthMultiFactorResponseBody
	// Unexpected error
	Error *shared.Error
}

func (o *GetAuthMultiFactorResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAuthMultiFactorResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAuthMultiFactorResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetAuthMultiFactorResponse) GetObject() *GetAuthMultiFactorResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *GetAuthMultiFactorResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
