// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"net/http"
)

type GetDatatypeRuleByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested lakehouse engine Datatype ruleset
	CountedDatatypeRuleset *shared.CountedDatatypeRuleset
	// Unexpected error
	Error *shared.Error
}

func (g *GetDatatypeRuleByIDResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetDatatypeRuleByIDResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetDatatypeRuleByIDResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetDatatypeRuleByIDResponse) GetCountedDatatypeRuleset() *shared.CountedDatatypeRuleset {
	if g == nil {
		return nil
	}
	return g.CountedDatatypeRuleset
}

func (g *GetDatatypeRuleByIDResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
