// Code generated by tools/codegen. DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestApp(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories:  providerFactory,
		PreventPostDestroyRefresh: true,
		Steps: []resource.TestStep{
			{
				ConfigDirectory: config.StaticDirectory("../../examples/apps"),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("criblio_app.create_app", "id", "terraform-created-app"),
					resource.TestCheckResourceAttr("criblio_app.import_from_file", "id", "terraform-example-app"),
					resource.TestCheckResourceAttr("criblio_app.import_from_url", "id", "url-imported-app"),
					resource.TestCheckResourceAttr("criblio_app.import_from_git", "id", "git-repository-example"),
				),
			},
			{
				ConfigDirectory: config.StaticDirectory("../../examples/apps"),
				PlanOnly:        true,
			},
		},
	})
}
