// Code generated by tools/codegen. DO NOT EDIT.

package tests

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestApp(t *testing.T) {
	if os.Getenv("DEPLOYMENT") == "onprem" {
		t.Skip("Apps API is not supported on-prem")
	}

	suffix := acctest.RandStringFromCharSet(6, acctest.CharSetAlphaNum)
	createID := "tf-created-" + suffix
	fileID := "tf-file-" + suffix
	urlID := "tf-url-" + suffix
	gitID := "tf-git-" + suffix
	configText := appExampleConfig(t, createID, fileID, urlID, gitID)

	checks := []resource.TestCheckFunc{
		resource.TestCheckResourceAttr("criblio_app.import_from_url", "id", urlID),
		resource.TestCheckResourceAttr("criblio_app.import_from_git", "id", gitID),
		resource.TestCheckResourceAttr("criblio_app.create_app", "id", createID),
		resource.TestCheckResourceAttr("criblio_app.import_from_file", "id", fileID),
	}

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories:  providerFactory,
		PreventPostDestroyRefresh: true,
		Steps: []resource.TestStep{
			{
				Config: configText,
				Check:  resource.ComposeAggregateTestCheckFunc(checks...),
			},
			{
				Config:   configText,
				PlanOnly: true,
			},
		},
	})
}

func appExampleConfig(t *testing.T, createID, fileID, urlID, gitID string) string {
	t.Helper()
	content, err := os.ReadFile("../../examples/apps/main.tf")
	if err != nil {
		t.Fatalf("read App example: %v", err)
	}
	archive, err := filepath.Abs("../../examples/apps/terraform-example-app-1.0.0.tgz")
	if err != nil {
		t.Fatalf("resolve App archive: %v", err)
	}
	replacer := strings.NewReplacer(
		`abspath("${path.module}/terraform-example-app-1.0.0.tgz")`, fmt.Sprintf("%q", archive),
		"terraform-created-app", createID,
		"terraform-example-app", fileID,
		"url-imported-app", urlID,
		"git-repository-example", gitID,
	)
	return replacer.Replace(string(content))
}
