// Code generated by tools/codegen. DO NOT EDIT.

package tests

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestRoutesDataSources(t *testing.T) {

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories:  providerFactory,
		PreventPostDestroyRefresh: true,
		Steps: []resource.TestStep{
			{
				Config: `resource "criblio_routes" "my_routes" {
  group_id = "default"
  id = "default"
  routes = [
    {
      description = "Route access logs to main Pipeline"
      filter = "source == \"access.log\""
      name = "my-route"
      pipeline = "main"
      final = true
    }
  ]
}

data "criblio_routes" "by_id" {
  group_id = criblio_routes.my_routes.group_id
  id = criblio_routes.my_routes.id
  depends_on = [criblio_routes.my_routes]
}`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrPair("data.criblio_routes.by_id", "group_id", "criblio_routes.my_routes", "group_id"),
					resource.TestCheckResourceAttrPair("data.criblio_routes.by_id", "id", "criblio_routes.my_routes", "id"),
				),
			},
		},
	})
}
