// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// BackpressureBehaviorOptionsBlockDrop - How to handle events when all receivers are exerting backpressure
type BackpressureBehaviorOptionsBlockDrop string

const (
	// BackpressureBehaviorOptionsBlockDropBlock Block
	BackpressureBehaviorOptionsBlockDropBlock BackpressureBehaviorOptionsBlockDrop = "block"
	// BackpressureBehaviorOptionsBlockDropDrop Drop
	BackpressureBehaviorOptionsBlockDropDrop BackpressureBehaviorOptionsBlockDrop = "drop"
)

func (e BackpressureBehaviorOptionsBlockDrop) ToPointer() *BackpressureBehaviorOptionsBlockDrop {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BackpressureBehaviorOptionsBlockDrop) IsExact() bool {
	if e != nil {
		switch *e {
		case "block", "drop":
			return true
		}
	}
	return false
}
