// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CountedDatatypeRuleset struct {
	Items []DatatypeRuleset `json:"items,omitempty"`
}

func (c *CountedDatatypeRuleset) GetItems() []DatatypeRuleset {
	if c == nil {
		return nil
	}
	return c.Items
}
