// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type DataCompressionFormatOptionsPersistence string

const (
	DataCompressionFormatOptionsPersistenceNone DataCompressionFormatOptionsPersistence = "none"
	DataCompressionFormatOptionsPersistenceGzip DataCompressionFormatOptionsPersistence = "gzip"
)

func (e DataCompressionFormatOptionsPersistence) ToPointer() *DataCompressionFormatOptionsPersistence {
	return &e
}
func (e *DataCompressionFormatOptionsPersistence) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "none":
		fallthrough
	case "gzip":
		*e = DataCompressionFormatOptionsPersistence(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DataCompressionFormatOptionsPersistence: %v", v)
	}
}
