// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FormatOptions string

const (
	FormatOptionsJSON    FormatOptions = "json"
	FormatOptionsParquet FormatOptions = "parquet"
	FormatOptionsDdss    FormatOptions = "ddss"
)

func (e FormatOptions) ToPointer() *FormatOptions {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *FormatOptions) IsExact() bool {
	if e != nil {
		switch *e {
		case "json", "parquet", "ddss":
			return true
		}
	}
	return false
}
