// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type FormatOptions string

const (
	FormatOptionsJSON    FormatOptions = "json"
	FormatOptionsParquet FormatOptions = "parquet"
	FormatOptionsDdss    FormatOptions = "ddss"
)

func (e FormatOptions) ToPointer() *FormatOptions {
	return &e
}
func (e *FormatOptions) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "json":
		fallthrough
	case "parquet":
		fallthrough
	case "ddss":
		*e = FormatOptions(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FormatOptions: %v", v)
	}
}
