// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/internal/utils"
)

type InputS3Type string

const (
	InputS3TypeS3 InputS3Type = "s3"
)

func (e InputS3Type) ToPointer() *InputS3Type {
	return &e
}
func (e *InputS3Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "s3":
		*e = InputS3Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputS3Type: %v", v)
	}
}

type InputS3 struct {
	// Unique ID for this input
	ID       *string     `json:"id,omitempty"`
	Type     InputS3Type `json:"type"`
	Disabled *bool       `json:"disabled,omitempty"`
	// Pipeline to process data from this Source before sending it through the Routes
	Pipeline *string `json:"pipeline,omitempty"`
	// Select whether to send data to Routes, or directly to Destinations.
	SendToRoutes *bool `json:"sendToRoutes,omitempty"`
	// Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
	Environment *string `json:"environment,omitempty"`
	// Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers).
	PqEnabled *bool `json:"pqEnabled,omitempty"`
	// Tags for filtering and grouping in @{product}
	Streamtags []string `json:"streamtags,omitempty"`
	// Direct connections to Destinations, and optionally via a Pipeline or a Pack
	Connections []ItemsTypeConnectionsOptional `json:"connections,omitempty"`
	Pq          *PqType                        `json:"pq,omitempty"`
	// The name, URL, or ARN of the SQS queue to read notifications from. When a non-AWS URL is specified, format must be: '{url}/myQueueName'. Example: 'https://host:port/myQueueName'. Value must be a JavaScript expression (which can evaluate to a constant value), enclosed in quotes or backticks. Can be evaluated only at init time. Example referencing a Global Variable: `https://host:port/myQueue-${C.vars.myVar}`.
	QueueName string `json:"queueName"`
	// Regex matching file names to download and process. Defaults to: .*
	FileFilter *string `json:"fileFilter,omitempty"`
	// SQS queue owner's AWS account ID. Leave empty if SQS queue is in same AWS account.
	AwsAccountID *string `json:"awsAccountId,omitempty"`
	// AWS authentication method. Choose Auto to use IAM roles.
	AwsAuthenticationMethod *AuthenticationMethodOptionsS3CollectorConf `json:"awsAuthenticationMethod,omitempty"`
	AwsSecretKey            *string                                     `json:"awsSecretKey,omitempty"`
	// AWS Region where the S3 bucket and SQS queue are located. Required, unless the Queue entry is a URL or ARN that includes a Region.
	Region *string `json:"region,omitempty"`
	// S3 service endpoint. If empty, defaults to the AWS Region-specific endpoint. Otherwise, it must point to S3-compatible endpoint.
	Endpoint *string `json:"endpoint,omitempty"`
	// Signature version to use for signing S3 requests
	SignatureVersion *SignatureVersionOptionsS3CollectorConf `json:"signatureVersion,omitempty"`
	// Reuse connections between requests, which can improve performance
	ReuseConnections *bool `json:"reuseConnections,omitempty"`
	// Reject certificates that cannot be verified against a valid CA, such as self-signed certificates
	RejectUnauthorized *bool `json:"rejectUnauthorized,omitempty"`
	// A list of event-breaking rulesets that will be applied, in order, to the input data stream
	BreakerRulesets []string `json:"breakerRulesets,omitempty"`
	// How long (in milliseconds) the Event Breaker will wait for new data to be sent to a specific channel before flushing the data stream out, as is, to the Pipelines
	StaleChannelFlushMs *float64 `json:"staleChannelFlushMs,omitempty"`
	// The maximum number of messages SQS should return in a poll request. Amazon SQS never returns more messages than this value (however, fewer messages might be returned). Valid values: 1 to 10.
	MaxMessages *float64 `json:"maxMessages,omitempty"`
	// After messages are retrieved by a ReceiveMessage request, @{product} will hide them from subsequent retrieve requests for at least this duration. You can set this as high as 43200 sec. (12 hours).
	VisibilityTimeout *float64 `json:"visibilityTimeout,omitempty"`
	// How many receiver processes to run. The higher the number, the better the throughput - at the expense of CPU overhead.
	NumReceivers *float64 `json:"numReceivers,omitempty"`
	// Socket inactivity timeout (in seconds). Increase this value if timeouts occur due to backpressure.
	SocketTimeout *float64 `json:"socketTimeout,omitempty"`
	// Skip files that trigger a processing error. Disabled by default, which allows retries after processing errors.
	SkipOnError *bool `json:"skipOnError,omitempty"`
	// Attach SQS notification metadata to a __sqsMetadata field on each event
	IncludeSqsMetadata *bool `json:"includeSqsMetadata,omitempty"`
	// Use Assume Role credentials to access Amazon S3
	EnableAssumeRole *bool `json:"enableAssumeRole,omitempty"`
	// Amazon Resource Name (ARN) of the role to assume
	AssumeRoleArn *string `json:"assumeRoleArn,omitempty"`
	// External ID to use when assuming role
	AssumeRoleExternalID *string `json:"assumeRoleExternalId,omitempty"`
	// Duration of the assumed role's session, in seconds. Minimum is 900 (15 minutes), default is 3600 (1 hour), and maximum is 43200 (12 hours).
	DurationSeconds *float64 `json:"durationSeconds,omitempty"`
	// Use Assume Role credentials when accessing Amazon SQS
	EnableSQSAssumeRole *bool           `json:"enableSQSAssumeRole,omitempty"`
	Preprocess          *PreprocessType `json:"preprocess,omitempty"`
	// Fields to add to events from this input
	Metadata []ItemsTypeMetadata `json:"metadata,omitempty"`
	// Maximum file size for each Parquet chunk
	ParquetChunkSizeMB *float64 `json:"parquetChunkSizeMB,omitempty"`
	// The maximum time allowed for downloading a Parquet chunk. Processing will stop if a chunk cannot be downloaded within the time specified.
	ParquetChunkDownloadTimeout *float64           `json:"parquetChunkDownloadTimeout,omitempty"`
	Checkpointing               *CheckpointingType `json:"checkpointing,omitempty"`
	// How long to wait for events before trying polling again. The lower the number the higher the AWS bill. The higher the number the longer it will take for the source to react to configuration changes and system restarts.
	PollTimeout *float64 `json:"pollTimeout,omitempty"`
	// Character encoding to use when parsing ingested data. When not set, @{product} will default to UTF-8 but may incorrectly interpret multi-byte characters.
	Encoding *string `json:"encoding,omitempty"`
	// Add a tag to processed S3 objects. Requires s3:GetObjectTagging and s3:PutObjectTagging AWS permissions.
	TagAfterProcessing *bool   `json:"tagAfterProcessing,omitempty"`
	Description        *string `json:"description,omitempty"`
	AwsAPIKey          *string `json:"awsApiKey,omitempty"`
	// Select or create a stored secret that references your access key and secret key
	AwsSecret *string `json:"awsSecret,omitempty"`
	// The key for the S3 object tag applied after processing. This field accepts an expression for dynamic generation.
	ProcessedTagKey *string `json:"processedTagKey,omitempty"`
	// The value for the S3 object tag applied after processing. This field accepts an expression for dynamic generation.
	ProcessedTagValue *string `json:"processedTagValue,omitempty"`
	// Binds 'queueName' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'queueName' at runtime.
	TemplateQueueName *string `json:"__template_queueName,omitempty"`
	// Binds 'awsAccountId' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'awsAccountId' at runtime.
	TemplateAwsAccountID *string `json:"__template_awsAccountId,omitempty"`
	// Binds 'awsSecretKey' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'awsSecretKey' at runtime.
	TemplateAwsSecretKey *string `json:"__template_awsSecretKey,omitempty"`
	// Binds 'region' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'region' at runtime.
	TemplateRegion *string `json:"__template_region,omitempty"`
	// Binds 'assumeRoleArn' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'assumeRoleArn' at runtime.
	TemplateAssumeRoleArn *string `json:"__template_assumeRoleArn,omitempty"`
	// Binds 'assumeRoleExternalId' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'assumeRoleExternalId' at runtime.
	TemplateAssumeRoleExternalID *string `json:"__template_assumeRoleExternalId,omitempty"`
	// Binds 'awsApiKey' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'awsApiKey' at runtime.
	TemplateAwsAPIKey *string `json:"__template_awsApiKey,omitempty"`
}

func (i InputS3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputS3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"type", "queueName"}); err != nil {
		return err
	}
	return nil
}

func (i *InputS3) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *InputS3) GetType() InputS3Type {
	if i == nil {
		return InputS3Type("")
	}
	return i.Type
}

func (i *InputS3) GetDisabled() *bool {
	if i == nil {
		return nil
	}
	return i.Disabled
}

func (i *InputS3) GetPipeline() *string {
	if i == nil {
		return nil
	}
	return i.Pipeline
}

func (i *InputS3) GetSendToRoutes() *bool {
	if i == nil {
		return nil
	}
	return i.SendToRoutes
}

func (i *InputS3) GetEnvironment() *string {
	if i == nil {
		return nil
	}
	return i.Environment
}

func (i *InputS3) GetPqEnabled() *bool {
	if i == nil {
		return nil
	}
	return i.PqEnabled
}

func (i *InputS3) GetStreamtags() []string {
	if i == nil {
		return nil
	}
	return i.Streamtags
}

func (i *InputS3) GetConnections() []ItemsTypeConnectionsOptional {
	if i == nil {
		return nil
	}
	return i.Connections
}

func (i *InputS3) GetPq() *PqType {
	if i == nil {
		return nil
	}
	return i.Pq
}

func (i *InputS3) GetQueueName() string {
	if i == nil {
		return ""
	}
	return i.QueueName
}

func (i *InputS3) GetFileFilter() *string {
	if i == nil {
		return nil
	}
	return i.FileFilter
}

func (i *InputS3) GetAwsAccountID() *string {
	if i == nil {
		return nil
	}
	return i.AwsAccountID
}

func (i *InputS3) GetAwsAuthenticationMethod() *AuthenticationMethodOptionsS3CollectorConf {
	if i == nil {
		return nil
	}
	return i.AwsAuthenticationMethod
}

func (i *InputS3) GetAwsSecretKey() *string {
	if i == nil {
		return nil
	}
	return i.AwsSecretKey
}

func (i *InputS3) GetRegion() *string {
	if i == nil {
		return nil
	}
	return i.Region
}

func (i *InputS3) GetEndpoint() *string {
	if i == nil {
		return nil
	}
	return i.Endpoint
}

func (i *InputS3) GetSignatureVersion() *SignatureVersionOptionsS3CollectorConf {
	if i == nil {
		return nil
	}
	return i.SignatureVersion
}

func (i *InputS3) GetReuseConnections() *bool {
	if i == nil {
		return nil
	}
	return i.ReuseConnections
}

func (i *InputS3) GetRejectUnauthorized() *bool {
	if i == nil {
		return nil
	}
	return i.RejectUnauthorized
}

func (i *InputS3) GetBreakerRulesets() []string {
	if i == nil {
		return nil
	}
	return i.BreakerRulesets
}

func (i *InputS3) GetStaleChannelFlushMs() *float64 {
	if i == nil {
		return nil
	}
	return i.StaleChannelFlushMs
}

func (i *InputS3) GetMaxMessages() *float64 {
	if i == nil {
		return nil
	}
	return i.MaxMessages
}

func (i *InputS3) GetVisibilityTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.VisibilityTimeout
}

func (i *InputS3) GetNumReceivers() *float64 {
	if i == nil {
		return nil
	}
	return i.NumReceivers
}

func (i *InputS3) GetSocketTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.SocketTimeout
}

func (i *InputS3) GetSkipOnError() *bool {
	if i == nil {
		return nil
	}
	return i.SkipOnError
}

func (i *InputS3) GetIncludeSqsMetadata() *bool {
	if i == nil {
		return nil
	}
	return i.IncludeSqsMetadata
}

func (i *InputS3) GetEnableAssumeRole() *bool {
	if i == nil {
		return nil
	}
	return i.EnableAssumeRole
}

func (i *InputS3) GetAssumeRoleArn() *string {
	if i == nil {
		return nil
	}
	return i.AssumeRoleArn
}

func (i *InputS3) GetAssumeRoleExternalID() *string {
	if i == nil {
		return nil
	}
	return i.AssumeRoleExternalID
}

func (i *InputS3) GetDurationSeconds() *float64 {
	if i == nil {
		return nil
	}
	return i.DurationSeconds
}

func (i *InputS3) GetEnableSQSAssumeRole() *bool {
	if i == nil {
		return nil
	}
	return i.EnableSQSAssumeRole
}

func (i *InputS3) GetPreprocess() *PreprocessType {
	if i == nil {
		return nil
	}
	return i.Preprocess
}

func (i *InputS3) GetMetadata() []ItemsTypeMetadata {
	if i == nil {
		return nil
	}
	return i.Metadata
}

func (i *InputS3) GetParquetChunkSizeMB() *float64 {
	if i == nil {
		return nil
	}
	return i.ParquetChunkSizeMB
}

func (i *InputS3) GetParquetChunkDownloadTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.ParquetChunkDownloadTimeout
}

func (i *InputS3) GetCheckpointing() *CheckpointingType {
	if i == nil {
		return nil
	}
	return i.Checkpointing
}

func (i *InputS3) GetPollTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.PollTimeout
}

func (i *InputS3) GetEncoding() *string {
	if i == nil {
		return nil
	}
	return i.Encoding
}

func (i *InputS3) GetTagAfterProcessing() *bool {
	if i == nil {
		return nil
	}
	return i.TagAfterProcessing
}

func (i *InputS3) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *InputS3) GetAwsAPIKey() *string {
	if i == nil {
		return nil
	}
	return i.AwsAPIKey
}

func (i *InputS3) GetAwsSecret() *string {
	if i == nil {
		return nil
	}
	return i.AwsSecret
}

func (i *InputS3) GetProcessedTagKey() *string {
	if i == nil {
		return nil
	}
	return i.ProcessedTagKey
}

func (i *InputS3) GetProcessedTagValue() *string {
	if i == nil {
		return nil
	}
	return i.ProcessedTagValue
}

func (i *InputS3) GetTemplateQueueName() *string {
	if i == nil {
		return nil
	}
	return i.TemplateQueueName
}

func (i *InputS3) GetTemplateAwsAccountID() *string {
	if i == nil {
		return nil
	}
	return i.TemplateAwsAccountID
}

func (i *InputS3) GetTemplateAwsSecretKey() *string {
	if i == nil {
		return nil
	}
	return i.TemplateAwsSecretKey
}

func (i *InputS3) GetTemplateRegion() *string {
	if i == nil {
		return nil
	}
	return i.TemplateRegion
}

func (i *InputS3) GetTemplateAssumeRoleArn() *string {
	if i == nil {
		return nil
	}
	return i.TemplateAssumeRoleArn
}

func (i *InputS3) GetTemplateAssumeRoleExternalID() *string {
	if i == nil {
		return nil
	}
	return i.TemplateAssumeRoleExternalID
}

func (i *InputS3) GetTemplateAwsAPIKey() *string {
	if i == nil {
		return nil
	}
	return i.TemplateAwsAPIKey
}
