// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/internal/utils"
)

type InputWindowsMetricsType string

const (
	InputWindowsMetricsTypeWindowsMetrics InputWindowsMetricsType = "windows_metrics"
)

func (e InputWindowsMetricsType) ToPointer() *InputWindowsMetricsType {
	return &e
}
func (e *InputWindowsMetricsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "windows_metrics":
		*e = InputWindowsMetricsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputWindowsMetricsType: %v", v)
	}
}

// InputWindowsMetricsSystemMode - Select the level of details for system metrics
type InputWindowsMetricsSystemMode string

const (
	// InputWindowsMetricsSystemModeBasic Basic
	InputWindowsMetricsSystemModeBasic InputWindowsMetricsSystemMode = "basic"
	// InputWindowsMetricsSystemModeAll All
	InputWindowsMetricsSystemModeAll InputWindowsMetricsSystemMode = "all"
	// InputWindowsMetricsSystemModeCustom Custom
	InputWindowsMetricsSystemModeCustom InputWindowsMetricsSystemMode = "custom"
	// InputWindowsMetricsSystemModeDisabled Disabled
	InputWindowsMetricsSystemModeDisabled InputWindowsMetricsSystemMode = "disabled"
)

func (e InputWindowsMetricsSystemMode) ToPointer() *InputWindowsMetricsSystemMode {
	return &e
}
func (e *InputWindowsMetricsSystemMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "basic":
		fallthrough
	case "all":
		fallthrough
	case "custom":
		fallthrough
	case "disabled":
		*e = InputWindowsMetricsSystemMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputWindowsMetricsSystemMode: %v", v)
	}
}

type InputWindowsMetricsSystem struct {
	// Select the level of details for system metrics
	Mode *InputWindowsMetricsSystemMode `json:"mode,omitempty"`
	// Generate metrics for all system information
	Detail *bool `json:"detail,omitempty"`
}

func (i InputWindowsMetricsSystem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWindowsMetricsSystem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputWindowsMetricsSystem) GetMode() *InputWindowsMetricsSystemMode {
	if i == nil {
		return nil
	}
	return i.Mode
}

func (i *InputWindowsMetricsSystem) GetDetail() *bool {
	if i == nil {
		return nil
	}
	return i.Detail
}

// InputWindowsMetricsCPUMode - Select the level of details for CPU metrics
type InputWindowsMetricsCPUMode string

const (
	// InputWindowsMetricsCPUModeBasic Basic
	InputWindowsMetricsCPUModeBasic InputWindowsMetricsCPUMode = "basic"
	// InputWindowsMetricsCPUModeAll All
	InputWindowsMetricsCPUModeAll InputWindowsMetricsCPUMode = "all"
	// InputWindowsMetricsCPUModeCustom Custom
	InputWindowsMetricsCPUModeCustom InputWindowsMetricsCPUMode = "custom"
	// InputWindowsMetricsCPUModeDisabled Disabled
	InputWindowsMetricsCPUModeDisabled InputWindowsMetricsCPUMode = "disabled"
)

func (e InputWindowsMetricsCPUMode) ToPointer() *InputWindowsMetricsCPUMode {
	return &e
}
func (e *InputWindowsMetricsCPUMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "basic":
		fallthrough
	case "all":
		fallthrough
	case "custom":
		fallthrough
	case "disabled":
		*e = InputWindowsMetricsCPUMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputWindowsMetricsCPUMode: %v", v)
	}
}

type InputWindowsMetricsCPU struct {
	// Select the level of details for CPU metrics
	Mode *InputWindowsMetricsCPUMode `json:"mode,omitempty"`
	// Generate metrics for each CPU
	PerCPU *bool `json:"perCpu,omitempty"`
	// Generate metrics for all CPU states
	Detail *bool `json:"detail,omitempty"`
	// Generate raw, monotonic CPU time counters
	Time *bool `json:"time,omitempty"`
}

func (i InputWindowsMetricsCPU) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWindowsMetricsCPU) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputWindowsMetricsCPU) GetMode() *InputWindowsMetricsCPUMode {
	if i == nil {
		return nil
	}
	return i.Mode
}

func (i *InputWindowsMetricsCPU) GetPerCPU() *bool {
	if i == nil {
		return nil
	}
	return i.PerCPU
}

func (i *InputWindowsMetricsCPU) GetDetail() *bool {
	if i == nil {
		return nil
	}
	return i.Detail
}

func (i *InputWindowsMetricsCPU) GetTime() *bool {
	if i == nil {
		return nil
	}
	return i.Time
}

// InputWindowsMetricsMemoryMode - Select the level of details for memory metrics
type InputWindowsMetricsMemoryMode string

const (
	// InputWindowsMetricsMemoryModeBasic Basic
	InputWindowsMetricsMemoryModeBasic InputWindowsMetricsMemoryMode = "basic"
	// InputWindowsMetricsMemoryModeAll All
	InputWindowsMetricsMemoryModeAll InputWindowsMetricsMemoryMode = "all"
	// InputWindowsMetricsMemoryModeCustom Custom
	InputWindowsMetricsMemoryModeCustom InputWindowsMetricsMemoryMode = "custom"
	// InputWindowsMetricsMemoryModeDisabled Disabled
	InputWindowsMetricsMemoryModeDisabled InputWindowsMetricsMemoryMode = "disabled"
)

func (e InputWindowsMetricsMemoryMode) ToPointer() *InputWindowsMetricsMemoryMode {
	return &e
}
func (e *InputWindowsMetricsMemoryMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "basic":
		fallthrough
	case "all":
		fallthrough
	case "custom":
		fallthrough
	case "disabled":
		*e = InputWindowsMetricsMemoryMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputWindowsMetricsMemoryMode: %v", v)
	}
}

type InputWindowsMetricsMemory struct {
	// Select the level of details for memory metrics
	Mode *InputWindowsMetricsMemoryMode `json:"mode,omitempty"`
	// Generate metrics for all memory states
	Detail *bool `json:"detail,omitempty"`
}

func (i InputWindowsMetricsMemory) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWindowsMetricsMemory) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputWindowsMetricsMemory) GetMode() *InputWindowsMetricsMemoryMode {
	if i == nil {
		return nil
	}
	return i.Mode
}

func (i *InputWindowsMetricsMemory) GetDetail() *bool {
	if i == nil {
		return nil
	}
	return i.Detail
}

// InputWindowsMetricsNetworkMode - Select the level of details for network metrics
type InputWindowsMetricsNetworkMode string

const (
	// InputWindowsMetricsNetworkModeBasic Basic
	InputWindowsMetricsNetworkModeBasic InputWindowsMetricsNetworkMode = "basic"
	// InputWindowsMetricsNetworkModeAll All
	InputWindowsMetricsNetworkModeAll InputWindowsMetricsNetworkMode = "all"
	// InputWindowsMetricsNetworkModeCustom Custom
	InputWindowsMetricsNetworkModeCustom InputWindowsMetricsNetworkMode = "custom"
	// InputWindowsMetricsNetworkModeDisabled Disabled
	InputWindowsMetricsNetworkModeDisabled InputWindowsMetricsNetworkMode = "disabled"
)

func (e InputWindowsMetricsNetworkMode) ToPointer() *InputWindowsMetricsNetworkMode {
	return &e
}
func (e *InputWindowsMetricsNetworkMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "basic":
		fallthrough
	case "all":
		fallthrough
	case "custom":
		fallthrough
	case "disabled":
		*e = InputWindowsMetricsNetworkMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputWindowsMetricsNetworkMode: %v", v)
	}
}

type InputWindowsMetricsNetwork struct {
	// Select the level of details for network metrics
	Mode *InputWindowsMetricsNetworkMode `json:"mode,omitempty"`
	// Generate full network metrics
	Detail *bool `json:"detail,omitempty"`
	// Generate protocol metrics for ICMP, ICMPMsg, IP, TCP, UDP and UDPLite
	Protocols *bool `json:"protocols,omitempty"`
	// Network interfaces to include/exclude. All interfaces are included if this list is empty.
	Devices []string `json:"devices,omitempty"`
	// Generate separate metrics for each interface
	PerInterface *bool `json:"perInterface,omitempty"`
}

func (i InputWindowsMetricsNetwork) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWindowsMetricsNetwork) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputWindowsMetricsNetwork) GetMode() *InputWindowsMetricsNetworkMode {
	if i == nil {
		return nil
	}
	return i.Mode
}

func (i *InputWindowsMetricsNetwork) GetDetail() *bool {
	if i == nil {
		return nil
	}
	return i.Detail
}

func (i *InputWindowsMetricsNetwork) GetProtocols() *bool {
	if i == nil {
		return nil
	}
	return i.Protocols
}

func (i *InputWindowsMetricsNetwork) GetDevices() []string {
	if i == nil {
		return nil
	}
	return i.Devices
}

func (i *InputWindowsMetricsNetwork) GetPerInterface() *bool {
	if i == nil {
		return nil
	}
	return i.PerInterface
}

// InputWindowsMetricsDiskMode - Select the level of details for disk metrics
type InputWindowsMetricsDiskMode string

const (
	// InputWindowsMetricsDiskModeBasic Basic
	InputWindowsMetricsDiskModeBasic InputWindowsMetricsDiskMode = "basic"
	// InputWindowsMetricsDiskModeAll All
	InputWindowsMetricsDiskModeAll InputWindowsMetricsDiskMode = "all"
	// InputWindowsMetricsDiskModeCustom Custom
	InputWindowsMetricsDiskModeCustom InputWindowsMetricsDiskMode = "custom"
	// InputWindowsMetricsDiskModeDisabled Disabled
	InputWindowsMetricsDiskModeDisabled InputWindowsMetricsDiskMode = "disabled"
)

func (e InputWindowsMetricsDiskMode) ToPointer() *InputWindowsMetricsDiskMode {
	return &e
}
func (e *InputWindowsMetricsDiskMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "basic":
		fallthrough
	case "all":
		fallthrough
	case "custom":
		fallthrough
	case "disabled":
		*e = InputWindowsMetricsDiskMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputWindowsMetricsDiskMode: %v", v)
	}
}

type InputWindowsMetricsDisk struct {
	// Select the level of details for disk metrics
	Mode *InputWindowsMetricsDiskMode `json:"mode,omitempty"`
	// Generate separate metrics for each volume
	PerVolume *bool `json:"perVolume,omitempty"`
	// Generate full disk metrics
	Detail *bool `json:"detail,omitempty"`
	// Windows volumes to include/exclude. E.g.: C:, !E:, etc. Wildcards and ! (not) operators are supported. All volumes are included if this list is empty.
	Volumes []string `json:"volumes,omitempty"`
}

func (i InputWindowsMetricsDisk) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWindowsMetricsDisk) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputWindowsMetricsDisk) GetMode() *InputWindowsMetricsDiskMode {
	if i == nil {
		return nil
	}
	return i.Mode
}

func (i *InputWindowsMetricsDisk) GetPerVolume() *bool {
	if i == nil {
		return nil
	}
	return i.PerVolume
}

func (i *InputWindowsMetricsDisk) GetDetail() *bool {
	if i == nil {
		return nil
	}
	return i.Detail
}

func (i *InputWindowsMetricsDisk) GetVolumes() []string {
	if i == nil {
		return nil
	}
	return i.Volumes
}

type InputWindowsMetricsCustom struct {
	System  *InputWindowsMetricsSystem  `json:"system,omitempty"`
	CPU     *InputWindowsMetricsCPU     `json:"cpu,omitempty"`
	Memory  *InputWindowsMetricsMemory  `json:"memory,omitempty"`
	Network *InputWindowsMetricsNetwork `json:"network,omitempty"`
	Disk    *InputWindowsMetricsDisk    `json:"disk,omitempty"`
}

func (i InputWindowsMetricsCustom) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWindowsMetricsCustom) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputWindowsMetricsCustom) GetSystem() *InputWindowsMetricsSystem {
	if i == nil {
		return nil
	}
	return i.System
}

func (i *InputWindowsMetricsCustom) GetCPU() *InputWindowsMetricsCPU {
	if i == nil {
		return nil
	}
	return i.CPU
}

func (i *InputWindowsMetricsCustom) GetMemory() *InputWindowsMetricsMemory {
	if i == nil {
		return nil
	}
	return i.Memory
}

func (i *InputWindowsMetricsCustom) GetNetwork() *InputWindowsMetricsNetwork {
	if i == nil {
		return nil
	}
	return i.Network
}

func (i *InputWindowsMetricsCustom) GetDisk() *InputWindowsMetricsDisk {
	if i == nil {
		return nil
	}
	return i.Disk
}

type InputWindowsMetricsHost struct {
	// Select level of detail for host metrics
	Mode   *ModeOptionsHost           `json:"mode,omitempty"`
	Custom *InputWindowsMetricsCustom `json:"custom,omitempty"`
}

func (i InputWindowsMetricsHost) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWindowsMetricsHost) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputWindowsMetricsHost) GetMode() *ModeOptionsHost {
	if i == nil {
		return nil
	}
	return i.Mode
}

func (i *InputWindowsMetricsHost) GetCustom() *InputWindowsMetricsCustom {
	if i == nil {
		return nil
	}
	return i.Custom
}

type InputWindowsMetricsPersistence struct {
	// Spool metrics to disk for Cribl Edge and Search
	Enable *bool `json:"enable,omitempty"`
	// Time span for each file bucket
	TimeWindow *string `json:"timeWindow,omitempty"`
	// Maximum disk space allowed to be consumed (examples: 420MB, 4GB). When limit is reached, older data will be deleted.
	MaxDataSize *string `json:"maxDataSize,omitempty"`
	// Maximum amount of time to retain data (examples: 2h, 4d). When limit is reached, older data will be deleted.
	MaxDataTime *string                                  `json:"maxDataTime,omitempty"`
	Compress    *DataCompressionFormatOptionsPersistence `json:"compress,omitempty"`
	// Path to use to write metrics. Defaults to $CRIBL_HOME/state/windows_metrics
	DestPath *string `json:"destPath,omitempty"`
}

func (i InputWindowsMetricsPersistence) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWindowsMetricsPersistence) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputWindowsMetricsPersistence) GetEnable() *bool {
	if i == nil {
		return nil
	}
	return i.Enable
}

func (i *InputWindowsMetricsPersistence) GetTimeWindow() *string {
	if i == nil {
		return nil
	}
	return i.TimeWindow
}

func (i *InputWindowsMetricsPersistence) GetMaxDataSize() *string {
	if i == nil {
		return nil
	}
	return i.MaxDataSize
}

func (i *InputWindowsMetricsPersistence) GetMaxDataTime() *string {
	if i == nil {
		return nil
	}
	return i.MaxDataTime
}

func (i *InputWindowsMetricsPersistence) GetCompress() *DataCompressionFormatOptionsPersistence {
	if i == nil {
		return nil
	}
	return i.Compress
}

func (i *InputWindowsMetricsPersistence) GetDestPath() *string {
	if i == nil {
		return nil
	}
	return i.DestPath
}

type InputWindowsMetrics struct {
	// Unique ID for this input
	ID       *string                 `json:"id,omitempty"`
	Type     InputWindowsMetricsType `json:"type"`
	Disabled *bool                   `json:"disabled,omitempty"`
	// Pipeline to process data from this Source before sending it through the Routes
	Pipeline *string `json:"pipeline,omitempty"`
	// Select whether to send data to Routes, or directly to Destinations.
	SendToRoutes *bool `json:"sendToRoutes,omitempty"`
	// Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
	Environment *string `json:"environment,omitempty"`
	// Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers).
	PqEnabled *bool `json:"pqEnabled,omitempty"`
	// Tags for filtering and grouping in @{product}
	Streamtags []string `json:"streamtags,omitempty"`
	// Direct connections to Destinations, and optionally via a Pipeline or a Pack
	Connections []ItemsTypeConnectionsOptional `json:"connections,omitempty"`
	Pq          *PqType                        `json:"pq,omitempty"`
	// Time, in seconds, between consecutive metric collections. Default is 10 seconds.
	Interval *float64                 `json:"interval,omitempty"`
	Host     *InputWindowsMetricsHost `json:"host,omitempty"`
	Process  *ProcessType             `json:"process,omitempty"`
	// Fields to add to events from this input
	Metadata    []ItemsTypeMetadata             `json:"metadata,omitempty"`
	Persistence *InputWindowsMetricsPersistence `json:"persistence,omitempty"`
	// Enable to use built-in tools (PowerShell) to collect metrics instead of native API (default) [Learn more](https://docs.cribl.io/edge/sources-windows-metrics/#advanced-tab)
	DisableNativeModule *bool   `json:"disableNativeModule,omitempty"`
	Description         *string `json:"description,omitempty"`
}

func (i InputWindowsMetrics) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputWindowsMetrics) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputWindowsMetrics) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *InputWindowsMetrics) GetType() InputWindowsMetricsType {
	if i == nil {
		return InputWindowsMetricsType("")
	}
	return i.Type
}

func (i *InputWindowsMetrics) GetDisabled() *bool {
	if i == nil {
		return nil
	}
	return i.Disabled
}

func (i *InputWindowsMetrics) GetPipeline() *string {
	if i == nil {
		return nil
	}
	return i.Pipeline
}

func (i *InputWindowsMetrics) GetSendToRoutes() *bool {
	if i == nil {
		return nil
	}
	return i.SendToRoutes
}

func (i *InputWindowsMetrics) GetEnvironment() *string {
	if i == nil {
		return nil
	}
	return i.Environment
}

func (i *InputWindowsMetrics) GetPqEnabled() *bool {
	if i == nil {
		return nil
	}
	return i.PqEnabled
}

func (i *InputWindowsMetrics) GetStreamtags() []string {
	if i == nil {
		return nil
	}
	return i.Streamtags
}

func (i *InputWindowsMetrics) GetConnections() []ItemsTypeConnectionsOptional {
	if i == nil {
		return nil
	}
	return i.Connections
}

func (i *InputWindowsMetrics) GetPq() *PqType {
	if i == nil {
		return nil
	}
	return i.Pq
}

func (i *InputWindowsMetrics) GetInterval() *float64 {
	if i == nil {
		return nil
	}
	return i.Interval
}

func (i *InputWindowsMetrics) GetHost() *InputWindowsMetricsHost {
	if i == nil {
		return nil
	}
	return i.Host
}

func (i *InputWindowsMetrics) GetProcess() *ProcessType {
	if i == nil {
		return nil
	}
	return i.Process
}

func (i *InputWindowsMetrics) GetMetadata() []ItemsTypeMetadata {
	if i == nil {
		return nil
	}
	return i.Metadata
}

func (i *InputWindowsMetrics) GetPersistence() *InputWindowsMetricsPersistence {
	if i == nil {
		return nil
	}
	return i.Persistence
}

func (i *InputWindowsMetrics) GetDisableNativeModule() *bool {
	if i == nil {
		return nil
	}
	return i.DisableNativeModule
}

func (i *InputWindowsMetrics) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}
