// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/internal/utils"
)

type InputZscalerHecType string

const (
	InputZscalerHecTypeZscalerHec InputZscalerHecType = "zscaler_hec"
)

func (e InputZscalerHecType) ToPointer() *InputZscalerHecType {
	return &e
}
func (e *InputZscalerHecType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "zscaler_hec":
		*e = InputZscalerHecType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputZscalerHecType: %v", v)
	}
}

type InputZscalerHecAuthToken struct {
	// Select Manual to enter an auth token directly, or select Secret to use a text secret to authenticate
	AuthType *AuthenticationMethodOptionsAuthTokensItems `json:"authType,omitempty"`
	// Select or create a stored text secret
	TokenSecret *string `json:"tokenSecret,omitempty"`
	// Shared secret to be provided by any client (Authorization: <token>)
	Token       string  `json:"token"`
	Enabled     *bool   `json:"enabled,omitempty"`
	Description *string `json:"description,omitempty"`
	// Enter the values you want to allow in the HEC event index field at the token level. Supports wildcards. To skip validation, leave blank.
	AllowedIndexesAtToken []string `json:"allowedIndexesAtToken,omitempty"`
	// Fields to add to events referencing this token
	Metadata []ItemsTypeMetadata `json:"metadata,omitempty"`
}

func (i InputZscalerHecAuthToken) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputZscalerHecAuthToken) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputZscalerHecAuthToken) GetAuthType() *AuthenticationMethodOptionsAuthTokensItems {
	if i == nil {
		return nil
	}
	return i.AuthType
}

func (i *InputZscalerHecAuthToken) GetTokenSecret() *string {
	if i == nil {
		return nil
	}
	return i.TokenSecret
}

func (i *InputZscalerHecAuthToken) GetToken() string {
	if i == nil {
		return ""
	}
	return i.Token
}

func (i *InputZscalerHecAuthToken) GetEnabled() *bool {
	if i == nil {
		return nil
	}
	return i.Enabled
}

func (i *InputZscalerHecAuthToken) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *InputZscalerHecAuthToken) GetAllowedIndexesAtToken() []string {
	if i == nil {
		return nil
	}
	return i.AllowedIndexesAtToken
}

func (i *InputZscalerHecAuthToken) GetMetadata() []ItemsTypeMetadata {
	if i == nil {
		return nil
	}
	return i.Metadata
}

type InputZscalerHec struct {
	// Unique ID for this input
	ID       *string             `json:"id,omitempty"`
	Type     InputZscalerHecType `json:"type"`
	Disabled *bool               `json:"disabled,omitempty"`
	// Pipeline to process data from this Source before sending it through the Routes
	Pipeline *string `json:"pipeline,omitempty"`
	// Select whether to send data to Routes, or directly to Destinations.
	SendToRoutes *bool `json:"sendToRoutes,omitempty"`
	// Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
	Environment *string `json:"environment,omitempty"`
	// Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers).
	PqEnabled *bool `json:"pqEnabled,omitempty"`
	// Tags for filtering and grouping in @{product}
	Streamtags []string `json:"streamtags,omitempty"`
	// Direct connections to Destinations, and optionally via a Pipeline or a Pack
	Connections []ItemsTypeConnectionsOptional `json:"connections,omitempty"`
	Pq          *PqType                        `json:"pq,omitempty"`
	// Address to bind on. Defaults to 0.0.0.0 (all addresses).
	Host string `json:"host"`
	// Port to listen on
	Port float64 `json:"port"`
	// Shared secrets to be provided by any client (Authorization: <token>). If empty, unauthorized access is permitted.
	AuthTokens []InputZscalerHecAuthToken `json:"authTokens,omitempty"`
	TLS        *TLSSettingsServerSideType `json:"tls,omitempty"`
	// Maximum number of active requests allowed per Worker Process. Set to 0 for unlimited. Caution: Increasing the limit above the default value, or setting it to unlimited, may degrade performance and reduce throughput.
	MaxActiveReq *float64 `json:"maxActiveReq,omitempty"`
	// Maximum number of requests per socket before @{product} instructs the client to close the connection. Default is 0 (unlimited).
	MaxRequestsPerSocket *int64 `json:"maxRequestsPerSocket,omitempty"`
	// Extract the client IP and port from PROXY protocol v1/v2. When enabled, the X-Forwarded-For header is ignored. Disable to use the X-Forwarded-For header for client IP extraction.
	EnableProxyHeader *bool `json:"enableProxyHeader,omitempty"`
	// Add request headers to events, in the __headers field
	CaptureHeaders *bool `json:"captureHeaders,omitempty"`
	// How often request activity is logged at the `info` level. A value of 1 would log every request, 10 every 10th request, etc.
	ActivityLogSampleRate *float64 `json:"activityLogSampleRate,omitempty"`
	// How long to wait for an incoming request to complete before aborting it. Use 0 to disable.
	RequestTimeout *float64 `json:"requestTimeout,omitempty"`
	// How long @{product} should wait before assuming that an inactive socket has timed out. To wait forever, set to 0.
	SocketTimeout *float64 `json:"socketTimeout,omitempty"`
	// After the last response is sent, @{product} will wait this long for additional data before closing the socket connection. Minimum 1 second, maximum 600 seconds (10 minutes).
	KeepAliveTimeout *float64 `json:"keepAliveTimeout,omitempty"`
	// Messages from matched IP addresses will be processed, unless also matched by the denylist
	IPAllowlistRegex *string `json:"ipAllowlistRegex,omitempty"`
	// Messages from matched IP addresses will be ignored. This takes precedence over the allowlist.
	IPDenylistRegex *string `json:"ipDenylistRegex,omitempty"`
	// Absolute path on which to listen for the Zscaler HTTP Event Collector API requests. This input supports the /event endpoint.
	HecAPI string `json:"hecAPI"`
	// Fields to add to every event. May be overridden by fields added at the token or request level.
	Metadata []ItemsTypeMetadata `json:"metadata,omitempty"`
	// List values allowed in HEC event index field. Leave blank to skip validation. Supports wildcards. The values here can expand index validation at the token level.
	AllowedIndexes []string `json:"allowedIndexes,omitempty"`
	// Whether to enable Zscaler HEC acknowledgements
	HecAcks *bool `json:"hecAcks,omitempty"`
	// Optionally, list HTTP origins to which @{product} should send CORS (cross-origin resource sharing) Access-Control-Allow-* headers. Supports wildcards.
	AccessControlAllowOrigin []string `json:"accessControlAllowOrigin,omitempty"`
	// Optionally, list HTTP headers that @{product} will send to allowed origins as "Access-Control-Allow-Headers" in a CORS preflight response. Use "*" to allow all headers.
	AccessControlAllowHeaders []string `json:"accessControlAllowHeaders,omitempty"`
	// Enable to emit per-token (<prefix>.http.perToken) and summary (<prefix>.http.summary) request metrics
	EmitTokenMetrics *bool   `json:"emitTokenMetrics,omitempty"`
	Description      *string `json:"description,omitempty"`
	// Binds 'host' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'host' at runtime.
	TemplateHost *string `json:"__template_host,omitempty"`
	// Binds 'port' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'port' at runtime.
	TemplatePort *string `json:"__template_port,omitempty"`
	// Binds 'hecAPI' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'hecAPI' at runtime.
	TemplateHecAPI    *string `json:"__template_hecAPI,omitempty"`
	EnableHealthCheck any     `json:"enableHealthCheck,omitempty"`
}

func (i InputZscalerHec) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputZscalerHec) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InputZscalerHec) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *InputZscalerHec) GetType() InputZscalerHecType {
	if i == nil {
		return InputZscalerHecType("")
	}
	return i.Type
}

func (i *InputZscalerHec) GetDisabled() *bool {
	if i == nil {
		return nil
	}
	return i.Disabled
}

func (i *InputZscalerHec) GetPipeline() *string {
	if i == nil {
		return nil
	}
	return i.Pipeline
}

func (i *InputZscalerHec) GetSendToRoutes() *bool {
	if i == nil {
		return nil
	}
	return i.SendToRoutes
}

func (i *InputZscalerHec) GetEnvironment() *string {
	if i == nil {
		return nil
	}
	return i.Environment
}

func (i *InputZscalerHec) GetPqEnabled() *bool {
	if i == nil {
		return nil
	}
	return i.PqEnabled
}

func (i *InputZscalerHec) GetStreamtags() []string {
	if i == nil {
		return nil
	}
	return i.Streamtags
}

func (i *InputZscalerHec) GetConnections() []ItemsTypeConnectionsOptional {
	if i == nil {
		return nil
	}
	return i.Connections
}

func (i *InputZscalerHec) GetPq() *PqType {
	if i == nil {
		return nil
	}
	return i.Pq
}

func (i *InputZscalerHec) GetHost() string {
	if i == nil {
		return ""
	}
	return i.Host
}

func (i *InputZscalerHec) GetPort() float64 {
	if i == nil {
		return 0.0
	}
	return i.Port
}

func (i *InputZscalerHec) GetAuthTokens() []InputZscalerHecAuthToken {
	if i == nil {
		return nil
	}
	return i.AuthTokens
}

func (i *InputZscalerHec) GetTLS() *TLSSettingsServerSideType {
	if i == nil {
		return nil
	}
	return i.TLS
}

func (i *InputZscalerHec) GetMaxActiveReq() *float64 {
	if i == nil {
		return nil
	}
	return i.MaxActiveReq
}

func (i *InputZscalerHec) GetMaxRequestsPerSocket() *int64 {
	if i == nil {
		return nil
	}
	return i.MaxRequestsPerSocket
}

func (i *InputZscalerHec) GetEnableProxyHeader() *bool {
	if i == nil {
		return nil
	}
	return i.EnableProxyHeader
}

func (i *InputZscalerHec) GetCaptureHeaders() *bool {
	if i == nil {
		return nil
	}
	return i.CaptureHeaders
}

func (i *InputZscalerHec) GetActivityLogSampleRate() *float64 {
	if i == nil {
		return nil
	}
	return i.ActivityLogSampleRate
}

func (i *InputZscalerHec) GetRequestTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.RequestTimeout
}

func (i *InputZscalerHec) GetSocketTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.SocketTimeout
}

func (i *InputZscalerHec) GetKeepAliveTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.KeepAliveTimeout
}

func (i *InputZscalerHec) GetIPAllowlistRegex() *string {
	if i == nil {
		return nil
	}
	return i.IPAllowlistRegex
}

func (i *InputZscalerHec) GetIPDenylistRegex() *string {
	if i == nil {
		return nil
	}
	return i.IPDenylistRegex
}

func (i *InputZscalerHec) GetHecAPI() string {
	if i == nil {
		return ""
	}
	return i.HecAPI
}

func (i *InputZscalerHec) GetMetadata() []ItemsTypeMetadata {
	if i == nil {
		return nil
	}
	return i.Metadata
}

func (i *InputZscalerHec) GetAllowedIndexes() []string {
	if i == nil {
		return nil
	}
	return i.AllowedIndexes
}

func (i *InputZscalerHec) GetHecAcks() *bool {
	if i == nil {
		return nil
	}
	return i.HecAcks
}

func (i *InputZscalerHec) GetAccessControlAllowOrigin() []string {
	if i == nil {
		return nil
	}
	return i.AccessControlAllowOrigin
}

func (i *InputZscalerHec) GetAccessControlAllowHeaders() []string {
	if i == nil {
		return nil
	}
	return i.AccessControlAllowHeaders
}

func (i *InputZscalerHec) GetEmitTokenMetrics() *bool {
	if i == nil {
		return nil
	}
	return i.EmitTokenMetrics
}

func (i *InputZscalerHec) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *InputZscalerHec) GetTemplateHost() *string {
	if i == nil {
		return nil
	}
	return i.TemplateHost
}

func (i *InputZscalerHec) GetTemplatePort() *string {
	if i == nil {
		return nil
	}
	return i.TemplatePort
}

func (i *InputZscalerHec) GetTemplateHecAPI() *string {
	if i == nil {
		return nil
	}
	return i.TemplateHecAPI
}

func (i *InputZscalerHec) GetEnableHealthCheck() any {
	if i == nil {
		return nil
	}
	return i.EnableHealthCheck
}
