// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type InputElementType string

const (
	InputElementTypeInputTimerange InputElementType = "input.timerange"
	InputElementTypeInputDropdown  InputElementType = "input.dropdown"
	InputElementTypeInputText      InputElementType = "input.text"
	InputElementTypeInputNumber    InputElementType = "input.number"
)

func (e InputElementType) ToPointer() *InputElementType {
	return &e
}
func (e *InputElementType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "input.timerange":
		fallthrough
	case "input.dropdown":
		fallthrough
	case "input.text":
		fallthrough
	case "input.number":
		*e = InputElementType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputElementType: %v", v)
	}
}
