// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/internal/utils"
)

type InputMicrosoftGraphType string

const (
	InputMicrosoftGraphTypeMicrosoftGraph InputMicrosoftGraphType = "microsoft_graph"
)

func (e InputMicrosoftGraphType) ToPointer() *InputMicrosoftGraphType {
	return &e
}
func (e *InputMicrosoftGraphType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "microsoft_graph":
		*e = InputMicrosoftGraphType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputMicrosoftGraphType: %v", v)
	}
}

type InputMicrosoftGraph struct {
	// Unique ID for this input
	ID       *string                 `json:"id,omitempty"`
	Type     InputMicrosoftGraphType `json:"type"`
	Disabled *bool                   `json:"disabled,omitempty"`
	// Pipeline to process data from this Source before sending it through the Routes
	Pipeline *string `json:"pipeline,omitempty"`
	// Select whether to send data to Routes, or directly to Destinations.
	SendToRoutes *bool `json:"sendToRoutes,omitempty"`
	// Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
	Environment *string `json:"environment,omitempty"`
	// Use a disk queue to minimize data loss when connected services block. See [Cribl Docs](https://docs.cribl.io/stream/persistent-queues) for PQ defaults (Cribl-managed Cloud Workers) and configuration options (on-prem and hybrid Workers).
	PqEnabled *bool `json:"pqEnabled,omitempty"`
	// Tags for filtering and grouping in @{product}
	Streamtags []string `json:"streamtags,omitempty"`
	// Direct connections to Destinations, and optionally via a Pipeline or a Pack
	Connections []ItemsTypeConnectionsOptional `json:"connections,omitempty"`
	Pq          *PqType                        `json:"pq,omitempty"`
	// Microsoft Graph API endpoint URL. (ex. https://graph.microsoft.com/v1.0/admin/exchange/tracing/messageTraces)
	URL string `json:"url"`
	// How often (in minutes) to run the report. Must divide evenly into 60 minutes to create a predictable schedule, or Save will fail.
	Interval int64 `json:"interval"`
	// Backward offset for the search range's head. (E.g.: -3h@h) Microsoft Graph data is delayed; this parameter (with Date range end) compensates for delay and gaps.
	StartDate *string `json:"startDate,omitempty"`
	// Backward offset for the search range's tail. (E.g.: -2h@h) Microsoft Graph data is delayed; this parameter (with Date range start) compensates for delay and gaps.
	EndDate *string `json:"endDate,omitempty"`
	// HTTP request inactivity timeout. Maximum is 2400 (40 minutes); enter 0 to wait indefinitely.
	Timeout *float64 `json:"timeout,omitempty"`
	// Disables time filtering of events when a date range is specified.
	DisableTimeFilter *bool `json:"disableTimeFilter,omitempty"`
	// Select authentication method.
	AuthType *AuthenticationMethodOptionsManualOauth `json:"authType,omitempty"`
	// How often workers should check in with the scheduler to keep job subscription alive
	KeepAliveTime *float64 `json:"keepAliveTime,omitempty"`
	// Maximum time the job is allowed to run. Time unit defaults to seconds if not specified (examples: 30, 45s, 15m). Enter 0 for unlimited time.
	JobTimeout *string `json:"jobTimeout,omitempty"`
	// The number of Keep Alive Time periods before an inactive worker will have its job subscription revoked.
	MaxMissedKeepAlives *float64 `json:"maxMissedKeepAlives,omitempty"`
	// Time to keep the job's artifacts on disk after job completion. This also affects how long a job is listed in the Job Inspector.
	TTL *string `json:"ttl,omitempty"`
	// When enabled, this job's artifacts are not counted toward the Worker Group's finished job artifacts limit. Artifacts will be removed only after the Collector's configured time to live.
	IgnoreGroupJobsLimit *bool `json:"ignoreGroupJobsLimit,omitempty"`
	// Fields to add to events from this input
	Metadata []ItemsTypeMetadata `json:"metadata,omitempty"`
	// Reschedule tasks that failed with non-fatal errors
	RescheduleDroppedTasks *bool `json:"rescheduleDroppedTasks,omitempty"`
	// Maximum number of times a task can be rescheduled
	MaxTaskReschedule *float64 `json:"maxTaskReschedule,omitempty"`
	// Log Level (verbosity) for collection runtime behavior.
	LogLevel    *LogLevelOptions                 `json:"logLevel,omitempty"`
	RetryRules  *RetryRulesTypeCodesEnableHeader `json:"retryRules,omitempty"`
	Description *string                          `json:"description,omitempty"`
	// Username to run Microsoft Graph API call.
	Username *string `json:"username,omitempty"`
	// Password to run Microsoft Graph API call.
	Password *string `json:"password,omitempty"`
	// Select or create a secret that references your credentials.
	CredentialsSecret *string `json:"credentialsSecret,omitempty"`
	// client_secret to pass in the OAuth request parameter.
	ClientSecret *string `json:"clientSecret,omitempty"`
	// Directory ID (tenant identifier) in Azure Active Directory.
	TenantID *string `json:"tenantId,omitempty"`
	// client_id to pass in the OAuth request parameter.
	ClientID *string `json:"clientId,omitempty"`
	// Resource to pass in the OAuth request parameter.
	Resource *string `json:"resource,omitempty"`
	// Office 365 subscription plan for your organization, typically Office 365 Enterprise
	PlanType *SubscriptionPlanOptions `json:"planType,omitempty"`
	// Select or create a secret that references your client_secret to pass in the OAuth request parameter.
	TextSecret  *string          `json:"textSecret,omitempty"`
	CertOptions *CertOptionsType `json:"certOptions,omitempty"`
	// Binds 'url' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'url' at runtime.
	TemplateURL *string `json:"__template_url,omitempty"`
	// Binds 'tenantId' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'tenantId' at runtime.
	TemplateTenantID *string `json:"__template_tenantId,omitempty"`
	// Binds 'clientId' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'clientId' at runtime.
	TemplateClientID *string `json:"__template_clientId,omitempty"`
	// Binds 'resource' to a variable for dynamic value resolution. Set to variable ID (pack-scoped) or 'cribl.'/'edge.' prefixed ID (group-scoped). Variable value overrides 'resource' at runtime.
	TemplateResource *string `json:"__template_resource,omitempty"`
}

func (i InputMicrosoftGraph) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InputMicrosoftGraph) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"type", "url", "interval"}); err != nil {
		return err
	}
	return nil
}

func (i *InputMicrosoftGraph) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *InputMicrosoftGraph) GetType() InputMicrosoftGraphType {
	if i == nil {
		return InputMicrosoftGraphType("")
	}
	return i.Type
}

func (i *InputMicrosoftGraph) GetDisabled() *bool {
	if i == nil {
		return nil
	}
	return i.Disabled
}

func (i *InputMicrosoftGraph) GetPipeline() *string {
	if i == nil {
		return nil
	}
	return i.Pipeline
}

func (i *InputMicrosoftGraph) GetSendToRoutes() *bool {
	if i == nil {
		return nil
	}
	return i.SendToRoutes
}

func (i *InputMicrosoftGraph) GetEnvironment() *string {
	if i == nil {
		return nil
	}
	return i.Environment
}

func (i *InputMicrosoftGraph) GetPqEnabled() *bool {
	if i == nil {
		return nil
	}
	return i.PqEnabled
}

func (i *InputMicrosoftGraph) GetStreamtags() []string {
	if i == nil {
		return nil
	}
	return i.Streamtags
}

func (i *InputMicrosoftGraph) GetConnections() []ItemsTypeConnectionsOptional {
	if i == nil {
		return nil
	}
	return i.Connections
}

func (i *InputMicrosoftGraph) GetPq() *PqType {
	if i == nil {
		return nil
	}
	return i.Pq
}

func (i *InputMicrosoftGraph) GetURL() string {
	if i == nil {
		return ""
	}
	return i.URL
}

func (i *InputMicrosoftGraph) GetInterval() int64 {
	if i == nil {
		return 0
	}
	return i.Interval
}

func (i *InputMicrosoftGraph) GetStartDate() *string {
	if i == nil {
		return nil
	}
	return i.StartDate
}

func (i *InputMicrosoftGraph) GetEndDate() *string {
	if i == nil {
		return nil
	}
	return i.EndDate
}

func (i *InputMicrosoftGraph) GetTimeout() *float64 {
	if i == nil {
		return nil
	}
	return i.Timeout
}

func (i *InputMicrosoftGraph) GetDisableTimeFilter() *bool {
	if i == nil {
		return nil
	}
	return i.DisableTimeFilter
}

func (i *InputMicrosoftGraph) GetAuthType() *AuthenticationMethodOptionsManualOauth {
	if i == nil {
		return nil
	}
	return i.AuthType
}

func (i *InputMicrosoftGraph) GetKeepAliveTime() *float64 {
	if i == nil {
		return nil
	}
	return i.KeepAliveTime
}

func (i *InputMicrosoftGraph) GetJobTimeout() *string {
	if i == nil {
		return nil
	}
	return i.JobTimeout
}

func (i *InputMicrosoftGraph) GetMaxMissedKeepAlives() *float64 {
	if i == nil {
		return nil
	}
	return i.MaxMissedKeepAlives
}

func (i *InputMicrosoftGraph) GetTTL() *string {
	if i == nil {
		return nil
	}
	return i.TTL
}

func (i *InputMicrosoftGraph) GetIgnoreGroupJobsLimit() *bool {
	if i == nil {
		return nil
	}
	return i.IgnoreGroupJobsLimit
}

func (i *InputMicrosoftGraph) GetMetadata() []ItemsTypeMetadata {
	if i == nil {
		return nil
	}
	return i.Metadata
}

func (i *InputMicrosoftGraph) GetRescheduleDroppedTasks() *bool {
	if i == nil {
		return nil
	}
	return i.RescheduleDroppedTasks
}

func (i *InputMicrosoftGraph) GetMaxTaskReschedule() *float64 {
	if i == nil {
		return nil
	}
	return i.MaxTaskReschedule
}

func (i *InputMicrosoftGraph) GetLogLevel() *LogLevelOptions {
	if i == nil {
		return nil
	}
	return i.LogLevel
}

func (i *InputMicrosoftGraph) GetRetryRules() *RetryRulesTypeCodesEnableHeader {
	if i == nil {
		return nil
	}
	return i.RetryRules
}

func (i *InputMicrosoftGraph) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}

func (i *InputMicrosoftGraph) GetUsername() *string {
	if i == nil {
		return nil
	}
	return i.Username
}

func (i *InputMicrosoftGraph) GetPassword() *string {
	if i == nil {
		return nil
	}
	return i.Password
}

func (i *InputMicrosoftGraph) GetCredentialsSecret() *string {
	if i == nil {
		return nil
	}
	return i.CredentialsSecret
}

func (i *InputMicrosoftGraph) GetClientSecret() *string {
	if i == nil {
		return nil
	}
	return i.ClientSecret
}

func (i *InputMicrosoftGraph) GetTenantID() *string {
	if i == nil {
		return nil
	}
	return i.TenantID
}

func (i *InputMicrosoftGraph) GetClientID() *string {
	if i == nil {
		return nil
	}
	return i.ClientID
}

func (i *InputMicrosoftGraph) GetResource() *string {
	if i == nil {
		return nil
	}
	return i.Resource
}

func (i *InputMicrosoftGraph) GetPlanType() *SubscriptionPlanOptions {
	if i == nil {
		return nil
	}
	return i.PlanType
}

func (i *InputMicrosoftGraph) GetTextSecret() *string {
	if i == nil {
		return nil
	}
	return i.TextSecret
}

func (i *InputMicrosoftGraph) GetCertOptions() *CertOptionsType {
	if i == nil {
		return nil
	}
	return i.CertOptions
}

func (i *InputMicrosoftGraph) GetTemplateURL() *string {
	if i == nil {
		return nil
	}
	return i.TemplateURL
}

func (i *InputMicrosoftGraph) GetTemplateTenantID() *string {
	if i == nil {
		return nil
	}
	return i.TemplateTenantID
}

func (i *InputMicrosoftGraph) GetTemplateClientID() *string {
	if i == nil {
		return nil
	}
	return i.TemplateClientID
}

func (i *InputMicrosoftGraph) GetTemplateResource() *string {
	if i == nil {
		return nil
	}
	return i.TemplateResource
}
