// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/internal/utils"
)

type ItemsTypeAuthTokens struct {
	// Select or create a stored text secret
	TokenSecret string `json:"tokenSecret"`
	Enabled     *bool  `json:"enabled,omitempty"`
	// Optional token description
	Description *string `json:"description,omitempty"`
}

func (i ItemsTypeAuthTokens) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *ItemsTypeAuthTokens) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"tokenSecret"}); err != nil {
		return err
	}
	return nil
}

func (i *ItemsTypeAuthTokens) GetTokenSecret() string {
	if i == nil {
		return ""
	}
	return i.TokenSecret
}

func (i *ItemsTypeAuthTokens) GetEnabled() *bool {
	if i == nil {
		return nil
	}
	return i.Enabled
}

func (i *ItemsTypeAuthTokens) GetDescription() *string {
	if i == nil {
		return nil
	}
	return i.Description
}
