// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ContentFormat - Content format for delivered events.
type ContentFormat string

const (
	ContentFormatRaw          ContentFormat = "Raw"
	ContentFormatRenderedText ContentFormat = "RenderedText"
)

func (e ContentFormat) ToPointer() *ContentFormat {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ContentFormat) IsExact() bool {
	if e != nil {
		switch *e {
		case "Raw", "RenderedText":
			return true
		}
	}
	return false
}

// QuerySelector - Query builder mode; simple with queries, or xml with xmlQuery.
type QuerySelector string

const (
	QuerySelectorSimple QuerySelector = "simple"
	QuerySelectorXML    QuerySelector = "xml"
)

func (e QuerySelector) ToPointer() *QuerySelector {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *QuerySelector) IsExact() bool {
	if e != nil {
		switch *e {
		case "simple", "xml":
			return true
		}
	}
	return false
}

type LocalSearchSourceWefSubscriptionItemQuery struct {
	// Path attribute from the relevant XML Select element.
	Path string `json:"path"`
	// XPath query inside the relevant XML Select element.
	QueryExpression string `json:"queryExpression"`
}

func (l *LocalSearchSourceWefSubscriptionItemQuery) GetPath() string {
	if l == nil {
		return ""
	}
	return l.Path
}

func (l *LocalSearchSourceWefSubscriptionItemQuery) GetQueryExpression() string {
	if l == nil {
		return ""
	}
	return l.QueryExpression
}

// LocalSearchSourceWefSubscriptionItem - WEF subscription entry for Local Search when type is wef. Aligns with Stream InputWef subscription fields. Use querySelector simple with queries, or xml with xmlQuery.
type LocalSearchSourceWefSubscriptionItem struct {
	// Subscription name exposed to Windows clients.
	SubscriptionName string `json:"subscriptionName"`
	// Version UUID for this subscription; changes when subscription parameters change.
	Version *string `json:"version,omitempty"`
	// Content format for delivered events.
	ContentFormat ContentFormat `json:"contentFormat"`
	// Maximum seconds between endpoint check-ins before marking unavailable.
	HeartbeatInterval float64 `json:"heartbeatInterval"`
	// Seconds to collect events before sending to Cribl.
	BatchTimeout float64 `json:"batchTimeout"`
	// Send previously existing events for new subscriptions.
	ReadExistingEvents *bool `json:"readExistingEvents,omitempty"`
	// Track received events for resume after re-subscription.
	SendBookmarks *bool `json:"sendBookmarks,omitempty"`
	// Receive compressed events from the source.
	Compress *bool `json:"compress,omitempty"`
	// DNS names of endpoints that forward these events (wildcards allowed).
	Targets []string `json:"targets"`
	// RFC 3066 locale for Windows clients (e.g. en-US).
	Locale   *string             `json:"locale,omitempty"`
	Metadata []ItemsTypeMetadata `json:"metadata,omitempty"`
	ID       *string             `json:"id,omitempty"`
	// Query builder mode; simple with queries, or xml with xmlQuery.
	QuerySelector *QuerySelector `json:"querySelector,omitempty"`
	// Path and XPath selector entries when using simple mode.
	Queries []LocalSearchSourceWefSubscriptionItemQuery `json:"queries,omitempty"`
	// XPath query when using xml mode.
	XMLQuery *string `json:"xmlQuery,omitempty"`
}

func (l *LocalSearchSourceWefSubscriptionItem) GetSubscriptionName() string {
	if l == nil {
		return ""
	}
	return l.SubscriptionName
}

func (l *LocalSearchSourceWefSubscriptionItem) GetVersion() *string {
	if l == nil {
		return nil
	}
	return l.Version
}

func (l *LocalSearchSourceWefSubscriptionItem) GetContentFormat() ContentFormat {
	if l == nil {
		return ContentFormat("")
	}
	return l.ContentFormat
}

func (l *LocalSearchSourceWefSubscriptionItem) GetHeartbeatInterval() float64 {
	if l == nil {
		return 0.0
	}
	return l.HeartbeatInterval
}

func (l *LocalSearchSourceWefSubscriptionItem) GetBatchTimeout() float64 {
	if l == nil {
		return 0.0
	}
	return l.BatchTimeout
}

func (l *LocalSearchSourceWefSubscriptionItem) GetReadExistingEvents() *bool {
	if l == nil {
		return nil
	}
	return l.ReadExistingEvents
}

func (l *LocalSearchSourceWefSubscriptionItem) GetSendBookmarks() *bool {
	if l == nil {
		return nil
	}
	return l.SendBookmarks
}

func (l *LocalSearchSourceWefSubscriptionItem) GetCompress() *bool {
	if l == nil {
		return nil
	}
	return l.Compress
}

func (l *LocalSearchSourceWefSubscriptionItem) GetTargets() []string {
	if l == nil {
		return []string{}
	}
	return l.Targets
}

func (l *LocalSearchSourceWefSubscriptionItem) GetLocale() *string {
	if l == nil {
		return nil
	}
	return l.Locale
}

func (l *LocalSearchSourceWefSubscriptionItem) GetMetadata() []ItemsTypeMetadata {
	if l == nil {
		return nil
	}
	return l.Metadata
}

func (l *LocalSearchSourceWefSubscriptionItem) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *LocalSearchSourceWefSubscriptionItem) GetQuerySelector() *QuerySelector {
	if l == nil {
		return nil
	}
	return l.QuerySelector
}

func (l *LocalSearchSourceWefSubscriptionItem) GetQueries() []LocalSearchSourceWefSubscriptionItemQuery {
	if l == nil {
		return nil
	}
	return l.Queries
}

func (l *LocalSearchSourceWefSubscriptionItem) GetXMLQuery() *string {
	if l == nil {
		return nil
	}
	return l.XMLQuery
}
