// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// LogLevelOptions - Log Level (verbosity) for collection runtime behavior.
type LogLevelOptions string

const (
	LogLevelOptionsError LogLevelOptions = "error"
	LogLevelOptionsWarn  LogLevelOptions = "warn"
	LogLevelOptionsInfo  LogLevelOptions = "info"
	LogLevelOptionsDebug LogLevelOptions = "debug"
	LogLevelOptionsSilly LogLevelOptions = "silly"
)

func (e LogLevelOptions) ToPointer() *LogLevelOptions {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *LogLevelOptions) IsExact() bool {
	if e != nil {
		switch *e {
		case "error", "warn", "info", "debug", "silly":
			return true
		}
	}
	return false
}
