// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ObjectACLOptions - Object ACL to assign to uploaded objects
type ObjectACLOptions string

const (
	// ObjectACLOptionsPrivate Private
	ObjectACLOptionsPrivate ObjectACLOptions = "private"
	// ObjectACLOptionsPublicRead Public Read Only
	ObjectACLOptionsPublicRead ObjectACLOptions = "public-read"
	// ObjectACLOptionsPublicReadWrite Public Read/Write
	ObjectACLOptionsPublicReadWrite ObjectACLOptions = "public-read-write"
	// ObjectACLOptionsAuthenticatedRead Authenticated Read Only
	ObjectACLOptionsAuthenticatedRead ObjectACLOptions = "authenticated-read"
	// ObjectACLOptionsAwsExecRead AWS EC2 AMI Read Only
	ObjectACLOptionsAwsExecRead ObjectACLOptions = "aws-exec-read"
	// ObjectACLOptionsBucketOwnerRead Bucket Owner Read Only
	ObjectACLOptionsBucketOwnerRead ObjectACLOptions = "bucket-owner-read"
	// ObjectACLOptionsBucketOwnerFullControl Bucket Owner Full Control
	ObjectACLOptionsBucketOwnerFullControl ObjectACLOptions = "bucket-owner-full-control"
)

func (e ObjectACLOptions) ToPointer() *ObjectACLOptions {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ObjectACLOptions) IsExact() bool {
	if e != nil {
		switch *e {
		case "private", "public-read", "public-read-write", "authenticated-read", "aws-exec-read", "bucket-owner-read", "bucket-owner-full-control":
			return true
		}
	}
	return false
}
