// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// OutputModeOptionsSplunkCollectorConf - Format of the returned output
type OutputModeOptionsSplunkCollectorConf string

const (
	OutputModeOptionsSplunkCollectorConfCsv  OutputModeOptionsSplunkCollectorConf = "csv"
	OutputModeOptionsSplunkCollectorConfJSON OutputModeOptionsSplunkCollectorConf = "json"
)

func (e OutputModeOptionsSplunkCollectorConf) ToPointer() *OutputModeOptionsSplunkCollectorConf {
	return &e
}
func (e *OutputModeOptionsSplunkCollectorConf) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "csv":
		fallthrough
	case "json":
		*e = OutputModeOptionsSplunkCollectorConf(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OutputModeOptionsSplunkCollectorConf: %v", v)
	}
}
