// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ParquetVersionOptions - Determines which data types are supported and how they are represented
type ParquetVersionOptions string

const (
	// ParquetVersionOptionsParquet10 1.0
	ParquetVersionOptionsParquet10 ParquetVersionOptions = "PARQUET_1_0"
	// ParquetVersionOptionsParquet24 2.4
	ParquetVersionOptionsParquet24 ParquetVersionOptions = "PARQUET_2_4"
	// ParquetVersionOptionsParquet26 2.6
	ParquetVersionOptionsParquet26 ParquetVersionOptions = "PARQUET_2_6"
)

func (e ParquetVersionOptions) ToPointer() *ParquetVersionOptions {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ParquetVersionOptions) IsExact() bool {
	if e != nil {
		switch *e {
		case "PARQUET_1_0", "PARQUET_2_4", "PARQUET_2_6":
			return true
		}
	}
	return false
}
