// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/criblio/terraform-provider-criblio/internal/sdk/internal/utils"
)

type PqTypePqControls struct {
}

func (p PqTypePqControls) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PqTypePqControls) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

type PqType struct {
	// With Smart mode, PQ will write events to the filesystem only when it detects backpressure from the processing engine. With Always On mode, PQ will always write events directly to the queue before forwarding them to the processing engine.
	Mode *ModeOptionsPq `json:"mode,omitempty"`
	// The maximum size to hold in memory before writing events to disk. Enter a numeral with units of KB, MB, etc. The minimum value is 64KB and the maximum value is 1MB.
	MaxBufferSizeBytes *string `json:"maxBufferSizeBytes,omitempty"`
	// Maximum number of events to hold in memory before writing the events to disk. Deprecated and only supported in workers < v4.17.0. Use maxBufferSizeBytes instead.
	MaxBufferSize *float64 `json:"maxBufferSize,omitempty"`
	// The number of events to send downstream before committing that Stream has read them
	CommitFrequency *float64 `json:"commitFrequency,omitempty"`
	// The maximum size to store in each queue file before closing and optionally compressing. Enter a numeral with units of KB, MB, etc.
	MaxFileSize *string `json:"maxFileSize,omitempty"`
	// The maximum disk space that the queue can consume (as an average per Worker Process) before queueing stops. Enter a numeral with units of KB, MB, etc.
	MaxSize *string `json:"maxSize,omitempty"`
	// The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/inputs/<input-id>
	Path *string `json:"path,omitempty"`
	// Codec to use to compress the persisted data
	Compress   *CompressionOptionsPq `json:"compress,omitempty"`
	PqControls *PqTypePqControls     `json:"pqControls,omitempty"`
}

func (p PqType) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PqType) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PqType) GetMode() *ModeOptionsPq {
	if p == nil {
		return nil
	}
	return p.Mode
}

func (p *PqType) GetMaxBufferSizeBytes() *string {
	if p == nil {
		return nil
	}
	return p.MaxBufferSizeBytes
}

func (p *PqType) GetMaxBufferSize() *float64 {
	if p == nil {
		return nil
	}
	return p.MaxBufferSize
}

func (p *PqType) GetCommitFrequency() *float64 {
	if p == nil {
		return nil
	}
	return p.CommitFrequency
}

func (p *PqType) GetMaxFileSize() *string {
	if p == nil {
		return nil
	}
	return p.MaxFileSize
}

func (p *PqType) GetMaxSize() *string {
	if p == nil {
		return nil
	}
	return p.MaxSize
}

func (p *PqType) GetPath() *string {
	if p == nil {
		return nil
	}
	return p.Path
}

func (p *PqType) GetCompress() *CompressionOptionsPq {
	if p == nil {
		return nil
	}
	return p.Compress
}

func (p *PqType) GetPqControls() *PqTypePqControls {
	if p == nil {
		return nil
	}
	return p.PqControls
}
