// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// QueueFullBehaviorOptions - How to handle events when the queue is exerting backpressure (full capacity or low disk). 'Block' is the same behavior as non-PQ blocking. 'Drop new data' throws away incoming data, while leaving the contents of the PQ unchanged.
type QueueFullBehaviorOptions string

const (
	// QueueFullBehaviorOptionsBlock Block
	QueueFullBehaviorOptionsBlock QueueFullBehaviorOptions = "block"
	// QueueFullBehaviorOptionsDrop Drop new data
	QueueFullBehaviorOptionsDrop QueueFullBehaviorOptions = "drop"
)

func (e QueueFullBehaviorOptions) ToPointer() *QueueFullBehaviorOptions {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *QueueFullBehaviorOptions) IsExact() bool {
	if e != nil {
		switch *e {
		case "block", "drop":
			return true
		}
	}
	return false
}
