// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// SignatureVersionOptionsV2V4 - Signature version to use for signing EC2 requests
type SignatureVersionOptionsV2V4 string

const (
	SignatureVersionOptionsV2V4V2 SignatureVersionOptionsV2V4 = "v2"
	SignatureVersionOptionsV2V4V4 SignatureVersionOptionsV2V4 = "v4"
)

func (e SignatureVersionOptionsV2V4) ToPointer() *SignatureVersionOptionsV2V4 {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SignatureVersionOptionsV2V4) IsExact() bool {
	if e != nil {
		switch *e {
		case "v2", "v4":
			return true
		}
	}
	return false
}
