package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/criblio/terraform-provider-criblio/internal/sdk"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/operations"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"github.com/criblio/terraform-provider-criblio/tools/criblio-import/internal/terraform"
	"strings"
)

func main() {
	ctx := context.Background()

	fmt.Println("🔐 Initializing SDK client (authentication handled automatically)...")
	client := sdk.New()

	// Step 1: Fetch and generate groups (same as before)
	fmt.Println("📥 Fetching groups from Cribl...")

	type GroupWithProduct struct {
		Group   shared.Group
		Product string
	}

	groups := []GroupWithProduct{}

	products := []operations.GetProductsGroupsByProductProduct{
		operations.GetProductsGroupsByProductProductStream,
		operations.GetProductsGroupsByProductProductEdge,
	}

	for _, product := range products {
		productStr := string(product)
		fmt.Printf("  Fetching groups for product: %s\n", productStr)
		request := operations.GetProductsGroupsByProductRequest{
			Product: product,
		}

		res, err := client.Groups.GetProductsGroupsByProduct(ctx, request)
		if err != nil {
			log.Printf("⚠️  Warning: Failed to fetch groups for product %s: %v", productStr, err)
			continue
		}

		if res.StatusCode != 200 || res.Object == nil {
			log.Printf("⚠️  Warning: Unexpected response for product %s: status %d", productStr, res.StatusCode)
			continue
		}

		for _, group := range res.Object.Items {
			if group.ID != "" {
				groups = append(groups, GroupWithProduct{
					Group:   group,
					Product: productStr,
				})
			}
		}
	}

	fmt.Printf("\n✅ Found %d groups\n\n", len(groups))

	// Step 2: Generate Terraform resources
	fmt.Println("📝 Generating Terraform resources...")

	var terraformResources strings.Builder
	terraformResources.WriteString("# Generated by criblio-import tool\n")
	terraformResources.WriteString("# Groups exported from Cribl\n\n")

	// Track import specs for auto-import
	importSpecs := []terraform.ImportSpec{}

	for _, groupWithProduct := range groups {
		group := groupWithProduct.Group
		resourceName := normalizeResourceName(group.ID)
		terraformResources.WriteString(fmt.Sprintf("resource \"criblio_group\" \"%s\" {\n", resourceName))
		terraformResources.WriteString(fmt.Sprintf("  id = %q\n", group.ID))
		terraformResources.WriteString(fmt.Sprintf("  product = %q\n", groupWithProduct.Product))

		if group.Name != nil && *group.Name != "" {
			terraformResources.WriteString(fmt.Sprintf("  name = %q\n", *group.Name))
		}

		if group.OnPrem != nil {
			terraformResources.WriteString(fmt.Sprintf("  on_prem = %v\n", *group.OnPrem))
		}

		if group.Provisioned {
			terraformResources.WriteString("  provisioned = true\n")
		}

		if group.IsFleet != nil {
			terraformResources.WriteString(fmt.Sprintf("  is_fleet = %v\n", *group.IsFleet))
		}

		if group.WorkerRemoteAccess != nil {
			terraformResources.WriteString(fmt.Sprintf("  worker_remote_access = %v\n", *group.WorkerRemoteAccess))
		}

		if len(group.Streamtags) > 0 {
			terraformResources.WriteString("  streamtags = [\n")
			for _, tag := range group.Streamtags {
				terraformResources.WriteString(fmt.Sprintf("    %q,\n", tag))
			}
			terraformResources.WriteString("  ]\n")
		}

		if group.Cloud != nil {
			terraformResources.WriteString("  cloud {\n")
			terraformResources.WriteString(fmt.Sprintf("    provider = %q\n", group.Cloud.Provider))
			terraformResources.WriteString(fmt.Sprintf("    region   = %q\n", group.Cloud.Region))
			terraformResources.WriteString("  }\n")
		}

		terraformResources.WriteString("}\n\n")

		// Add to import specs
		importSpecs = append(importSpecs, terraform.ImportSpec{
			ResourceType: "criblio_group",
			ResourceName: resourceName,
			ImportID:     group.ID,
		})
	}

	// Write to file
	outputFile := "groups.tf"
	err := os.WriteFile(outputFile, []byte(terraformResources.String()), 0644)
	if err != nil {
		log.Fatalf("❌ Failed to write Terraform file: %v", err)
	}

	fmt.Printf("✅ Generated Terraform file: %s\n", outputFile)
	fmt.Printf("📊 Summary: %d groups exported\n", len(groups))

	// Step 3: Auto-import if requested (via flag or environment)
	autoImport := os.Getenv("AUTO_IMPORT") == "true" || len(os.Args) > 1 && os.Args[1] == "--auto-import"

	if autoImport {
		fmt.Println("\n🔄 Auto-importing resources into Terraform state...")

		// Create provider.tf if it doesn't exist
		if _, err := os.Stat("provider.tf"); os.IsNotExist(err) {
			providerConfig := `terraform {
  required_providers {
    criblio = {
      source  = "criblio/criblio"
    }
  }
}

provider "criblio" {
  # Authentication via environment variables or ~/.cribl/credentials
}
`
			os.WriteFile("provider.tf", []byte(providerConfig), 0644)
			fmt.Println("  ✓ Created provider.tf")
		}

		// Initialize Terraform importer
		importer, err := terraform.NewImporter(".")
		if err != nil {
			log.Fatalf("❌ Failed to create Terraform importer: %v", err)
		}

		// Initialize Terraform
		if err := importer.Init(ctx); err != nil {
			log.Fatalf("❌ Failed to initialize Terraform: %v", err)
		}

		// Import all resources
		if err := importer.ImportMultipleResources(ctx, importSpecs); err != nil {
			log.Printf("⚠️  Some imports failed: %v", err)
		}

		// Validate configuration
		if err := importer.Validate(ctx); err != nil {
			log.Printf("⚠️  Validation warning: %v", err)
		}

		// Show plan
		fmt.Println("")
		if err := importer.Plan(ctx); err != nil {
			log.Printf("⚠️  Plan warning: %v", err)
		}

		fmt.Println("\n💡 Next steps:")
		fmt.Println("   1. Review the plan output above")
		fmt.Println("   2. Run: terraform apply")
	} else {
		fmt.Println("\n💡 Next steps:")
		fmt.Println("   1. Review the generated groups.tf file")
		fmt.Println("   2. Run: terraform init")
		fmt.Println("   3. Run: terraform import (or use --auto-import flag)")
		fmt.Println("   4. Run: terraform plan")
		fmt.Println("   5. Run: terraform apply")
	}
}

func normalizeResourceName(name string) string {
	name = strings.ReplaceAll(name, "-", "_")
	name = strings.ReplaceAll(name, ".", "_")
	name = strings.ReplaceAll(name, " ", "_")

	if len(name) > 0 && !isLetter(rune(name[0])) {
		name = "r_" + name
	}

	return name
}

func isLetter(r rune) bool {
	return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
}

