# Generated by criblio-import tool
# Global variables exported from Cribl
# Minimal config - only required fields (id, group_id)
# After import, run: terraform plan -generate-config-out=complete.tf

resource "criblio_global_var" "unixtime" {
  id       = "unixtime"
  group_id = "default"
  type     = "expression" # Default value to match state
}

resource "criblio_global_var" "datetime" {
  id       = "datetime"
  group_id = "default"
  type     = "expression" # Default value to match state
}

resource "criblio_global_var" "theAnswer" {
  id       = "theAnswer"
  group_id = "default"
  type     = "number" # Default value to match state
}

resource "criblio_global_var" "myObject" {
  id       = "myObject"
  group_id = "default"
  type     = "object" # Default value to match state
}

resource "criblio_global_var" "myArray" {
  id       = "myArray"
  group_id = "default"
  type     = "array" # Default value to match state
}

resource "criblio_global_var" "convertBytes" {
  id       = "convertBytes"
  group_id = "default"
  type     = "expression" # Default value to match state
}

resource "criblio_global_var" "my_globalvar" {
  id       = "my_globalvar"
  group_id = "default"
  type     = "number" # Default value to match state
}

resource "criblio_global_var" "test_demo_var" {
  id       = "test_demo_var"
  group_id = "default"
  type     = "number" # Default value to match state
}

resource "criblio_global_var" "test_demo_var_2" {
  id       = "test_demo_var_2"
  group_id = "default"
  type     = "number" # Default value to match state
}

