// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
	custom_stringplanmodifier "github.com/criblio/terraform-provider-criblio/internal/tfplanmodifiers/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

var _ = jsontypes.NormalizedType{}
var _ = types.String{}

var _ resource.Resource = &AppResource{}
var _ resource.ResourceWithConfigure = &AppResource{}
var _ resource.ResourceWithImportState = &AppResource{}

type AppResource struct {
	client *restclient.Client
	api    AppAPI
}

func NewAppResource() resource.Resource {
	return &AppResource{}
}

func (r *AppResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_app"
}

func (r *AppResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "App Resource",
		Attributes: map[string]schema.Attribute{
			"author": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: `Author of the app.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"cribl": schema.SingleNestedAttribute{
				Required: false,
				Optional: true,
				Computed: true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.RequiresReplace(),
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"type": schema.StringAttribute{
						Required:    false,
						Optional:    true,
						Computed:    false,
						Description: `Cribl package type. Always "app" for apps.`,
					},
					"create_app_script_version": schema.StringAttribute{
						Required:    false,
						Optional:    true,
						Computed:    false,
						Description: `Version of the create-app scaffold that generated this app.`,
					},
					"hidden": schema.BoolAttribute{
						Required:    false,
						Optional:    true,
						Computed:    false,
						Description: `When <code>true</code>, the app is installed but hidden from the Apps list UI.`,
					},
				},
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: `Brief description of the app.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"display_name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: `Human-readable display name for the app.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"filename": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    false,
				Description: `Local App archive to upload before installation. Apps are supported only in Cribl.Cloud.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("source")),
				},
			},
			"force": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Computed:    false,
				Description: `If <code>true</code>, overwrite any existing App that has the same <code>id</code>. If <code>false</code>, and an App with the same <code>id</code> already exists, the request fails.`,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.RequiresReplace(),
				},
			},
			"id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Unique identifier for the App. When provided with <code>source</code>, overrides the <code>id</code> that is listed in the package.json for the App.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					custom_stringplanmodifier.SuppressDiff(custom_stringplanmodifier.ExplicitSuppress),
				},
			},
			"min_log_stream_version": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: `Minimum Cribl Stream version required by this app.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"source": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: `The source of the app: a URL, uploaded filename, or git+ URL. If omitted, the provider generates and uploads a minimal App scaffold. Apps are supported only in Cribl.Cloud.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"spec": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: `Schema spec version for the app.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"version": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: `Semantic version of the app.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *AppResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clients, ok := req.ProviderData.(*ProviderClients)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *ProviderClients, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = clients.RC
	r.api = newAppAPI(r.client)
}

func (r *AppResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var model AppModel
	var plan types.Object
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(plan.As(ctx, &model, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := r.api.Create(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applyAppAPIToState(apiModel, &model, true, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func (r *AppResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var model AppModel
	resp.Diagnostics.Append(req.State.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := r.api.Read(ctx, model)
	if restclient.IsNotFound(err) {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applyAppAPIToState(apiModel, &model, true, isAppImportState(&model))
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func (r *AppResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var model AppModel
	var plan types.Object
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(plan.As(ctx, &model, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := r.api.Update(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applyAppAPIToState(apiModel, &model, true, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func (r *AppResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var model AppModel
	resp.Diagnostics.Append(req.State.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.api.Delete(ctx, model); err != nil && !restclient.IsNotFound(err) {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
	}
}

func (r *AppResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func isAppImportState(state *AppModel) bool {
	if state == nil {
		return false
	}
	// Resources whose bodies contain only optional fields have no required
	// sentinel. An ID-only state is an import and must be hydrated from Read.
	if !state.Filename.IsNull() && !state.Filename.IsUnknown() {
		return false
	}
	if !state.Force.IsNull() && !state.Force.IsUnknown() {
		return false
	}
	return true
}

func applyAppAPIToState(api *AppModel, state *AppModel, preserveInputs bool, fillMissingInputs bool) {
	if api == nil || state == nil {
		return
	}
	if !api.Author.IsNull() && !api.Author.IsUnknown() {
		state.Author = api.Author
	}
	if state.Author.IsUnknown() {
		state.Author = types.StringNull()
	}
	if !api.Cribl.IsNull() && !api.Cribl.IsUnknown() {
		state.Cribl = api.Cribl
	}
	if state.Cribl.IsUnknown() {
		state.Cribl = types.ObjectNull(AppCriblAttrTypes())
	}
	if len(state.Cribl.AttributeTypes(context.Background())) == 0 {
		state.Cribl = types.ObjectNull(AppCriblAttrTypes())
	}
	if !api.Description.IsNull() && !api.Description.IsUnknown() {
		state.Description = api.Description
	}
	if state.Description.IsUnknown() {
		state.Description = types.StringNull()
	}
	if !api.DisplayName.IsNull() && !api.DisplayName.IsUnknown() {
		state.DisplayName = api.DisplayName
	}
	if state.DisplayName.IsUnknown() {
		state.DisplayName = types.StringNull()
	}
	if !preserveInputs || (fillMissingInputs && (state.Filename.IsNull() || state.Filename.IsUnknown())) {
		if !api.Filename.IsNull() && !api.Filename.IsUnknown() {
			state.Filename = api.Filename
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.Force.IsNull() || state.Force.IsUnknown())) {
		if !api.Force.IsNull() && !api.Force.IsUnknown() {
			state.Force = api.Force
		}
	}
	if !preserveInputs || (fillMissingInputs && (state.ID.IsNull() || state.ID.IsUnknown())) {
		if !api.ID.IsNull() && !api.ID.IsUnknown() {
			state.ID = api.ID
		}
	}
	if !api.MinLogStreamVersion.IsNull() && !api.MinLogStreamVersion.IsUnknown() {
		state.MinLogStreamVersion = api.MinLogStreamVersion
	}
	if state.MinLogStreamVersion.IsUnknown() {
		state.MinLogStreamVersion = types.StringNull()
	}
	if !api.Source.IsNull() && !api.Source.IsUnknown() {
		state.Source = api.Source
	}
	if state.Source.IsUnknown() {
		state.Source = types.StringNull()
	}
	if !api.Spec.IsNull() && !api.Spec.IsUnknown() {
		state.Spec = api.Spec
	}
	if state.Spec.IsUnknown() {
		state.Spec = types.StringNull()
	}
	if !api.Version.IsNull() && !api.Version.IsUnknown() {
		state.Version = api.Version
	}
	if state.Version.IsUnknown() {
		state.Version = types.StringNull()
	}
}

func AppDebug(value any) string {
	return fmt.Sprintf("%v", value)
}
