// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AppAPI struct {
	client *restclient.Client
}

func newAppAPI(client *restclient.Client) AppAPI {
	return AppAPI{client: client}
}

func (a AppAPI) Create(ctx context.Context, model AppModel) (*AppModel, error) {
	if !model.Filename.IsNull() && !model.Filename.IsUnknown() && model.Filename.ValueString() != "" {
		source, err := a.upload(ctx, model.Filename.ValueString())
		if err != nil {
			return nil, err
		}
		model.Source = types.StringValue(source)
	} else if model.Source.IsNull() || model.Source.IsUnknown() || model.Source.ValueString() == "" {
		content, err := createAppArchive(model)
		if err != nil {
			return nil, err
		}
		filename := model.ID.ValueString() + ".tgz"
		source, err := a.uploadContent(ctx, filename, content)
		if err != nil {
			return nil, err
		}
		model.Source = types.StringValue(source)
	}
	return restclient.Post[AppModel, AppModel](ctx, a.client, "/apps", model)
}
func (a AppAPI) upload(ctx context.Context, filename string) (string, error) {
	content, err := os.ReadFile(filename)
	if err != nil {
		return "", fmt.Errorf("read app archive %q: %w", filename, err)
	}
	return a.uploadContent(ctx, filepath.Base(filename), content)
}

func (a AppAPI) uploadContent(ctx context.Context, filename string, content []byte) (string, error) {
	query := url.Values{"filename": []string{filename}}
	body, err := restclient.PutRaw(ctx, a.client, "/apps?"+query.Encode(), "application/octet-stream", content)
	if err != nil {
		return "", fmt.Errorf("upload app archive %q: %w", filename, err)
	}
	var response struct {
		Source string `json:"source"`
	}
	if err := json.Unmarshal(body, &response); err != nil {
		return "", fmt.Errorf("decode app upload response: %w", err)
	}
	if response.Source == "" {
		return "", fmt.Errorf("app upload response did not include source")
	}
	return response.Source, nil
}

func createAppArchive(model AppModel) ([]byte, error) {
	manifest := map[string]any{
		"name":        model.ID.ValueString(),
		"version":     "0.0.1",
		"displayName": model.ID.ValueString(),
		"cribl":       map[string]any{"type": "app"},
	}
	if !model.Version.IsNull() && !model.Version.IsUnknown() && model.Version.ValueString() != "" {
		manifest["version"] = model.Version.ValueString()
	}
	if !model.DisplayName.IsNull() && !model.DisplayName.IsUnknown() && model.DisplayName.ValueString() != "" {
		manifest["displayName"] = model.DisplayName.ValueString()
	}
	if !model.Author.IsNull() && !model.Author.IsUnknown() {
		manifest["author"] = model.Author.ValueString()
	}
	if !model.Description.IsNull() && !model.Description.IsUnknown() {
		manifest["description"] = model.Description.ValueString()
	}
	packageJSON, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encode generated app manifest: %w", err)
	}

	var output bytes.Buffer
	gzipWriter := gzip.NewWriter(&output)
	tarWriter := tar.NewWriter(gzipWriter)
	if err := tarWriter.WriteHeader(&tar.Header{Name: "static/", Mode: 0o755, Typeflag: tar.TypeDir}); err != nil {
		return nil, fmt.Errorf("write generated app static directory: %w", err)
	}
	files := []struct {
		name string
		body []byte
	}{
		{name: "package.json", body: packageJSON},
		{name: "static/index.html", body: []byte("<!doctype html><html><head><meta charset=\"utf-8\"><title>Cribl App</title></head><body><main id=\"app\"></main></body></html>")},
	}
	for _, file := range files {
		header := &tar.Header{Name: file.name, Mode: 0o644, Size: int64(len(file.body))}
		if err := tarWriter.WriteHeader(header); err != nil {
			return nil, fmt.Errorf("write generated app archive header: %w", err)
		}
		if _, err := tarWriter.Write(file.body); err != nil {
			return nil, fmt.Errorf("write generated app archive content: %w", err)
		}
	}
	if err := tarWriter.Close(); err != nil {
		return nil, fmt.Errorf("close generated app tar archive: %w", err)
	}
	if err := gzipWriter.Close(); err != nil {
		return nil, fmt.Errorf("close generated app gzip archive: %w", err)
	}
	return output.Bytes(), nil
}

func (a AppAPI) Read(ctx context.Context, model AppModel) (*AppModel, error) {
	return restclient.Get[AppModel](ctx, a.client, fmt.Sprintf("/apps/%s", model.ID.ValueString()))
}

func (a AppAPI) Update(ctx context.Context, model AppModel) (*AppModel, error) {
	body, err := model.updateBody()
	if err != nil {
		return nil, err
	}
	if _, err := restclient.Patch[map[string]any, any](ctx, a.client, fmt.Sprintf("/apps/%s", model.ID.ValueString()), body); err != nil {
		return nil, err
	}
	return a.Read(ctx, model)
}

func (a AppAPI) Delete(ctx context.Context, model AppModel) error {
	return restclient.Delete(ctx, a.client, fmt.Sprintf("/apps/%s", model.ID.ValueString()))
}
