// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ = context.Background
var _ = jsontypes.NormalizedType{}

type GrokModel struct {
	Content types.String  `tfsdk:"content" json:"content,omitempty"`
	GroupID types.String  `tfsdk:"group_id" json:"groupId,omitempty"`
	ID      types.String  `tfsdk:"id" json:"id,omitempty"`
	Size    types.Float64 `tfsdk:"size" json:"size,omitempty"`
	Tags    types.String  `tfsdk:"tags" json:"tags,omitempty"`
}

type GrokResourceModel struct {
	Content types.String  `tfsdk:"content" json:"content,omitempty"`
	GroupID types.String  `tfsdk:"group_id" json:"groupId,omitempty"`
	ID      types.String  `tfsdk:"id" json:"id,omitempty"`
	Size    types.Float64 `tfsdk:"size" json:"size,omitempty"`
	Tags    types.String  `tfsdk:"tags" json:"tags,omitempty"`
}

type GrokDataSourceModel struct {
	Content types.String  `tfsdk:"content" json:"content,omitempty"`
	GroupID types.String  `tfsdk:"group_id" json:"groupId,omitempty"`
	ID      types.String  `tfsdk:"id" json:"id,omitempty"`
	Size    types.Float64 `tfsdk:"size" json:"size,omitempty"`
	Tags    types.String  `tfsdk:"tags" json:"tags,omitempty"`
}

type GrokAPIModel struct {
	Content *string  `json:"content,omitempty"`
	GroupID *string  `json:"groupId,omitempty"`
	ID      *string  `json:"id,omitempty"`
	Size    *float64 `json:"size,omitempty"`
	Tags    *string  `json:"tags,omitempty"`
}

func GrokTerraformValueToJSON(value attr.Value) (any, error) {
	if value.IsNull() || value.IsUnknown() {
		return nil, nil
	}
	switch typed := value.(type) {
	case types.Bool:
		return typed.ValueBool(), nil
	case types.Int64:
		return typed.ValueInt64(), nil
	case types.Float64:
		return typed.ValueFloat64(), nil
	case types.String:
		return typed.ValueString(), nil
	case types.List:
		output := make([]any, 0, len(typed.Elements()))
		for _, element := range typed.Elements() {
			value, err := GrokTerraformValueToJSON(element)
			if err != nil {
				return nil, err
			}
			output = append(output, value)
		}
		return output, nil
	case types.Map:
		output := make(map[string]any, len(typed.Elements()))
		for key, element := range typed.Elements() {
			value, err := GrokTerraformValueToJSON(element)
			if err != nil {
				return nil, err
			}
			output[key] = value
		}
		return output, nil
	case types.Object:
		output := make(map[string]any, len(typed.Attributes()))
		for key, attribute := range typed.Attributes() {
			value, err := GrokTerraformValueToJSON(attribute)
			if err != nil {
				return nil, err
			}
			output[key] = value
		}
		return output, nil
	case interface{ ValueString() string }:
		return typed.ValueString(), nil
	default:
		return nil, fmt.Errorf("unsupported Terraform value %T", value)
	}
}

func (m GrokModel) MarshalJSON() ([]byte, error) {
	output := map[string]any{}
	if !m.Content.IsNull() && !m.Content.IsUnknown() {
		value, err := GrokTerraformValueToJSON(m.Content)
		if err != nil {
			return nil, fmt.Errorf("convert content to API value: %v", err)
		}
		output["content"] = value
	}
	if !m.ID.IsNull() && !m.ID.IsUnknown() {
		value, err := GrokTerraformValueToJSON(m.ID)
		if err != nil {
			return nil, fmt.Errorf("convert id to API value: %v", err)
		}
		output["id"] = value
	}
	return json.Marshal(output)
}

func (m *GrokModel) UnmarshalJSON(data []byte) error {
	var input GrokAPIModel
	if err := json.Unmarshal(data, &input); err != nil {
		return err
	}
	if input.Content != nil {
		m.Content = types.StringValue(*input.Content)
	} else {
		m.Content = types.StringNull()
	}
	if input.GroupID != nil {
		m.GroupID = types.StringValue(*input.GroupID)
	} else {
		m.GroupID = types.StringNull()
	}
	if input.ID != nil {
		m.ID = types.StringValue(*input.ID)
	} else {
		m.ID = types.StringNull()
	}
	if input.Size != nil {
		m.Size = types.Float64Value(*input.Size)
	} else {
		m.Size = types.Float64Null()
	}
	if input.Tags != nil {
		m.Tags = types.StringValue(*input.Tags)
	} else {
		m.Tags = types.StringNull()
	}
	return nil
}
