// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ = jsontypes.NormalizedType{}
var _ = types.String{}

var _ datasource.DataSource = &KeyDataSource{}
var _ datasource.DataSourceWithConfigure = &KeyDataSource{}

type KeyDataSource struct {
	client *restclient.Client
	api    KeyAPI
}

func NewKeyDataSource() datasource.DataSource {
	return &KeyDataSource{}
}

func (d *KeyDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_key"
}

func (d *KeyDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Key Data Source",
		Attributes: map[string]schema.Attribute{
			"algorithm": schema.StringAttribute{
				Computed: true,
			},
			"created": schema.Float64Attribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"expires": schema.Float64Attribute{
				Computed: true,
			},
			"group": schema.StringAttribute{
				Computed:    true,
				Description: `Name of the Worker Group/Fleet that created this key`,
			},
			"group_id": schema.StringAttribute{
				Required:    true,
				Description: `Worker group ID.`,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"iv_size": schema.Int64Attribute{
				Computed:    true,
				Description: `Length of the initialization vector, in bytes`,
			},
			"key_id": schema.StringAttribute{
				Computed:    true,
				Description: `API-assigned key ID returned by Cribl.`,
			},
			"keyclass": schema.Float64Attribute{
				Computed: true,
			},
			"kms": schema.StringAttribute{
				Computed: true,
			},
			"use_iv": schema.BoolAttribute{
				Computed:    true,
				Description: `Seed encryption with a [nonce](https://en.wikipedia.org/wiki/Cryptographic_nonce) to make the key more random and unique. Must be enabled with the aes-256-gcm algorithm.`,
			},
		},
	}
}

func (d *KeyDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clients, ok := req.ProviderData.(*ProviderClients)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *ProviderClients, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	d.client = clients.RC
	d.api = newKeyAPI(d.client)
}

func (d *KeyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var model KeyModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := d.api.Read(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applyKeyAPIToState(apiModel, &model, false, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func KeyDataSourceDebug(value any) string {
	return fmt.Sprintf("%v", value)
}
