// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"unicode"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ = context.Background
var _ = jsontypes.NormalizedType{}

type MappingRulesetModel struct {
	Active  types.Bool   `tfsdk:"active" json:"active,omitempty"`
	Conf    types.Object `tfsdk:"conf" json:"conf,omitempty"`
	ID      types.String `tfsdk:"id" json:"id,omitempty"`
	Product types.String `tfsdk:"product" json:"product,omitempty"`
}

type MappingRulesetResourceModel struct {
	Active  types.Bool   `tfsdk:"active" json:"active,omitempty"`
	Conf    types.Object `tfsdk:"conf" json:"conf,omitempty"`
	ID      types.String `tfsdk:"id" json:"id,omitempty"`
	Product types.String `tfsdk:"product" json:"product,omitempty"`
}

type MappingRulesetDataSourceModel struct {
	Active  types.Bool   `tfsdk:"active" json:"active,omitempty"`
	Conf    types.Object `tfsdk:"conf" json:"conf,omitempty"`
	ID      types.String `tfsdk:"id" json:"id,omitempty"`
	Product types.String `tfsdk:"product" json:"product,omitempty"`
}

type MappingRulesetAPIModel struct {
	Active  *bool   `json:"active,omitempty"`
	Conf    any     `json:"conf,omitempty"`
	ID      *string `json:"id,omitempty"`
	Product *string `json:"product,omitempty"`
}

type MappingRulesetConfModel struct {
	Functions types.List `tfsdk:"functions" json:"functions,omitempty"`
}

type MappingRulesetConfAPIModel struct {
	Functions any `json:"functions,omitempty"`
}

func MappingRulesetConfAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"functions": types.ListType{ElemType: types.ObjectType{AttrTypes: MappingRulesetConfFunctionsAttrTypes()}},
	}
}

type MappingRulesetConfFunctionsModel struct {
	ID          types.String `tfsdk:"id" json:"id,omitempty"`
	Filter      types.String `tfsdk:"filter" json:"filter,omitempty"`
	Disabled    types.Bool   `tfsdk:"disabled" json:"disabled,omitempty"`
	Final       types.Bool   `tfsdk:"final" json:"final,omitempty"`
	Description types.String `tfsdk:"description" json:"description,omitempty"`
	Conf        types.Object `tfsdk:"conf" json:"conf,omitempty"`
	GroupID     types.String `tfsdk:"group_id" json:"groupId,omitempty"`
}

type MappingRulesetConfFunctionsAPIModel struct {
	ID          *string `json:"id,omitempty"`
	Filter      *string `json:"filter,omitempty"`
	Disabled    *bool   `json:"disabled,omitempty"`
	Final       *bool   `json:"final,omitempty"`
	Description *string `json:"description,omitempty"`
	Conf        any     `json:"conf,omitempty"`
	GroupID     *string `json:"groupId,omitempty"`
}

func MappingRulesetConfFunctionsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"id":          types.StringType,
		"filter":      types.StringType,
		"disabled":    types.BoolType,
		"final":       types.BoolType,
		"description": types.StringType,
		"conf":        types.ObjectType{AttrTypes: MappingRulesetConfFunctionsConfAttrTypes()},
		"group_id":    types.StringType,
	}
}

type MappingRulesetConfFunctionsConfModel struct {
	Add types.List `tfsdk:"add" json:"add,omitempty"`
}

type MappingRulesetConfFunctionsConfAPIModel struct {
	Add any `json:"add,omitempty"`
}

func MappingRulesetConfFunctionsConfAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"add": types.ListType{ElemType: types.ObjectType{AttrTypes: MappingRulesetConfFunctionsConfAddAttrTypes()}},
	}
}

type MappingRulesetConfFunctionsConfAddModel struct {
	Name  types.String `tfsdk:"name" json:"name,omitempty"`
	Value types.String `tfsdk:"value" json:"value,omitempty"`
}

type MappingRulesetConfFunctionsConfAddAPIModel struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

func MappingRulesetConfFunctionsConfAddAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":  types.StringType,
		"value": types.StringType,
	}
}

func MappingRulesetTerraformValueToJSON(value attr.Value) (any, error) {
	if value.IsNull() || value.IsUnknown() {
		return nil, nil
	}
	switch typed := value.(type) {
	case types.Bool:
		return typed.ValueBool(), nil
	case types.Int64:
		return typed.ValueInt64(), nil
	case types.Float64:
		return typed.ValueFloat64(), nil
	case types.String:
		return typed.ValueString(), nil
	case types.List:
		output := make([]any, 0, len(typed.Elements()))
		for _, element := range typed.Elements() {
			value, err := MappingRulesetTerraformValueToJSON(element)
			if err != nil {
				return nil, err
			}
			output = append(output, value)
		}
		return output, nil
	case types.Map:
		output := make(map[string]any, len(typed.Elements()))
		for key, element := range typed.Elements() {
			value, err := MappingRulesetTerraformValueToJSON(element)
			if err != nil {
				return nil, err
			}
			if value == nil {
				continue
			}
			output[key] = value
		}
		return output, nil
	case types.Object:
		output := make(map[string]any, len(typed.Attributes()))
		for key, attribute := range typed.Attributes() {
			value, err := MappingRulesetTerraformValueToJSON(attribute)
			if err != nil {
				return nil, err
			}
			if value == nil {
				continue
			}
			output[MappingRulesetTerraformNameToAPIName(key)] = value
		}
		return output, nil
	case interface{ ValueString() string }:
		return typed.ValueString(), nil
	default:
		return nil, fmt.Errorf("unsupported Terraform value %T", value)
	}
}

func mappingRulesetID(model MappingRulesetModel) string {
	if model.ID.IsNull() || model.ID.IsUnknown() || model.ID.ValueString() == "" {
		return "default"
	}
	return model.ID.ValueString()
}

func mappingRulesetConfWithDefaults(value any) any {
	conf, ok := value.(map[string]any)
	if !ok {
		return value
	}
	functions, ok := conf["functions"].([]any)
	if !ok {
		return value
	}
	for index, item := range functions {
		function, ok := item.(map[string]any)
		if !ok {
			continue
		}
		if id, ok := function["id"].(string); !ok || id == "" {
			function["id"] = "eval"
		}
		if _, ok := function["final"]; !ok {
			function["final"] = true
		}
		confValue, ok := function["conf"].(map[string]any)
		if ok {
			addItems, ok := confValue["add"].([]any)
			if ok {
				for addIndex, addItem := range addItems {
					add, ok := addItem.(map[string]any)
					if !ok {
						continue
					}
					if name, ok := add["name"].(string); !ok || name == "" {
						add["name"] = "groupId"
					}
					addItems[addIndex] = add
				}
				confValue["add"] = addItems
				function["conf"] = confValue
			}
		}
		functions[index] = function
	}
	conf["functions"] = functions
	return conf
}

func MappingRulesetTerraformNameToAPIName(name string) string {
	prefix := ""
	if strings.HasPrefix(name, "__template_") {
		prefix = "__template_"
		name = strings.TrimPrefix(name, prefix)
	}
	var output strings.Builder
	upperNext := false
	for _, char := range name {
		if char == '_' {
			upperNext = true
			continue
		}
		if upperNext {
			output.WriteRune(unicode.ToUpper(char))
			upperNext = false
			continue
		}
		output.WriteRune(char)
	}
	return prefix + output.String()
}

func MappingRulesetAPIValueToTerraformValue(value any, typ attr.Type) (attr.Value, error) {
	if value == nil {
		return MappingRulesetTerraformNullValue(typ)
	}
	if typ.Equal(types.BoolType) {
		typed, ok := value.(bool)
		if !ok {
			return nil, fmt.Errorf("expected bool, got %T", value)
		}
		return types.BoolValue(typed), nil
	}
	if typ.Equal(types.Int64Type) {
		typed, ok := value.(float64)
		if !ok {
			return nil, fmt.Errorf("expected number, got %T", value)
		}
		return types.Int64Value(int64(typed)), nil
	}
	if typ.Equal(types.Float64Type) {
		typed, ok := value.(float64)
		if !ok {
			return nil, fmt.Errorf("expected number, got %T", value)
		}
		return types.Float64Value(typed), nil
	}
	if typ.Equal(types.StringType) {
		typed, ok := value.(string)
		if !ok {
			return nil, fmt.Errorf("expected string, got %T", value)
		}
		return types.StringValue(typed), nil
	}
	switch typed := typ.(type) {
	case types.ListType:
		input, ok := value.([]any)
		if !ok {
			return nil, fmt.Errorf("expected list, got %T", value)
		}
		output := make([]attr.Value, 0, len(input))
		for _, item := range input {
			nested, err := MappingRulesetAPIValueToTerraformValue(item, typed.ElemType)
			if err != nil {
				return nil, err
			}
			output = append(output, nested)
		}
		value, diags := types.ListValue(typed.ElemType, output)
		if diags.HasError() {
			return nil, fmt.Errorf("%v", diags)
		}
		return value, nil
	case types.MapType:
		input, ok := value.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("expected map, got %T", value)
		}
		output := make(map[string]attr.Value, len(input))
		for key, item := range input {
			nested, err := MappingRulesetAPIValueToTerraformValue(item, typed.ElemType)
			if err != nil {
				return nil, err
			}
			output[key] = nested
		}
		value, diags := types.MapValue(typed.ElemType, output)
		if diags.HasError() {
			return nil, fmt.Errorf("%v", diags)
		}
		return value, nil
	case types.ObjectType:
		input, ok := value.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("expected object, got %T", value)
		}
		output := make(map[string]attr.Value, len(typed.AttrTypes))
		for key, attrType := range typed.AttrTypes {
			apiKey := MappingRulesetTerraformNameToAPIName(key)
			item, ok := input[apiKey]
			if !ok {
				item, ok = input[key]
			}
			if !ok {
				nested, err := MappingRulesetTerraformNullValue(attrType)
				if err != nil {
					return nil, err
				}
				output[key] = nested
				continue
			}
			nested, err := MappingRulesetAPIValueToTerraformValue(item, attrType)
			if err != nil {
				return nil, err
			}
			output[key] = nested
		}
		value, diags := types.ObjectValue(typed.AttrTypes, output)
		if diags.HasError() {
			return nil, fmt.Errorf("%v", diags)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unsupported Terraform type %T", typ)
	}
}

func MappingRulesetTerraformNullValue(typ attr.Type) (attr.Value, error) {
	if typ.Equal(types.BoolType) {
		return types.BoolNull(), nil
	}
	if typ.Equal(types.Int64Type) {
		return types.Int64Null(), nil
	}
	if typ.Equal(types.Float64Type) {
		return types.Float64Null(), nil
	}
	if typ.Equal(types.StringType) {
		return types.StringNull(), nil
	}
	switch typed := typ.(type) {
	case types.ListType:
		return types.ListNull(typed.ElemType), nil
	case types.MapType:
		return types.MapNull(typed.ElemType), nil
	case types.ObjectType:
		return types.ObjectNull(typed.AttrTypes), nil
	default:
		return nil, fmt.Errorf("unsupported Terraform type %T", typ)
	}
}

func (m MappingRulesetModel) MarshalJSON() ([]byte, error) {
	output := map[string]any{}
	if !m.Active.IsNull() && !m.Active.IsUnknown() {
		value, err := MappingRulesetTerraformValueToJSON(m.Active)
		if err != nil {
			return nil, fmt.Errorf("convert active to API value: %v", err)
		}
		output["active"] = value
	}
	if !m.Conf.IsNull() && !m.Conf.IsUnknown() {
		value, err := MappingRulesetTerraformValueToJSON(m.Conf)
		if err != nil {
			return nil, fmt.Errorf("convert conf to API value: %v", err)
		}
		value = mappingRulesetConfWithDefaults(value)
		output["conf"] = value
	}
	output["id"] = mappingRulesetID(m)
	return json.Marshal(output)
}

func (m *MappingRulesetModel) UnmarshalJSON(data []byte) error {
	var input MappingRulesetAPIModel
	if err := json.Unmarshal(data, &input); err != nil {
		return err
	}
	if input.Active != nil {
		m.Active = types.BoolValue(*input.Active)
	} else {
		m.Active = types.BoolNull()
	}
	if input.Conf != nil {
		value, err := MappingRulesetAPIValueToTerraformValue(input.Conf, types.ObjectType{AttrTypes: MappingRulesetConfAttrTypes()})
		if err != nil {
			return fmt.Errorf("convert conf from API value: %v", err)
		}
		m.Conf = value.(types.Object)
	} else {
		m.Conf = types.ObjectNull(MappingRulesetConfAttrTypes())
	}
	if input.ID != nil {
		m.ID = types.StringValue(*input.ID)
	} else {
		m.ID = types.StringNull()
	}
	if input.Product != nil {
		m.Product = types.StringValue(*input.Product)
	} else {
		m.Product = types.StringNull()
	}
	return nil
}
