// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ = jsontypes.NormalizedType{}
var _ = types.String{}

var _ datasource.DataSource = &MonitorsDataSource{}
var _ datasource.DataSourceWithConfigure = &MonitorsDataSource{}

type MonitorsDataSource struct {
	client *restclient.Client
}

type MonitorsListDataSourceModel struct {
	Items types.List `tfsdk:"items"`
}

func NewMonitorsDataSource() datasource.DataSource {
	return &MonitorsDataSource{}
}

func (d *MonitorsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_monitors"
}

func (d *MonitorsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Monitors Data Source",
		Attributes: map[string]schema.Attribute{

			"items": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"description": schema.StringAttribute{
							Computed: true,
						},
						"enabled": schema.BoolAttribute{
							Computed: true,
						},
						"firing_after": schema.Float64Attribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"is_default": schema.BoolAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"notification_policies": schema.ListAttribute{
							Computed:    true,
							ElementType: types.StringType,
						},
						"notifications_enabled": schema.BoolAttribute{
							Computed: true,
						},
						"ok_after": schema.Float64Attribute{
							Computed: true,
						},
						"params": schema.StringAttribute{
							Computed:    true,
							Description: `Monitor parameters as JSON string (use jsonencode({...}) in HCL).`,
							CustomType:  jsontypes.NormalizedType{},
						},
						"query": schema.StringAttribute{
							Computed:    true,
							Description: `PromQL string or MonitorQuery object as JSON. Use a plain string or jsonencode({...}) in HCL.`,
							CustomType:  jsontypes.NormalizedType{},
						},
						"rules": schema.StringAttribute{
							Computed:    true,
							Description: `Array of monitor rules as JSON string (use jsonencode([...]) in HCL).`,
							CustomType:  jsontypes.NormalizedType{},
						},
						"schedule_interval_seconds": schema.Float64Attribute{
							Computed: true,
						},
						"silences": schema.ListAttribute{
							Computed:    true,
							ElementType: types.StringType,
						},
						"sql_override": schema.StringAttribute{
							Computed:    true,
							Description: `SQL override as JSON string, e.g. jsonencode({instant: '...', range: '...'}).`,
							CustomType:  jsontypes.NormalizedType{},
						},
					},
				},
			},
		},
	}
}

func (d *MonitorsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clients, ok := req.ProviderData.(*ProviderClients)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *ProviderClients, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	d.client = clients.RC
}

func (d *MonitorsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var model MonitorsListDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	items, err := restclient.Get[[]MonitorModel](ctx, d.client, "/products/aetos/monitors")
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	values := []attr.Value{}
	if items != nil {
		values = make([]attr.Value, 0, len(*items))
		for _, item := range *items {
			values = append(values, types.ObjectValueMust(MonitorsItemAttrTypes(), map[string]attr.Value{"description": item.Description, "enabled": item.Enabled, "firing_after": item.FiringAfter, "id": item.ID, "is_default": item.IsDefault, "name": item.Name, "notification_policies": item.NotificationPolicies, "notifications_enabled": item.NotificationsEnabled, "ok_after": item.OkAfter, "params": item.Params, "query": item.Query, "rules": item.Rules, "schedule_interval_seconds": item.ScheduleIntervalSeconds, "silences": item.Silences, "sql_override": item.SqlOverride}))
		}
	}
	model.Items = types.ListValueMust(types.ObjectType{AttrTypes: MonitorsItemAttrTypes()}, values)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func MonitorsItemAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"description":               types.StringType,
		"enabled":                   types.BoolType,
		"firing_after":              types.Float64Type,
		"id":                        types.StringType,
		"is_default":                types.BoolType,
		"name":                      types.StringType,
		"notification_policies":     types.ListType{ElemType: types.StringType},
		"notifications_enabled":     types.BoolType,
		"ok_after":                  types.Float64Type,
		"params":                    jsontypes.NormalizedType{},
		"query":                     jsontypes.NormalizedType{},
		"rules":                     jsontypes.NormalizedType{},
		"schedule_interval_seconds": types.Float64Type,
		"silences":                  types.ListType{ElemType: types.StringType},
		"sql_override":              jsontypes.NormalizedType{},
	}
}
