// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ = jsontypes.NormalizedType{}
var _ = types.String{}

var _ datasource.DataSource = &PackVarsDataSource{}
var _ datasource.DataSourceWithConfigure = &PackVarsDataSource{}

type PackVarsDataSource struct {
	client *restclient.Client
	api    PackVarsAPI
}

func NewPackVarsDataSource() datasource.DataSource {
	return &PackVarsDataSource{}
}

func (d *PackVarsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_pack_vars"
}

func (d *PackVarsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "PackVars Data Source",
		Attributes: map[string]schema.Attribute{
			"args": schema.ListNestedAttribute{
				Computed:    true,
				Description: `Argument definitions for expression-type variables. Each item has type and name (e.g. for (val / 1073741824).toFixed(precision || 5)).`,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"type": schema.StringAttribute{
							Computed:    true,
							Description: `Argument type (e.g. number, string)`,
						},
						"name": schema.StringAttribute{
							Computed:    true,
							Description: `Argument name`,
						},
					},
				},
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"group_id": schema.StringAttribute{
				Required:    true,
				Description: `Worker group ID.`,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `Global variable name`,
			},
			"lib": schema.StringAttribute{
				Computed: true,
			},
			"pack": schema.StringAttribute{
				Required:    true,
				Description: `The <code>id</code> of the Pack.`,
			},
			"tags": schema.StringAttribute{
				Computed: true,
			},
			"type": schema.StringAttribute{
				Computed: true,
			},
			"value": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (d *PackVarsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clients, ok := req.ProviderData.(*ProviderClients)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *ProviderClients, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	d.client = clients.RC
	d.api = newPackVarsAPI(d.client)
}

func (d *PackVarsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var model PackVarsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := d.api.Read(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applyPackVarsAPIToState(apiModel, &model, false, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func PackVarsDataSourceDebug(value any) string {
	return fmt.Sprintf("%v", value)
}
