// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
)

type PackRoutesAPI struct {
	client *restclient.Client
}

func newPackRoutesAPI(client *restclient.Client) PackRoutesAPI {
	return PackRoutesAPI{client: client}
}

func (a PackRoutesAPI) Create(ctx context.Context, model PackRoutesModel) (*PackRoutesModel, error) {
	return restclient.Patch[PackRoutesModel, PackRoutesModel](ctx, a.client, fmt.Sprintf("/m/%s/p/%s/routes/default", model.GroupID.ValueString(), resolvePackIDForRestAPI(ctx, a.client, model.GroupID.ValueString(), model.Pack.ValueString())), model)
}

func (a PackRoutesAPI) Read(ctx context.Context, model PackRoutesModel) (*PackRoutesModel, error) {
	return restclient.Get[PackRoutesModel](ctx, a.client, fmt.Sprintf("/m/%s/p/%s/routes/default", model.GroupID.ValueString(), resolvePackIDForRestAPI(ctx, a.client, model.GroupID.ValueString(), model.Pack.ValueString())))
}

func (a PackRoutesAPI) Update(ctx context.Context, model PackRoutesModel) (*PackRoutesModel, error) {
	body, err := model.updateBody()
	if err != nil {
		return nil, err
	}
	if _, err := restclient.Patch[map[string]any, any](ctx, a.client, fmt.Sprintf("/m/%s/p/%s/routes/default", model.GroupID.ValueString(), resolvePackIDForRestAPI(ctx, a.client, model.GroupID.ValueString(), model.Pack.ValueString())), body); err != nil {
		return nil, err
	}
	return a.Read(ctx, model)
}

func (a PackRoutesAPI) Delete(ctx context.Context, model PackRoutesModel) error {
	body := map[string]any{"id": "default", "routes": []any{map[string]any{"disabled": false, "filter": "true", "final": true, "name": "Default", "pipeline": "main"}}}
	_, err := restclient.Patch[map[string]any, PackRoutesModel](ctx, a.client, fmt.Sprintf("/m/%s/p/%s/routes/default", model.GroupID.ValueString(), resolvePackIDForRestAPI(ctx, a.client, model.GroupID.ValueString(), model.Pack.ValueString())), body)
	return err
}
