// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
)

type SearchDatatypeAPI struct {
	client *restclient.Client
}

func newSearchDatatypeAPI(client *restclient.Client) SearchDatatypeAPI {
	return SearchDatatypeAPI{client: client}
}

func (a SearchDatatypeAPI) Create(ctx context.Context, model SearchDatatypeModel) (*SearchDatatypeModel, error) {
	return restclient.Post[SearchDatatypeModel, SearchDatatypeModel](ctx, a.client, fmt.Sprintf("/m/%s/search/datatypes", "default_search"), model)
}

func (a SearchDatatypeAPI) Read(ctx context.Context, model SearchDatatypeModel) (*SearchDatatypeModel, error) {
	return restclient.Get[SearchDatatypeModel](ctx, a.client, fmt.Sprintf("/m/%s/search/datatypes/%s", "default_search", model.ID.ValueString()))
}

func (a SearchDatatypeAPI) Update(ctx context.Context, model SearchDatatypeModel) (*SearchDatatypeModel, error) {
	return restclient.Patch[SearchDatatypeModel, SearchDatatypeModel](ctx, a.client, fmt.Sprintf("/m/%s/search/datatypes/%s", "default_search", model.ID.ValueString()), model)
}

func (a SearchDatatypeAPI) Delete(ctx context.Context, model SearchDatatypeModel) error {
	return restclient.Delete(ctx, a.client, fmt.Sprintf("/m/%s/search/datatypes/%s", "default_search", model.ID.ValueString()))
}
