// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	tfTypes "github.com/criblio/terraform-provider-criblio/internal/provider/types"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/operations"
	"github.com/criblio/terraform-provider-criblio/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *SearchDashboardResourceModel) RefreshFromOperationsCreateSearchDashboardResponseBody(ctx context.Context, resp *operations.CreateSearchDashboardResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if len(resp.Items) == 0 {
			diags.AddError("Unexpected response from API", "Missing response body array data.")
			return diags
		}

		diags.Append(r.RefreshFromSharedSearchDashboard(ctx, &resp.Items[0])...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *SearchDashboardResourceModel) RefreshFromOperationsGetSearchDashboardByIDResponseBody(ctx context.Context, resp *operations.GetSearchDashboardByIDResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if len(resp.Items) == 0 {
			diags.AddError("Unexpected response from API", "Missing response body array data.")
			return diags
		}

		diags.Append(r.RefreshFromSharedSearchDashboard(ctx, &resp.Items[0])...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *SearchDashboardResourceModel) RefreshFromOperationsUpdateSearchDashboardByIDResponseBody(ctx context.Context, resp *operations.UpdateSearchDashboardByIDResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if len(resp.Items) == 0 {
			diags.AddError("Unexpected response from API", "Missing response body array data.")
			return diags
		}

		diags.Append(r.RefreshFromSharedSearchDashboard(ctx, &resp.Items[0])...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *SearchDashboardResourceModel) RefreshFromSharedSearchDashboard(ctx context.Context, resp *shared.SearchDashboard) diag.Diagnostics {
	var diags diag.Diagnostics

	r.CacheTTLSeconds = types.Float64PointerValue(resp.CacheTTLSeconds)
	r.Category = types.StringPointerValue(resp.Category)
	r.Description = types.StringPointerValue(resp.Description)
	r.Elements = []tfTypes.DashboardElementUnion{}

	for _, elementsItem := range resp.Elements {
		var elements tfTypes.DashboardElementUnion

		if elementsItem.DashboardElementVisualization != nil {
			elements.DashboardElementVisualization = &tfTypes.DashboardElementVisualization{}
			if len(elementsItem.DashboardElementVisualization.Config) > 0 {
				elements.DashboardElementVisualization.Config = make(map[string]jsontypes.Normalized, len(elementsItem.DashboardElementVisualization.Config))
				for key, value := range elementsItem.DashboardElementVisualization.Config {
					result, _ := json.Marshal(value)
					elements.DashboardElementVisualization.Config[key] = jsontypes.NewNormalizedValue(string(result))
				}
			}
			elements.DashboardElementVisualization.HidePanel = types.BoolPointerValue(elementsItem.DashboardElementVisualization.HidePanel)
			elements.DashboardElementVisualization.HorizontalChart = types.BoolPointerValue(elementsItem.DashboardElementVisualization.HorizontalChart)
			elements.DashboardElementVisualization.ID = types.StringValue(elementsItem.DashboardElementVisualization.ID)
			elements.DashboardElementVisualization.Layout.H = types.Float64Value(elementsItem.DashboardElementVisualization.Layout.H)
			elements.DashboardElementVisualization.Layout.W = types.Float64Value(elementsItem.DashboardElementVisualization.Layout.W)
			elements.DashboardElementVisualization.Layout.X = types.Float64Value(elementsItem.DashboardElementVisualization.Layout.X)
			elements.DashboardElementVisualization.Layout.Y = types.Float64Value(elementsItem.DashboardElementVisualization.Layout.Y)
			if elementsItem.DashboardElementVisualization.Search.SearchQuerySaved != nil {
				elements.DashboardElementVisualization.Search.SearchQuerySaved = &tfTypes.SearchQuerySaved{}
				elements.DashboardElementVisualization.Search.SearchQuerySaved.Query = types.StringPointerValue(elementsItem.DashboardElementVisualization.Search.SearchQuerySaved.Query)
				elements.DashboardElementVisualization.Search.SearchQuerySaved.QueryID = types.StringValue(elementsItem.DashboardElementVisualization.Search.SearchQuerySaved.QueryID)
				if elementsItem.DashboardElementVisualization.Search.SearchQuerySaved.RunMode != nil {
					elements.DashboardElementVisualization.Search.SearchQuerySaved.RunMode = types.StringValue(string(*elementsItem.DashboardElementVisualization.Search.SearchQuerySaved.RunMode))
				} else {
					elements.DashboardElementVisualization.Search.SearchQuerySaved.RunMode = types.StringNull()
				}
				elements.DashboardElementVisualization.Search.SearchQuerySaved.Type = types.StringValue(string(elementsItem.DashboardElementVisualization.Search.SearchQuerySaved.Type))
			}
			if elementsItem.DashboardElementVisualization.Search.SearchQueryInline != nil {
				elements.DashboardElementVisualization.Search.SearchQueryInline = &tfTypes.SearchQueryInline{}
				if elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Earliest != nil {
					elements.DashboardElementVisualization.Search.SearchQueryInline.Earliest = &tfTypes.SearchQueryEarliest{}
					if elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Earliest.Str != nil {
						elements.DashboardElementVisualization.Search.SearchQueryInline.Earliest.Str = types.StringPointerValue(elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Earliest.Str)
					}
					if elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Earliest.Number != nil {
						elements.DashboardElementVisualization.Search.SearchQueryInline.Earliest.Number = types.Float64PointerValue(elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Earliest.Number)
					}
				}
				if elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Latest != nil {
					elements.DashboardElementVisualization.Search.SearchQueryInline.Latest = &tfTypes.SearchQueryLatest{}
					if elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Latest.Str != nil {
						elements.DashboardElementVisualization.Search.SearchQueryInline.Latest.Str = types.StringPointerValue(elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Latest.Str)
					}
					if elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Latest.Number != nil {
						elements.DashboardElementVisualization.Search.SearchQueryInline.Latest.Number = types.Float64PointerValue(elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Latest.Number)
					}
				}
				elements.DashboardElementVisualization.Search.SearchQueryInline.ParentSearchID = types.StringPointerValue(elementsItem.DashboardElementVisualization.Search.SearchQueryInline.ParentSearchID)
				elements.DashboardElementVisualization.Search.SearchQueryInline.Query = types.StringValue(elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Query)
				elements.DashboardElementVisualization.Search.SearchQueryInline.SampleRate = types.Float64PointerValue(elementsItem.DashboardElementVisualization.Search.SearchQueryInline.SampleRate)
				elements.DashboardElementVisualization.Search.SearchQueryInline.Timezone = types.StringPointerValue(elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Timezone)
				elements.DashboardElementVisualization.Search.SearchQueryInline.Type = types.StringValue(string(elementsItem.DashboardElementVisualization.Search.SearchQueryInline.Type))
			}
			if elementsItem.DashboardElementVisualization.Search.SearchQueryValues != nil {
				elements.DashboardElementVisualization.Search.SearchQueryValues = &tfTypes.SearchQueryValues{}
				elements.DashboardElementVisualization.Search.SearchQueryValues.Type = types.StringValue(string(elementsItem.DashboardElementVisualization.Search.SearchQueryValues.Type))
				elements.DashboardElementVisualization.Search.SearchQueryValues.Values = make([]types.String, 0, len(elementsItem.DashboardElementVisualization.Search.SearchQueryValues.Values))
				for _, v := range elementsItem.DashboardElementVisualization.Search.SearchQueryValues.Values {
					elements.DashboardElementVisualization.Search.SearchQueryValues.Values = append(elements.DashboardElementVisualization.Search.SearchQueryValues.Values, types.StringValue(v))
				}
			}
			elements.DashboardElementVisualization.Title = types.StringPointerValue(elementsItem.DashboardElementVisualization.Title)
			if elementsItem.DashboardElementVisualization.TitleAction == nil {
				elements.DashboardElementVisualization.TitleAction = nil
			} else {
				elements.DashboardElementVisualization.TitleAction = &tfTypes.TitleAction{}
				elements.DashboardElementVisualization.TitleAction.Label = types.StringValue(elementsItem.DashboardElementVisualization.TitleAction.Label)
				elements.DashboardElementVisualization.TitleAction.OpenInNewTab = types.BoolPointerValue(elementsItem.DashboardElementVisualization.TitleAction.OpenInNewTab)
				elements.DashboardElementVisualization.TitleAction.URL = types.StringValue(elementsItem.DashboardElementVisualization.TitleAction.URL)
			}
			elements.DashboardElementVisualization.Type = types.StringValue(string(elementsItem.DashboardElementVisualization.Type))
		}
		if elementsItem.DashboardElementInput != nil {
			elements.DashboardElementInput = &tfTypes.DashboardElementInput{}
			if elementsItem.DashboardElementInput.Config == nil {
				elements.DashboardElementInput.Config = nil
			} else {
				elements.DashboardElementInput.Config = &tfTypes.InputElementConfig{}
				if elementsItem.DashboardElementInput.Config.DefaultValue != nil {
					elements.DashboardElementInput.Config.DefaultValue = &tfTypes.DefaultValueUnion{}
					if elementsItem.DashboardElementInput.Config.DefaultValue.Str != nil {
						elements.DashboardElementInput.Config.DefaultValue.Str = types.StringPointerValue(elementsItem.DashboardElementInput.Config.DefaultValue.Str)
					}
					if elementsItem.DashboardElementInput.Config.DefaultValue.Number != nil {
						elements.DashboardElementInput.Config.DefaultValue.Number = types.Float64PointerValue(elementsItem.DashboardElementInput.Config.DefaultValue.Number)
					}
					if elementsItem.DashboardElementInput.Config.DefaultValue.DefaultValue != nil {
						elements.DashboardElementInput.Config.DefaultValue.DefaultValue = &tfTypes.DefaultValue{}
						if elementsItem.DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Str != nil {
							elements.DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Str = types.StringPointerValue(elementsItem.DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Str)
						}
						if elementsItem.DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Number != nil {
							elements.DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Number = types.Float64PointerValue(elementsItem.DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Number)
						}
						if elementsItem.DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Str != nil {
							elements.DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Str = types.StringPointerValue(elementsItem.DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Str)
						}
						if elementsItem.DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Number != nil {
							elements.DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Number = types.Float64PointerValue(elementsItem.DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Number)
						}
						elements.DashboardElementInput.Config.DefaultValue.DefaultValue.Timezone = types.StringPointerValue(elementsItem.DashboardElementInput.Config.DefaultValue.DefaultValue.Timezone)
					}
				}
			}
			elements.DashboardElementInput.HidePanel = types.BoolPointerValue(elementsItem.DashboardElementInput.HidePanel)
			elements.DashboardElementInput.HorizontalChart = types.BoolPointerValue(elementsItem.DashboardElementInput.HorizontalChart)
			elements.DashboardElementInput.ID = types.StringValue(elementsItem.DashboardElementInput.ID)
			elements.DashboardElementInput.InputID = types.StringValue(elementsItem.DashboardElementInput.InputID)
			elements.DashboardElementInput.Layout.H = types.Float64Value(elementsItem.DashboardElementInput.Layout.H)
			elements.DashboardElementInput.Layout.W = types.Float64Value(elementsItem.DashboardElementInput.Layout.W)
			elements.DashboardElementInput.Layout.X = types.Float64Value(elementsItem.DashboardElementInput.Layout.X)
			elements.DashboardElementInput.Layout.Y = types.Float64Value(elementsItem.DashboardElementInput.Layout.Y)
			if elementsItem.DashboardElementInput.Search != nil {
				elements.DashboardElementInput.Search = &tfTypes.SearchQuery{}
				if elementsItem.DashboardElementInput.Search.SearchQuerySaved != nil {
					elements.DashboardElementInput.Search.SearchQuerySaved = &tfTypes.SearchQuerySaved{}
					elements.DashboardElementInput.Search.SearchQuerySaved.Query = types.StringPointerValue(elementsItem.DashboardElementInput.Search.SearchQuerySaved.Query)
					elements.DashboardElementInput.Search.SearchQuerySaved.QueryID = types.StringValue(elementsItem.DashboardElementInput.Search.SearchQuerySaved.QueryID)
					if elementsItem.DashboardElementInput.Search.SearchQuerySaved.RunMode != nil {
						elements.DashboardElementInput.Search.SearchQuerySaved.RunMode = types.StringValue(string(*elementsItem.DashboardElementInput.Search.SearchQuerySaved.RunMode))
					} else {
						elements.DashboardElementInput.Search.SearchQuerySaved.RunMode = types.StringNull()
					}
					elements.DashboardElementInput.Search.SearchQuerySaved.Type = types.StringValue(string(elementsItem.DashboardElementInput.Search.SearchQuerySaved.Type))
				}
				if elementsItem.DashboardElementInput.Search.SearchQueryInline != nil {
					elements.DashboardElementInput.Search.SearchQueryInline = &tfTypes.SearchQueryInline{}
					if elementsItem.DashboardElementInput.Search.SearchQueryInline.Earliest != nil {
						elements.DashboardElementInput.Search.SearchQueryInline.Earliest = &tfTypes.SearchQueryEarliest{}
						if elementsItem.DashboardElementInput.Search.SearchQueryInline.Earliest.Str != nil {
							elements.DashboardElementInput.Search.SearchQueryInline.Earliest.Str = types.StringPointerValue(elementsItem.DashboardElementInput.Search.SearchQueryInline.Earliest.Str)
						}
						if elementsItem.DashboardElementInput.Search.SearchQueryInline.Earliest.Number != nil {
							elements.DashboardElementInput.Search.SearchQueryInline.Earliest.Number = types.Float64PointerValue(elementsItem.DashboardElementInput.Search.SearchQueryInline.Earliest.Number)
						}
					}
					if elementsItem.DashboardElementInput.Search.SearchQueryInline.Latest != nil {
						elements.DashboardElementInput.Search.SearchQueryInline.Latest = &tfTypes.SearchQueryLatest{}
						if elementsItem.DashboardElementInput.Search.SearchQueryInline.Latest.Str != nil {
							elements.DashboardElementInput.Search.SearchQueryInline.Latest.Str = types.StringPointerValue(elementsItem.DashboardElementInput.Search.SearchQueryInline.Latest.Str)
						}
						if elementsItem.DashboardElementInput.Search.SearchQueryInline.Latest.Number != nil {
							elements.DashboardElementInput.Search.SearchQueryInline.Latest.Number = types.Float64PointerValue(elementsItem.DashboardElementInput.Search.SearchQueryInline.Latest.Number)
						}
					}
					elements.DashboardElementInput.Search.SearchQueryInline.ParentSearchID = types.StringPointerValue(elementsItem.DashboardElementInput.Search.SearchQueryInline.ParentSearchID)
					elements.DashboardElementInput.Search.SearchQueryInline.Query = types.StringValue(elementsItem.DashboardElementInput.Search.SearchQueryInline.Query)
					elements.DashboardElementInput.Search.SearchQueryInline.SampleRate = types.Float64PointerValue(elementsItem.DashboardElementInput.Search.SearchQueryInline.SampleRate)
					elements.DashboardElementInput.Search.SearchQueryInline.Timezone = types.StringPointerValue(elementsItem.DashboardElementInput.Search.SearchQueryInline.Timezone)
					elements.DashboardElementInput.Search.SearchQueryInline.Type = types.StringValue(string(elementsItem.DashboardElementInput.Search.SearchQueryInline.Type))
				}
				if elementsItem.DashboardElementInput.Search.SearchQueryValues != nil {
					elements.DashboardElementInput.Search.SearchQueryValues = &tfTypes.SearchQueryValues{}
					elements.DashboardElementInput.Search.SearchQueryValues.Type = types.StringValue(string(elementsItem.DashboardElementInput.Search.SearchQueryValues.Type))
					elements.DashboardElementInput.Search.SearchQueryValues.Values = make([]types.String, 0, len(elementsItem.DashboardElementInput.Search.SearchQueryValues.Values))
					for _, v := range elementsItem.DashboardElementInput.Search.SearchQueryValues.Values {
						elements.DashboardElementInput.Search.SearchQueryValues.Values = append(elements.DashboardElementInput.Search.SearchQueryValues.Values, types.StringValue(v))
					}
				}
			}
			elements.DashboardElementInput.Title = types.StringPointerValue(elementsItem.DashboardElementInput.Title)
			if elementsItem.DashboardElementInput.TitleAction == nil {
				elements.DashboardElementInput.TitleAction = nil
			} else {
				elements.DashboardElementInput.TitleAction = &tfTypes.TitleAction{}
				elements.DashboardElementInput.TitleAction.Label = types.StringValue(elementsItem.DashboardElementInput.TitleAction.Label)
				elements.DashboardElementInput.TitleAction.OpenInNewTab = types.BoolPointerValue(elementsItem.DashboardElementInput.TitleAction.OpenInNewTab)
				elements.DashboardElementInput.TitleAction.URL = types.StringValue(elementsItem.DashboardElementInput.TitleAction.URL)
			}
			elements.DashboardElementInput.Type = types.StringValue(string(elementsItem.DashboardElementInput.Type))
		}
		if elementsItem.DashboardElement != nil {
			elements.DashboardElement = &tfTypes.DashboardElement{}
			if elementsItem.DashboardElement.Config == nil {
				elements.DashboardElement.Config = nil
			} else {
				elements.DashboardElement.Config = &tfTypes.MarkdownElementConfig{}
				elements.DashboardElement.Config.Markdown = types.StringValue(elementsItem.DashboardElement.Config.Markdown)
			}
			elements.DashboardElement.HidePanel = types.BoolPointerValue(elementsItem.DashboardElement.HidePanel)
			elements.DashboardElement.HorizontalChart = types.BoolPointerValue(elementsItem.DashboardElement.HorizontalChart)
			elements.DashboardElement.ID = types.StringValue(elementsItem.DashboardElement.ID)
			elements.DashboardElement.Layout.H = types.Float64Value(elementsItem.DashboardElement.Layout.H)
			elements.DashboardElement.Layout.W = types.Float64Value(elementsItem.DashboardElement.Layout.W)
			elements.DashboardElement.Layout.X = types.Float64Value(elementsItem.DashboardElement.Layout.X)
			elements.DashboardElement.Layout.Y = types.Float64Value(elementsItem.DashboardElement.Layout.Y)
			if elementsItem.DashboardElement.Search == nil {
				elements.DashboardElement.Search = nil
			} else {
				elements.DashboardElement.Search = &tfTypes.PanelQueryDefinition{}
				elements.DashboardElement.Search.Alias = types.StringPointerValue(elementsItem.DashboardElement.Search.Alias)
				elements.DashboardElement.Search.LocalID = types.StringValue(elementsItem.DashboardElement.Search.LocalID)
				elements.DashboardElement.Search.Query = types.StringValue(elementsItem.DashboardElement.Search.Query)
			}
			if elementsItem.DashboardElement.TitleAction == nil {
				elements.DashboardElement.TitleAction = nil
			} else {
				elements.DashboardElement.TitleAction = &tfTypes.TitleAction{}
				elements.DashboardElement.TitleAction.Label = types.StringValue(elementsItem.DashboardElement.TitleAction.Label)
				elements.DashboardElement.TitleAction.OpenInNewTab = types.BoolPointerValue(elementsItem.DashboardElement.TitleAction.OpenInNewTab)
				elements.DashboardElement.TitleAction.URL = types.StringValue(elementsItem.DashboardElement.TitleAction.URL)
			}
			elements.DashboardElement.Type = types.StringValue(string(elementsItem.DashboardElement.Type))
			elements.DashboardElement.Variant = types.StringValue(string(elementsItem.DashboardElement.Variant))
		}

		r.Elements = append(r.Elements, elements)
	}
	if len(resp.Groups) > 0 {
		r.Groups = make(map[string]tfTypes.DashboardGroups, len(resp.Groups))
		for dashboardGroupsKey, dashboardGroupsValue := range resp.Groups {
			var dashboardGroupsResult tfTypes.DashboardGroups
			if dashboardGroupsValue.Action == nil {
				dashboardGroupsResult.Action = nil
			} else {
				dashboardGroupsResult.Action = &tfTypes.DashboardGroupsAction{}
				dashboardGroupsResult.Action.Label = types.StringValue(dashboardGroupsValue.Action.Label)
				if len(dashboardGroupsValue.Action.Params) > 0 {
					dashboardGroupsResult.Action.Params = make(map[string]types.String, len(dashboardGroupsValue.Action.Params))
					for key1, value1 := range dashboardGroupsValue.Action.Params {
						dashboardGroupsResult.Action.Params[key1] = types.StringValue(value1)
					}
				}
				dashboardGroupsResult.Action.Target = types.StringValue(dashboardGroupsValue.Action.Target)
			}
			dashboardGroupsResult.Collapsed = types.BoolPointerValue(dashboardGroupsValue.Collapsed)
			dashboardGroupsResult.InputID = types.StringPointerValue(dashboardGroupsValue.InputID)
			dashboardGroupsResult.Title = types.StringValue(dashboardGroupsValue.Title)

			r.Groups[dashboardGroupsKey] = dashboardGroupsResult
		}
	}
	r.ID = types.StringValue(resp.ID)
	r.Name = types.StringValue(resp.Name)
	r.RefreshRate = types.Float64PointerValue(resp.RefreshRate)
	if resp.Schedule == nil {
		r.Schedule = nil
	} else {
		r.Schedule = &tfTypes.SavedQuerySchedule{}
		r.Schedule.CronSchedule = types.StringValue(resp.Schedule.CronSchedule)
		r.Schedule.Enabled = types.BoolValue(resp.Schedule.Enabled)
		r.Schedule.KeepLastN = types.Float64Value(resp.Schedule.KeepLastN)
		r.Schedule.Notifications.Disabled = types.BoolValue(resp.Schedule.Notifications.Disabled)
		r.Schedule.Tz = types.StringValue(resp.Schedule.Tz)
	}

	return diags
}

func (r *SearchDashboardResourceModel) ToOperationsDeleteSearchDashboardByIDRequest(ctx context.Context) (*operations.DeleteSearchDashboardByIDRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.DeleteSearchDashboardByIDRequest{
		ID: id,
	}

	return &out, diags
}

func (r *SearchDashboardResourceModel) ToOperationsGetSearchDashboardByIDRequest(ctx context.Context) (*operations.GetSearchDashboardByIDRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetSearchDashboardByIDRequest{
		ID: id,
	}

	return &out, diags
}

func (r *SearchDashboardResourceModel) ToOperationsUpdateSearchDashboardByIDRequest(ctx context.Context) (*operations.UpdateSearchDashboardByIDRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	searchDashboard, searchDashboardDiags := r.ToSharedSearchDashboard(ctx)
	diags.Append(searchDashboardDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateSearchDashboardByIDRequest{
		ID:              id,
		SearchDashboard: *searchDashboard,
	}

	return &out, diags
}

func (r *SearchDashboardResourceModel) ToSharedSearchDashboard(ctx context.Context) (*shared.SearchDashboard, diag.Diagnostics) {
	var diags diag.Diagnostics

	cacheTTLSeconds := new(float64)
	if !r.CacheTTLSeconds.IsUnknown() && !r.CacheTTLSeconds.IsNull() {
		*cacheTTLSeconds = r.CacheTTLSeconds.ValueFloat64()
	} else {
		cacheTTLSeconds = nil
	}
	category := new(string)
	if !r.Category.IsUnknown() && !r.Category.IsNull() {
		*category = r.Category.ValueString()
	} else {
		category = nil
	}
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	elements := make([]shared.DashboardElementUnion, 0, len(r.Elements))
	for elementsItem := range r.Elements {
		if r.Elements[elementsItem].DashboardElementVisualization != nil {
			config := make(map[string]interface{})
			for configKey := range r.Elements[elementsItem].DashboardElementVisualization.Config {
				var configInst interface{}
				_ = json.Unmarshal([]byte(r.Elements[elementsItem].DashboardElementVisualization.Config[configKey].ValueString()), &configInst)
				config[configKey] = configInst
			}
			hidePanel := new(bool)
			if !r.Elements[elementsItem].DashboardElementVisualization.HidePanel.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.HidePanel.IsNull() {
				*hidePanel = r.Elements[elementsItem].DashboardElementVisualization.HidePanel.ValueBool()
			} else {
				hidePanel = nil
			}
			horizontalChart := new(bool)
			if !r.Elements[elementsItem].DashboardElementVisualization.HorizontalChart.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.HorizontalChart.IsNull() {
				*horizontalChart = r.Elements[elementsItem].DashboardElementVisualization.HorizontalChart.ValueBool()
			} else {
				horizontalChart = nil
			}
			var id string
			id = r.Elements[elementsItem].DashboardElementVisualization.ID.ValueString()

			var h float64
			h = r.Elements[elementsItem].DashboardElementVisualization.Layout.H.ValueFloat64()

			var w float64
			w = r.Elements[elementsItem].DashboardElementVisualization.Layout.W.ValueFloat64()

			var x float64
			x = r.Elements[elementsItem].DashboardElementVisualization.Layout.X.ValueFloat64()

			var y float64
			y = r.Elements[elementsItem].DashboardElementVisualization.Layout.Y.ValueFloat64()

			layout := shared.DashboardLayout{
				H: h,
				W: w,
				X: x,
				Y: y,
			}
			var search shared.SearchQuery
			var searchQuerySaved *shared.SearchQuerySaved
			if r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQuerySaved != nil {
				query := new(string)
				if !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQuerySaved.Query.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQuerySaved.Query.IsNull() {
					*query = r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQuerySaved.Query.ValueString()
				} else {
					query = nil
				}
				var queryID string
				queryID = r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQuerySaved.QueryID.ValueString()

				runMode := new(shared.SavesSearchRunMode)
				if !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQuerySaved.RunMode.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQuerySaved.RunMode.IsNull() {
					*runMode = shared.SavesSearchRunMode(r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQuerySaved.RunMode.ValueString())
				} else {
					runMode = nil
				}
				typeVar := shared.TypeSaved(r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQuerySaved.Type.ValueString())
				searchQuerySaved = &shared.SearchQuerySaved{
					Query:   query,
					QueryID: queryID,
					RunMode: runMode,
					Type:    typeVar,
				}
			}
			if searchQuerySaved != nil {
				search = shared.SearchQuery{
					SearchQuerySaved: searchQuerySaved,
				}
			}
			var searchQueryInline *shared.SearchQueryInline
			if r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline != nil {
				var earliest *shared.SearchQueryEarliest
				if r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Earliest != nil {
					str := new(string)
					if !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Earliest.Str.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Earliest.Str.IsNull() {
						*str = r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Earliest.Str.ValueString()
					} else {
						str = nil
					}
					if str != nil {
						earliest = &shared.SearchQueryEarliest{
							Str: str,
						}
					}
					number := new(float64)
					if !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Earliest.Number.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Earliest.Number.IsNull() {
						*number = r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Earliest.Number.ValueFloat64()
					} else {
						number = nil
					}
					if number != nil {
						earliest = &shared.SearchQueryEarliest{
							Number: number,
						}
					}
				}
				var latest *shared.SearchQueryLatest
				if r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Latest != nil {
					str1 := new(string)
					if !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Latest.Str.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Latest.Str.IsNull() {
						*str1 = r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Latest.Str.ValueString()
					} else {
						str1 = nil
					}
					if str1 != nil {
						latest = &shared.SearchQueryLatest{
							Str: str1,
						}
					}
					number1 := new(float64)
					if !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Latest.Number.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Latest.Number.IsNull() {
						*number1 = r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Latest.Number.ValueFloat64()
					} else {
						number1 = nil
					}
					if number1 != nil {
						latest = &shared.SearchQueryLatest{
							Number: number1,
						}
					}
				}
				parentSearchID := new(string)
				if !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.ParentSearchID.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.ParentSearchID.IsNull() {
					*parentSearchID = r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.ParentSearchID.ValueString()
				} else {
					parentSearchID = nil
				}
				var query1 string
				query1 = r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Query.ValueString()

				sampleRate := new(float64)
				if !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.SampleRate.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.SampleRate.IsNull() {
					*sampleRate = r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.SampleRate.ValueFloat64()
				} else {
					sampleRate = nil
				}
				timezone := new(string)
				if !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Timezone.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Timezone.IsNull() {
					*timezone = r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Timezone.ValueString()
				} else {
					timezone = nil
				}
				typeVar1 := shared.TypeInline(r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryInline.Type.ValueString())
				searchQueryInline = &shared.SearchQueryInline{
					Earliest:       earliest,
					Latest:         latest,
					ParentSearchID: parentSearchID,
					Query:          query1,
					SampleRate:     sampleRate,
					Timezone:       timezone,
					Type:           typeVar1,
				}
			}
			if searchQueryInline != nil {
				search = shared.SearchQuery{
					SearchQueryInline: searchQueryInline,
				}
			}
			var searchQueryValues *shared.SearchQueryValues
			if r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryValues != nil {
				typeVar2 := shared.TypeValues(r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryValues.Type.ValueString())
				values := make([]string, 0, len(r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryValues.Values))
				for valuesIndex := range r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryValues.Values {
					values = append(values, r.Elements[elementsItem].DashboardElementVisualization.Search.SearchQueryValues.Values[valuesIndex].ValueString())
				}
				searchQueryValues = &shared.SearchQueryValues{
					Type:   typeVar2,
					Values: values,
				}
			}
			if searchQueryValues != nil {
				search = shared.SearchQuery{
					SearchQueryValues: searchQueryValues,
				}
			}
			title := new(string)
			if !r.Elements[elementsItem].DashboardElementVisualization.Title.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.Title.IsNull() {
				*title = r.Elements[elementsItem].DashboardElementVisualization.Title.ValueString()
			} else {
				title = nil
			}
			var titleAction *shared.TitleAction
			if r.Elements[elementsItem].DashboardElementVisualization.TitleAction != nil {
				var label string
				label = r.Elements[elementsItem].DashboardElementVisualization.TitleAction.Label.ValueString()

				openInNewTab := new(bool)
				if !r.Elements[elementsItem].DashboardElementVisualization.TitleAction.OpenInNewTab.IsUnknown() && !r.Elements[elementsItem].DashboardElementVisualization.TitleAction.OpenInNewTab.IsNull() {
					*openInNewTab = r.Elements[elementsItem].DashboardElementVisualization.TitleAction.OpenInNewTab.ValueBool()
				} else {
					openInNewTab = nil
				}
				var url string
				url = r.Elements[elementsItem].DashboardElementVisualization.TitleAction.URL.ValueString()

				titleAction = &shared.TitleAction{
					Label:        label,
					OpenInNewTab: openInNewTab,
					URL:          url,
				}
			}
			typeVar3 := shared.VisualizationElementType(r.Elements[elementsItem].DashboardElementVisualization.Type.ValueString())
			dashboardElementVisualization := shared.DashboardElementVisualization{
				Config:          config,
				HidePanel:       hidePanel,
				HorizontalChart: horizontalChart,
				ID:              id,
				Layout:          layout,
				Search:          search,
				Title:           title,
				TitleAction:     titleAction,
				Type:            typeVar3,
			}
			elements = append(elements, shared.DashboardElementUnion{
				DashboardElementVisualization: &dashboardElementVisualization,
			})
		}
		if r.Elements[elementsItem].DashboardElementInput != nil {
			var config1 *shared.InputElementConfig
			if r.Elements[elementsItem].DashboardElementInput.Config != nil {
				var defaultValue *shared.DefaultValueUnion
				if r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue != nil {
					str2 := new(string)
					if !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.Str.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.Str.IsNull() {
						*str2 = r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.Str.ValueString()
					} else {
						str2 = nil
					}
					if str2 != nil {
						defaultValue = &shared.DefaultValueUnion{
							Str: str2,
						}
					}
					number2 := new(float64)
					if !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.Number.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.Number.IsNull() {
						*number2 = r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.Number.ValueFloat64()
					} else {
						number2 = nil
					}
					if number2 != nil {
						defaultValue = &shared.DefaultValueUnion{
							Number: number2,
						}
					}
					var defaultValue1 *shared.DefaultValue
					if r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue != nil {
						var earliest1 shared.InputElementConfigEarliest
						str3 := new(string)
						if !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Str.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Str.IsNull() {
							*str3 = r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Str.ValueString()
						} else {
							str3 = nil
						}
						if str3 != nil {
							earliest1 = shared.InputElementConfigEarliest{
								Str: str3,
							}
						}
						number3 := new(float64)
						if !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Number.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Number.IsNull() {
							*number3 = r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Earliest.Number.ValueFloat64()
						} else {
							number3 = nil
						}
						if number3 != nil {
							earliest1 = shared.InputElementConfigEarliest{
								Number: number3,
							}
						}
						var latest1 shared.InputElementConfigLatest
						str4 := new(string)
						if !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Str.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Str.IsNull() {
							*str4 = r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Str.ValueString()
						} else {
							str4 = nil
						}
						if str4 != nil {
							latest1 = shared.InputElementConfigLatest{
								Str: str4,
							}
						}
						number4 := new(float64)
						if !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Number.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Number.IsNull() {
							*number4 = r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Latest.Number.ValueFloat64()
						} else {
							number4 = nil
						}
						if number4 != nil {
							latest1 = shared.InputElementConfigLatest{
								Number: number4,
							}
						}
						timezone1 := new(string)
						if !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Timezone.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Timezone.IsNull() {
							*timezone1 = r.Elements[elementsItem].DashboardElementInput.Config.DefaultValue.DefaultValue.Timezone.ValueString()
						} else {
							timezone1 = nil
						}
						defaultValue1 = &shared.DefaultValue{
							Earliest: earliest1,
							Latest:   latest1,
							Timezone: timezone1,
						}
					}
					if defaultValue1 != nil {
						defaultValue = &shared.DefaultValueUnion{
							DefaultValue: defaultValue1,
						}
					}
				}
				config1 = &shared.InputElementConfig{
					DefaultValue: defaultValue,
				}
			}
			hidePanel1 := new(bool)
			if !r.Elements[elementsItem].DashboardElementInput.HidePanel.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.HidePanel.IsNull() {
				*hidePanel1 = r.Elements[elementsItem].DashboardElementInput.HidePanel.ValueBool()
			} else {
				hidePanel1 = nil
			}
			horizontalChart1 := new(bool)
			if !r.Elements[elementsItem].DashboardElementInput.HorizontalChart.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.HorizontalChart.IsNull() {
				*horizontalChart1 = r.Elements[elementsItem].DashboardElementInput.HorizontalChart.ValueBool()
			} else {
				horizontalChart1 = nil
			}
			var id1 string
			id1 = r.Elements[elementsItem].DashboardElementInput.ID.ValueString()

			var inputID string
			inputID = r.Elements[elementsItem].DashboardElementInput.InputID.ValueString()

			var h1 float64
			h1 = r.Elements[elementsItem].DashboardElementInput.Layout.H.ValueFloat64()

			var w1 float64
			w1 = r.Elements[elementsItem].DashboardElementInput.Layout.W.ValueFloat64()

			var x1 float64
			x1 = r.Elements[elementsItem].DashboardElementInput.Layout.X.ValueFloat64()

			var y1 float64
			y1 = r.Elements[elementsItem].DashboardElementInput.Layout.Y.ValueFloat64()

			layout1 := shared.DashboardLayout{
				H: h1,
				W: w1,
				X: x1,
				Y: y1,
			}
			var search1 *shared.SearchQuery
			if r.Elements[elementsItem].DashboardElementInput.Search != nil {
				var searchQuerySaved1 *shared.SearchQuerySaved
				if r.Elements[elementsItem].DashboardElementInput.Search.SearchQuerySaved != nil {
					query2 := new(string)
					if !r.Elements[elementsItem].DashboardElementInput.Search.SearchQuerySaved.Query.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Search.SearchQuerySaved.Query.IsNull() {
						*query2 = r.Elements[elementsItem].DashboardElementInput.Search.SearchQuerySaved.Query.ValueString()
					} else {
						query2 = nil
					}
					var queryId1 string
					queryId1 = r.Elements[elementsItem].DashboardElementInput.Search.SearchQuerySaved.QueryID.ValueString()

					runMode1 := new(shared.SavesSearchRunMode)
					if !r.Elements[elementsItem].DashboardElementInput.Search.SearchQuerySaved.RunMode.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Search.SearchQuerySaved.RunMode.IsNull() {
						*runMode1 = shared.SavesSearchRunMode(r.Elements[elementsItem].DashboardElementInput.Search.SearchQuerySaved.RunMode.ValueString())
					} else {
						runMode1 = nil
					}
					typeVar4 := shared.TypeSaved(r.Elements[elementsItem].DashboardElementInput.Search.SearchQuerySaved.Type.ValueString())
					searchQuerySaved1 = &shared.SearchQuerySaved{
						Query:   query2,
						QueryID: queryId1,
						RunMode: runMode1,
						Type:    typeVar4,
					}
				}
				if searchQuerySaved1 != nil {
					search1 = &shared.SearchQuery{
						SearchQuerySaved: searchQuerySaved1,
					}
				}
				var searchQueryInline1 *shared.SearchQueryInline
				if r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline != nil {
					var earliest2 *shared.SearchQueryEarliest
					if r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Earliest != nil {
						str5 := new(string)
						if !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Earliest.Str.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Earliest.Str.IsNull() {
							*str5 = r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Earliest.Str.ValueString()
						} else {
							str5 = nil
						}
						if str5 != nil {
							earliest2 = &shared.SearchQueryEarliest{
								Str: str5,
							}
						}
						number5 := new(float64)
						if !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Earliest.Number.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Earliest.Number.IsNull() {
							*number5 = r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Earliest.Number.ValueFloat64()
						} else {
							number5 = nil
						}
						if number5 != nil {
							earliest2 = &shared.SearchQueryEarliest{
								Number: number5,
							}
						}
					}
					var latest2 *shared.SearchQueryLatest
					if r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Latest != nil {
						str6 := new(string)
						if !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Latest.Str.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Latest.Str.IsNull() {
							*str6 = r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Latest.Str.ValueString()
						} else {
							str6 = nil
						}
						if str6 != nil {
							latest2 = &shared.SearchQueryLatest{
								Str: str6,
							}
						}
						number6 := new(float64)
						if !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Latest.Number.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Latest.Number.IsNull() {
							*number6 = r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Latest.Number.ValueFloat64()
						} else {
							number6 = nil
						}
						if number6 != nil {
							latest2 = &shared.SearchQueryLatest{
								Number: number6,
							}
						}
					}
					parentSearchId1 := new(string)
					if !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.ParentSearchID.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.ParentSearchID.IsNull() {
						*parentSearchId1 = r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.ParentSearchID.ValueString()
					} else {
						parentSearchId1 = nil
					}
					var query3 string
					query3 = r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Query.ValueString()

					sampleRate1 := new(float64)
					if !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.SampleRate.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.SampleRate.IsNull() {
						*sampleRate1 = r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.SampleRate.ValueFloat64()
					} else {
						sampleRate1 = nil
					}
					timezone2 := new(string)
					if !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Timezone.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Timezone.IsNull() {
						*timezone2 = r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Timezone.ValueString()
					} else {
						timezone2 = nil
					}
					typeVar5 := shared.TypeInline(r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryInline.Type.ValueString())
					searchQueryInline1 = &shared.SearchQueryInline{
						Earliest:       earliest2,
						Latest:         latest2,
						ParentSearchID: parentSearchId1,
						Query:          query3,
						SampleRate:     sampleRate1,
						Timezone:       timezone2,
						Type:           typeVar5,
					}
				}
				if searchQueryInline1 != nil {
					search1 = &shared.SearchQuery{
						SearchQueryInline: searchQueryInline1,
					}
				}
				var searchQueryValues1 *shared.SearchQueryValues
				if r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryValues != nil {
					typeVar6 := shared.TypeValues(r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryValues.Type.ValueString())
					values1 := make([]string, 0, len(r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryValues.Values))
					for valuesIndex1 := range r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryValues.Values {
						values1 = append(values1, r.Elements[elementsItem].DashboardElementInput.Search.SearchQueryValues.Values[valuesIndex1].ValueString())
					}
					searchQueryValues1 = &shared.SearchQueryValues{
						Type:   typeVar6,
						Values: values1,
					}
				}
				if searchQueryValues1 != nil {
					search1 = &shared.SearchQuery{
						SearchQueryValues: searchQueryValues1,
					}
				}
			}
			title1 := new(string)
			if !r.Elements[elementsItem].DashboardElementInput.Title.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.Title.IsNull() {
				*title1 = r.Elements[elementsItem].DashboardElementInput.Title.ValueString()
			} else {
				title1 = nil
			}
			var titleAction1 *shared.TitleAction
			if r.Elements[elementsItem].DashboardElementInput.TitleAction != nil {
				var label1 string
				label1 = r.Elements[elementsItem].DashboardElementInput.TitleAction.Label.ValueString()

				openInNewTab1 := new(bool)
				if !r.Elements[elementsItem].DashboardElementInput.TitleAction.OpenInNewTab.IsUnknown() && !r.Elements[elementsItem].DashboardElementInput.TitleAction.OpenInNewTab.IsNull() {
					*openInNewTab1 = r.Elements[elementsItem].DashboardElementInput.TitleAction.OpenInNewTab.ValueBool()
				} else {
					openInNewTab1 = nil
				}
				var url1 string
				url1 = r.Elements[elementsItem].DashboardElementInput.TitleAction.URL.ValueString()

				titleAction1 = &shared.TitleAction{
					Label:        label1,
					OpenInNewTab: openInNewTab1,
					URL:          url1,
				}
			}
			typeVar7 := shared.InputElementType(r.Elements[elementsItem].DashboardElementInput.Type.ValueString())
			dashboardElementInput := shared.DashboardElementInput{
				Config:          config1,
				HidePanel:       hidePanel1,
				HorizontalChart: horizontalChart1,
				ID:              id1,
				InputID:         inputID,
				Layout:          layout1,
				Search:          search1,
				Title:           title1,
				TitleAction:     titleAction1,
				Type:            typeVar7,
			}
			elements = append(elements, shared.DashboardElementUnion{
				DashboardElementInput: &dashboardElementInput,
			})
		}
		if r.Elements[elementsItem].DashboardElement != nil {
			var config2 *shared.MarkdownElementConfig
			if r.Elements[elementsItem].DashboardElement.Config != nil {
				var markdown string
				markdown = r.Elements[elementsItem].DashboardElement.Config.Markdown.ValueString()

				config2 = &shared.MarkdownElementConfig{
					Markdown: markdown,
				}
			}
			hidePanel2 := new(bool)
			if !r.Elements[elementsItem].DashboardElement.HidePanel.IsUnknown() && !r.Elements[elementsItem].DashboardElement.HidePanel.IsNull() {
				*hidePanel2 = r.Elements[elementsItem].DashboardElement.HidePanel.ValueBool()
			} else {
				hidePanel2 = nil
			}
			horizontalChart2 := new(bool)
			if !r.Elements[elementsItem].DashboardElement.HorizontalChart.IsUnknown() && !r.Elements[elementsItem].DashboardElement.HorizontalChart.IsNull() {
				*horizontalChart2 = r.Elements[elementsItem].DashboardElement.HorizontalChart.ValueBool()
			} else {
				horizontalChart2 = nil
			}
			var id2 string
			id2 = r.Elements[elementsItem].DashboardElement.ID.ValueString()

			var h2 float64
			h2 = r.Elements[elementsItem].DashboardElement.Layout.H.ValueFloat64()

			var w2 float64
			w2 = r.Elements[elementsItem].DashboardElement.Layout.W.ValueFloat64()

			var x2 float64
			x2 = r.Elements[elementsItem].DashboardElement.Layout.X.ValueFloat64()

			var y2 float64
			y2 = r.Elements[elementsItem].DashboardElement.Layout.Y.ValueFloat64()

			layout2 := shared.DashboardLayout{
				H: h2,
				W: w2,
				X: x2,
				Y: y2,
			}
			var search2 *shared.PanelQueryDefinition
			if r.Elements[elementsItem].DashboardElement.Search != nil {
				alias := new(string)
				if !r.Elements[elementsItem].DashboardElement.Search.Alias.IsUnknown() && !r.Elements[elementsItem].DashboardElement.Search.Alias.IsNull() {
					*alias = r.Elements[elementsItem].DashboardElement.Search.Alias.ValueString()
				} else {
					alias = nil
				}
				var localID string
				localID = r.Elements[elementsItem].DashboardElement.Search.LocalID.ValueString()

				var query4 string
				query4 = r.Elements[elementsItem].DashboardElement.Search.Query.ValueString()

				search2 = &shared.PanelQueryDefinition{
					Alias:   alias,
					LocalID: localID,
					Query:   query4,
				}
			}
			var titleAction2 *shared.TitleAction
			if r.Elements[elementsItem].DashboardElement.TitleAction != nil {
				var label2 string
				label2 = r.Elements[elementsItem].DashboardElement.TitleAction.Label.ValueString()

				openInNewTab2 := new(bool)
				if !r.Elements[elementsItem].DashboardElement.TitleAction.OpenInNewTab.IsUnknown() && !r.Elements[elementsItem].DashboardElement.TitleAction.OpenInNewTab.IsNull() {
					*openInNewTab2 = r.Elements[elementsItem].DashboardElement.TitleAction.OpenInNewTab.ValueBool()
				} else {
					openInNewTab2 = nil
				}
				var url2 string
				url2 = r.Elements[elementsItem].DashboardElement.TitleAction.URL.ValueString()

				titleAction2 = &shared.TitleAction{
					Label:        label2,
					OpenInNewTab: openInNewTab2,
					URL:          url2,
				}
			}
			typeVar8 := shared.MarkdownElementType(r.Elements[elementsItem].DashboardElement.Type.ValueString())
			variant := shared.VariantMarkdown(r.Elements[elementsItem].DashboardElement.Variant.ValueString())
			dashboardElement := shared.DashboardElement{
				Config:          config2,
				HidePanel:       hidePanel2,
				HorizontalChart: horizontalChart2,
				ID:              id2,
				Layout:          layout2,
				Search:          search2,
				TitleAction:     titleAction2,
				Type:            typeVar8,
				Variant:         variant,
			}
			elements = append(elements, shared.DashboardElementUnion{
				DashboardElement: &dashboardElement,
			})
		}
	}
	groups := make(map[string]shared.DashboardGroups)
	for groupsKey := range r.Groups {
		var action *shared.DashboardGroupsAction
		if r.Groups[groupsKey].Action != nil {
			var label3 string
			label3 = r.Groups[groupsKey].Action.Label.ValueString()

			params := make(map[string]string)
			for paramsKey := range r.Groups[groupsKey].Action.Params {
				var paramsInst string
				paramsInst = r.Groups[groupsKey].Action.Params[paramsKey].ValueString()

				params[paramsKey] = paramsInst
			}
			var target string
			target = r.Groups[groupsKey].Action.Target.ValueString()

			action = &shared.DashboardGroupsAction{
				Label:  label3,
				Params: params,
				Target: target,
			}
		}
		collapsed := new(bool)
		if !r.Groups[groupsKey].Collapsed.IsUnknown() && !r.Groups[groupsKey].Collapsed.IsNull() {
			*collapsed = r.Groups[groupsKey].Collapsed.ValueBool()
		} else {
			collapsed = nil
		}
		inputId1 := new(string)
		if !r.Groups[groupsKey].InputID.IsUnknown() && !r.Groups[groupsKey].InputID.IsNull() {
			*inputId1 = r.Groups[groupsKey].InputID.ValueString()
		} else {
			inputId1 = nil
		}
		var title2 string
		title2 = r.Groups[groupsKey].Title.ValueString()

		groupsInst := shared.DashboardGroups{
			Action:    action,
			Collapsed: collapsed,
			InputID:   inputId1,
			Title:     title2,
		}
		groups[groupsKey] = groupsInst
	}
	var id3 string
	id3 = r.ID.ValueString()

	var name string
	name = r.Name.ValueString()

	refreshRate := new(float64)
	if !r.RefreshRate.IsUnknown() && !r.RefreshRate.IsNull() {
		*refreshRate = r.RefreshRate.ValueFloat64()
	} else {
		refreshRate = nil
	}
	var schedule *shared.SavedQuerySchedule
	if r.Schedule != nil {
		var cronSchedule string
		cronSchedule = r.Schedule.CronSchedule.ValueString()

		var enabled bool
		enabled = r.Schedule.Enabled.ValueBool()

		var keepLastN float64
		keepLastN = r.Schedule.KeepLastN.ValueFloat64()

		var disabled bool
		disabled = r.Schedule.Notifications.Disabled.ValueBool()

		notifications := shared.Notifications{
			Disabled: disabled,
		}
		var tz string
		tz = r.Schedule.Tz.ValueString()

		schedule = &shared.SavedQuerySchedule{
			CronSchedule:  cronSchedule,
			Enabled:       enabled,
			KeepLastN:     keepLastN,
			Notifications: notifications,
			Tz:            tz,
		}
	}
	out := shared.SearchDashboard{
		CacheTTLSeconds: cacheTTLSeconds,
		Category:        category,
		Description:     description,
		Elements:        elements,
		Groups:          groups,
		ID:              id3,
		Name:            name,
		RefreshRate:     refreshRate,
		Schedule:        schedule,
	}

	return &out, diags
}
