// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"

	custom_stringplanmodifier "github.com/criblio/terraform-provider-criblio/internal/planmodifiers/stringplanmodifier"
	"github.com/criblio/terraform-provider-criblio/internal/restclient"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ = jsontypes.NormalizedType{}
var _ = types.String{}

var _ resource.Resource = &SearchEngineResource{}
var _ resource.ResourceWithConfigure = &SearchEngineResource{}
var _ resource.ResourceWithImportState = &SearchEngineResource{}

type SearchEngineResource struct {
	client *restclient.Client
	api    SearchEngineAPI
}

func NewSearchEngineResource() resource.Resource {
	return &SearchEngineResource{}
}

func (r *SearchEngineResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_search_engine"
}

func (r *SearchEngineResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "SearchEngine Resource",
		Attributes: map[string]schema.Attribute{
			"active_workflow": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: `The provisioning workflow that is currently active for the lakehouse engine, if any.`,
			},
			"datasets": schema.ListAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: `The <code>id</code> values for Datasets that are linked to the lakehouse engine.`,
				ElementType: types.StringType,
			},
			"deletion_started_at": schema.Int64Attribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: `Timestamp (in Unix time) when deletion was initiated for the lakehouse engine (if applicable), in milliseconds.`,
			},
			"description": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Computed:    true,
				Description: `Brief description of the lakehouse engine.`,
			},
			"effective_status": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: `Operational status of the lakehouse engine, accounting for both the engine and its underlying Worker Group. If the engine is ready but the Worker Group is not, reflects the Worker Group status. If the engine is not ready, reflects the engine status regardless of the Worker Group status.`,
			},
			"engine_type": schema.StringAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: `Type of engine. For lakehouse engines, always <code>local</code>.`,
			},
			"group_id": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Worker group ID.`,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
				},
			},
			"has_main": schema.BoolAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: `If <code>true</code>, the lakehouse engine currently owns the main Dataset.`,
			},
			"id": schema.StringAttribute{
				Required: true,
				Optional: false,
				Computed: false,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplaceIfConfigured(),
					custom_stringplanmodifier.SuppressDiff(custom_stringplanmodifier.ExplicitSuppress),
				},
			},
			"is_compute_deprovisioned": schema.BoolAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: `If <code>true</code>, compute for the lakehouse engine has been deprovisioned after termination.`,
			},
			"is_storage_deprovisioned": schema.BoolAttribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: `If <code>true</code>, the storage backing the lakehouse engine has been deprovisioned and fully cleaned up after termination.`,
			},
			"last_provisioned_ms": schema.Int64Attribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: `Timestamp (in Unix time) when the lakehouse engine was last provisioned or updated, in milliseconds.`,
			},
			"metrics_last_published_at": schema.Int64Attribute{
				Required:    false,
				Optional:    false,
				Computed:    true,
				Description: `Timestamp (in Unix time) when the lakehouse engine metrics were last published, in milliseconds.`,
			},
			"status": schema.StringAttribute{
				Required: false,
				Optional: false,
				Computed: true,
			},
			"tier_size": schema.StringAttribute{
				Required:    true,
				Optional:    false,
				Computed:    false,
				Description: `Storage and compute [tier size](https://docs.cribl.io/search/engine-setup/#sizes-list) for the lakehouse engine. Configuring sizes <code>3xlarge</code>, <code>4xlarge</code>,<code>5xlarge</code>, and <code>6xlarge</code> requires the <code>cribl_operator</code> role.`,
			},
		},
	}
}

func (r *SearchEngineResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clients, ok := req.ProviderData.(*ProviderClients)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *ProviderClients, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = clients.RC
	r.api = newSearchEngineAPI(r.client)
}

func (r *SearchEngineResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var model SearchEngineModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := r.api.Create(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applySearchEngineAPIToState(apiModel, &model, true, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func (r *SearchEngineResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var model SearchEngineModel
	resp.Diagnostics.Append(req.State.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := r.api.Read(ctx, model)
	if restclient.IsNotFound(err) {
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applySearchEngineAPIToState(apiModel, &model, true, isSearchEngineImportState(&model))
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func (r *SearchEngineResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var model SearchEngineModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := r.api.Update(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applySearchEngineAPIToState(apiModel, &model, true, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func (r *SearchEngineResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var model SearchEngineModel
	resp.Diagnostics.Append(req.State.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.api.Delete(ctx, model); err != nil && !restclient.IsNotFound(err) {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
	}
}

func (r *SearchEngineResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	dec := json.NewDecoder(bytes.NewReader([]byte(req.ID)))
	dec.DisallowUnknownFields()
	var data struct {
		GroupID string `json:"group_id"`
		ID      string `json:"id"`
	}
	if err := dec.Decode(&data); err != nil {
		resp.Diagnostics.AddError("Invalid ID", `The import ID is not valid. It is expected to be a JSON object string with the required path parameters: `+err.Error())
		return
	}
	if data.GroupID == "" {
		resp.Diagnostics.AddError("Missing required field", `The field group_id is required but was not found in the json encoded ID.`)
		return
	}
	if data.ID == "" {
		resp.Diagnostics.AddError("Missing required field", `The field id is required but was not found in the json encoded ID.`)
		return
	}
	var model SearchEngineModel
	model.GroupID = types.StringValue(data.GroupID)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("group_id"), data.GroupID)...)
	model.ID = types.StringValue(data.ID)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), data.ID)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := r.api.Read(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applySearchEngineAPIToState(apiModel, &model, false, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func isSearchEngineImportState(state *SearchEngineModel) bool {
	if state == nil {
		return false
	}
	if state.TierSize.IsNull() || state.TierSize.IsUnknown() {
		return true
	}
	return false
}

func applySearchEngineAPIToState(api *SearchEngineModel, state *SearchEngineModel, preserveInputs bool, fillMissingInputs bool) {
	if api == nil || state == nil {
		return
	}
	if !api.ActiveWorkflow.IsNull() && !api.ActiveWorkflow.IsUnknown() {
		state.ActiveWorkflow = api.ActiveWorkflow
	} else if state.ActiveWorkflow.IsNull() || state.ActiveWorkflow.IsUnknown() {
		state.ActiveWorkflow = types.StringValue("")
	}
	if !api.Datasets.IsNull() && !api.Datasets.IsUnknown() {
		state.Datasets = api.Datasets
	} else if state.Datasets.IsNull() || state.Datasets.IsUnknown() {
		state.Datasets = types.ListValueMust(types.StringType, nil)
	}
	if elementType := state.Datasets.ElementType(context.Background()); elementType == nil {
		state.Datasets = types.ListNull(types.StringType)
	}
	if !api.DeletionStartedAt.IsNull() && !api.DeletionStartedAt.IsUnknown() {
		state.DeletionStartedAt = api.DeletionStartedAt
	} else if state.DeletionStartedAt.IsNull() || state.DeletionStartedAt.IsUnknown() {
		state.DeletionStartedAt = types.Int64Value(0)
	}
	if !api.Description.IsNull() && !api.Description.IsUnknown() {
		state.Description = api.Description
	}
	if state.Description.IsUnknown() {
		state.Description = types.StringNull()
	}
	if !api.EffectiveStatus.IsNull() && !api.EffectiveStatus.IsUnknown() {
		state.EffectiveStatus = api.EffectiveStatus
	} else if state.EffectiveStatus.IsNull() || state.EffectiveStatus.IsUnknown() {
		state.EffectiveStatus = types.StringValue("")
	}
	if !api.EngineType.IsNull() && !api.EngineType.IsUnknown() {
		state.EngineType = api.EngineType
	} else if state.EngineType.IsNull() || state.EngineType.IsUnknown() {
		state.EngineType = types.StringValue("")
	}
	if !preserveInputs || (fillMissingInputs && (state.GroupID.IsNull() || state.GroupID.IsUnknown())) {
		if !api.GroupID.IsNull() && !api.GroupID.IsUnknown() {
			state.GroupID = api.GroupID
		}
	}
	if !api.HasMain.IsNull() && !api.HasMain.IsUnknown() {
		state.HasMain = api.HasMain
	} else if state.HasMain.IsNull() || state.HasMain.IsUnknown() {
		state.HasMain = types.BoolValue(false)
	}
	if !preserveInputs || (fillMissingInputs && (state.ID.IsNull() || state.ID.IsUnknown())) {
		if !api.ID.IsNull() && !api.ID.IsUnknown() {
			state.ID = api.ID
		}
	}
	if !api.IsComputeDeprovisioned.IsNull() && !api.IsComputeDeprovisioned.IsUnknown() {
		state.IsComputeDeprovisioned = api.IsComputeDeprovisioned
	} else if state.IsComputeDeprovisioned.IsNull() || state.IsComputeDeprovisioned.IsUnknown() {
		state.IsComputeDeprovisioned = types.BoolValue(false)
	}
	if !api.IsStorageDeprovisioned.IsNull() && !api.IsStorageDeprovisioned.IsUnknown() {
		state.IsStorageDeprovisioned = api.IsStorageDeprovisioned
	} else if state.IsStorageDeprovisioned.IsNull() || state.IsStorageDeprovisioned.IsUnknown() {
		state.IsStorageDeprovisioned = types.BoolValue(false)
	}
	if !api.LastProvisionedMs.IsNull() && !api.LastProvisionedMs.IsUnknown() {
		state.LastProvisionedMs = api.LastProvisionedMs
	} else if state.LastProvisionedMs.IsNull() || state.LastProvisionedMs.IsUnknown() {
		state.LastProvisionedMs = types.Int64Value(0)
	}
	if !api.MetricsLastPublishedAt.IsNull() && !api.MetricsLastPublishedAt.IsUnknown() {
		state.MetricsLastPublishedAt = api.MetricsLastPublishedAt
	} else if state.MetricsLastPublishedAt.IsNull() || state.MetricsLastPublishedAt.IsUnknown() {
		state.MetricsLastPublishedAt = types.Int64Value(0)
	}
	if !api.Status.IsNull() && !api.Status.IsUnknown() {
		state.Status = api.Status
	} else if state.Status.IsNull() || state.Status.IsUnknown() {
		state.Status = types.StringValue("")
	}
	if !preserveInputs || (fillMissingInputs && (state.TierSize.IsNull() || state.TierSize.IsUnknown())) {
		if !api.TierSize.IsNull() && !api.TierSize.IsUnknown() {
			state.TierSize = api.TierSize
		}
	}
}

func SearchEngineDebug(value any) string {
	return fmt.Sprintf("%v", value)
}
