// Code generated by tools/codegen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/criblio/terraform-provider-criblio/internal/restclient"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ = jsontypes.NormalizedType{}
var _ = types.String{}

var _ datasource.DataSource = &SubscriptionDataSource{}
var _ datasource.DataSourceWithConfigure = &SubscriptionDataSource{}

type SubscriptionDataSource struct {
	client *restclient.Client
	api    SubscriptionAPI
}

func NewSubscriptionDataSource() datasource.DataSource {
	return &SubscriptionDataSource{}
}

func (d *SubscriptionDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_subscription"
}

func (d *SubscriptionDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Subscription Data Source",
		Attributes: map[string]schema.Attribute{
			"consumer": schema.SingleNestedAttribute{
				Required:    false,
				Computed:    true,
				Description: `Consumers are now defined on projects instead of subscriptions.`,
			},
			"description": schema.StringAttribute{
				Required: false,
				Computed: true,
			},
			"disabled": schema.BoolAttribute{
				Required: false,
				Computed: true,
			},
			"filter": schema.StringAttribute{
				Required: false,
				Computed: true,
			},
			"group_id": schema.StringAttribute{
				Required:    true,
				Computed:    false,
				Description: `Worker group ID.`,
			},
			"id": schema.StringAttribute{
				Required: true,
				Computed: false,
			},
			"pipeline": schema.StringAttribute{
				Required: false,
				Computed: true,
			},
		},
	}
}

func (d *SubscriptionDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	clients, ok := req.ProviderData.(*ProviderClients)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *ProviderClients, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	d.client = clients.RC
	d.api = newSubscriptionAPI(d.client)
}

func (d *SubscriptionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var model SubscriptionModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}
	apiModel, err := d.api.Read(ctx, model)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	applySubscriptionAPIToState(apiModel, &model, false, false)
	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}

func SubscriptionDataSourceDebug(value any) string {
	return fmt.Sprintf("%v", value)
}
