// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type DiscoverRequestParam struct {
	Name  types.String `tfsdk:"name"`
	Value types.String `tfsdk:"value"`
}
