// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type OutputAzureDataExplorer struct {
	TemplateClientID              types.String                        `tfsdk:"template_client_id"`
	TemplateClientSecret          types.String                        `tfsdk:"template_client_secret"`
	TemplateClusterURL            types.String                        `tfsdk:"template_cluster_url"`
	TemplateDatabase              types.String                        `tfsdk:"template_database"`
	TemplateFormat                types.String                        `tfsdk:"template_format"`
	TemplateIngestURL             types.String                        `tfsdk:"template_ingest_url"`
	TemplateScope                 types.String                        `tfsdk:"template_scope"`
	TemplateTable                 types.String                        `tfsdk:"template_table"`
	TemplateTenantID              types.String                        `tfsdk:"template_tenant_id"`
	AddIDToStagePath              types.Bool                          `tfsdk:"add_id_to_stage_path"`
	AdditionalProperties          []AdditionalProperty                `tfsdk:"additional_properties"`
	AutomaticSchema               types.Bool                          `tfsdk:"automatic_schema"`
	Certificate                   *OutputAzureDataExplorerCertificate `tfsdk:"certificate"`
	ClientID                      types.String                        `tfsdk:"client_id"`
	ClientSecret                  types.String                        `tfsdk:"client_secret"`
	ClusterURL                    types.String                        `tfsdk:"cluster_url"`
	Compress                      types.String                        `tfsdk:"compress"`
	CompressionLevel              types.String                        `tfsdk:"compression_level"`
	Concurrency                   types.Float64                       `tfsdk:"concurrency"`
	Database                      types.String                        `tfsdk:"database"`
	DeadletterEnabled             types.Bool                          `tfsdk:"deadletter_enabled"`
	DeadletterPath                types.String                        `tfsdk:"deadletter_path"`
	Description                   types.String                        `tfsdk:"description"`
	DirectoryBatchSize            types.Float64                       `tfsdk:"directory_batch_size"`
	EmptyDirCleanupSec            types.Float64                       `tfsdk:"empty_dir_cleanup_sec"`
	EnablePageChecksum            types.Bool                          `tfsdk:"enable_page_checksum"`
	EnableStatistics              types.Bool                          `tfsdk:"enable_statistics"`
	EnableWritePageIndex          types.Bool                          `tfsdk:"enable_write_page_index"`
	Environment                   types.String                        `tfsdk:"environment"`
	ExtentTags                    []ExtentTag                         `tfsdk:"extent_tags"`
	FileNameSuffix                types.String                        `tfsdk:"file_name_suffix"`
	FlushImmediately              types.Bool                          `tfsdk:"flush_immediately"`
	FlushPeriodSec                types.Float64                       `tfsdk:"flush_period_sec"`
	Format                        types.String                        `tfsdk:"format"`
	ID                            types.String                        `tfsdk:"id"`
	IngestIfNotExists             []IngestIfNotExist                  `tfsdk:"ingest_if_not_exists"`
	IngestMode                    types.String                        `tfsdk:"ingest_mode"`
	IngestURL                     types.String                        `tfsdk:"ingest_url"`
	IsMappingObj                  types.Bool                          `tfsdk:"is_mapping_obj"`
	KeepAlive                     types.Bool                          `tfsdk:"keep_alive"`
	KeyValueMetadata              []ItemsTypeKeyValueMetadata         `tfsdk:"key_value_metadata"`
	MappingObj                    types.String                        `tfsdk:"mapping_obj"`
	MappingRef                    types.String                        `tfsdk:"mapping_ref"`
	MaxConcurrentFileParts        types.Float64                       `tfsdk:"max_concurrent_file_parts"`
	MaxFileIdleTimeSec            types.Float64                       `tfsdk:"max_file_idle_time_sec"`
	MaxFileOpenTimeSec            types.Float64                       `tfsdk:"max_file_open_time_sec"`
	MaxFileSizeMB                 types.Float64                       `tfsdk:"max_file_size_mb"`
	MaxOpenFiles                  types.Float64                       `tfsdk:"max_open_files"`
	MaxPayloadEvents              types.Float64                       `tfsdk:"max_payload_events"`
	MaxPayloadSizeKB              types.Float64                       `tfsdk:"max_payload_size_kb"`
	MaxRetryNum                   types.Float64                       `tfsdk:"max_retry_num"`
	OauthEndpoint                 types.String                        `tfsdk:"oauth_endpoint"`
	OauthType                     types.String                        `tfsdk:"oauth_type"`
	OnBackpressure                types.String                        `tfsdk:"on_backpressure"`
	OnDiskFullBackpressure        types.String                        `tfsdk:"on_disk_full_backpressure"`
	ParquetDataPageVersion        types.String                        `tfsdk:"parquet_data_page_version"`
	ParquetPageSize               types.String                        `tfsdk:"parquet_page_size"`
	ParquetRowGroupLength         types.Float64                       `tfsdk:"parquet_row_group_length"`
	ParquetSchema                 types.String                        `tfsdk:"parquet_schema"`
	ParquetVersion                types.String                        `tfsdk:"parquet_version"`
	Pipeline                      types.String                        `tfsdk:"pipeline"`
	PqCompress                    types.String                        `tfsdk:"pq_compress"`
	PqControls                    *OutputAzureDataExplorerPqControls  `tfsdk:"pq_controls"`
	PqMaxBackpressureSec          types.Float64                       `tfsdk:"pq_max_backpressure_sec"`
	PqMaxBufferSize               types.Float64                       `tfsdk:"pq_max_buffer_size"`
	PqMaxBufferSizeBytes          types.String                        `tfsdk:"pq_max_buffer_size_bytes"`
	PqMaxFileSize                 types.String                        `tfsdk:"pq_max_file_size"`
	PqMaxSize                     types.String                        `tfsdk:"pq_max_size"`
	PqMode                        types.String                        `tfsdk:"pq_mode"`
	PqOnBackpressure              types.String                        `tfsdk:"pq_on_backpressure"`
	PqPath                        types.String                        `tfsdk:"pq_path"`
	PqRatePerSec                  types.Float64                       `tfsdk:"pq_rate_per_sec"`
	PqStrictOrdering              types.Bool                          `tfsdk:"pq_strict_ordering"`
	RejectUnauthorized            types.Bool                          `tfsdk:"reject_unauthorized"`
	RemoveEmptyDirs               types.Bool                          `tfsdk:"remove_empty_dirs"`
	ReportLevel                   types.String                        `tfsdk:"report_level"`
	ReportMethod                  types.String                        `tfsdk:"report_method"`
	ResponseHonorRetryAfterHeader types.Bool                          `tfsdk:"response_honor_retry_after_header"`
	ResponseRetrySettings         []ItemsTypeResponseRetrySettings    `tfsdk:"response_retry_settings"`
	RetainBlobOnSuccess           types.Bool                          `tfsdk:"retain_blob_on_success"`
	RetrySettings                 *RetrySettingsType                  `tfsdk:"retry_settings"`
	Scope                         types.String                        `tfsdk:"scope"`
	ShouldLogInvalidRows          types.Bool                          `tfsdk:"should_log_invalid_rows"`
	StagePath                     types.String                        `tfsdk:"stage_path"`
	Streamtags                    []types.String                      `tfsdk:"streamtags"`
	SystemFields                  []types.String                      `tfsdk:"system_fields"`
	Table                         types.String                        `tfsdk:"table"`
	TenantID                      types.String                        `tfsdk:"tenant_id"`
	TextSecret                    types.String                        `tfsdk:"text_secret"`
	TimeoutRetrySettings          *TimeoutRetrySettingsType           `tfsdk:"timeout_retry_settings"`
	TimeoutSec                    types.Float64                       `tfsdk:"timeout_sec"`
	Type                          types.String                        `tfsdk:"type"`
	UseRoundRobinDNS              types.Bool                          `tfsdk:"use_round_robin_dns"`
	ValidateDatabaseSettings      types.Bool                          `tfsdk:"validate_database_settings"`
}
