// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type ServicesLimits struct {
	Connections   CommonServiceLimitConfigs `tfsdk:"connections"`
	Metrics       CommonServiceLimitConfigs `tfsdk:"metrics"`
	Notifications CommonServiceLimitConfigs `tfsdk:"notifications"`
}
