// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type UpgradePackageUrls struct {
	PackageHashURL types.String `tfsdk:"package_hash_url"`
	PackageURL     types.String `tfsdk:"package_url"`
}
