name: Cleanup TFProvider Workspace

on:
  workflow_call:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Run Acceptance Tests
        env:
          CRIBL_CLIENT_ID: ${{ secrets.CRIBL_CLIENT_ID }}
          CRIBL_CLIENT_SECRET: ${{ secrets.CRIBL_CLIENT_SECRET }}
          CRIBL_ORGANIZATION_ID: "beautiful-nguyen-y8y4azd"
          CRIBL_WORKSPACE_ID: "tfprovider"
        run: |
          

