name: Updated Speakeasy Version
on:


jobs:
  update_speakeasy_version:
    runs-on: ubuntu-latest
    steps:
      - name: Install Speakeasy
        uses: mheap/setup-go-cli@fa9b01cdd4115eac636164f0de43bf7d51c82697 # v1
        with:
          owner: speakeasy-api
          repo: speakeasy
          cli_name: speakeasy
          package_type: zip
  
      - name: Configure speakeasy CLI
        run: |
          mkdir -p ~/.speakeasy
          echo 'speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}' > ~/.speakeasy/config.yaml
      - name: Checkout current repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.ref }}
  
      - uses: dominikh/staticcheck-action@v1.3.1
  
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
  
      - name: Run Speakeasy with frozen workflow lockfile
        run: | 
          #update the thing
          version=`speakeasy update | cut -d ' ' -f 4`

          if [[ ! `echo $version | grep 

          speakeasy run --frozen-workflow-lockfile
